"use client";

import { Activity, BarChart3, CalendarCheck, CircleDollarSign, CreditCard, Heart, Megaphone, RefreshCw, RotateCcw, Star, Stethoscope, Target, TrendingUp, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useClinic } from "@/features/clinic/hooks/useClinic";
import DateRangeFilter from "@/features/date-range/DateRangeFilter";
import { useDateRange } from "@/features/date-range/useDateRange";
import { usePermission } from "@/features/users/hooks/usePermission";
import { useClinicAnalytics } from "../hooks/useClinicAnalytics";
import type { DoctorMetric, RankedMetric } from "../types/analytics";

const number = (value: number) => new Intl.NumberFormat("en-US").format(value);
const money = (value: number) => new Intl.NumberFormat("en-SA", { style: "currency", currency: "SAR", maximumFractionDigits: 0 }).format(value);
const paymentMethod: Record<string, string> = { cash: "نقدي", bank: "تحويل بنكي", bank_transfer: "تحويل بنكي", card: "بطاقة", mada: "مدى", visa: "فيزا", master_card: "ماستركارد", insurance: "تأمين", wallet: "رصيد العميل", split: "دفع مختلط", other: "أخرى" };

function Metric({ label, value, hint, tone = "slate" }: { label: string; value: string; hint?: string; tone?: "slate" | "green" | "blue" | "orange" }) {
  const tones = { slate: "bg-slate-950", green: "bg-emerald-600", blue: "bg-blue-600", orange: "bg-orange-500" };
  return <article className={`rounded-2xl p-5 text-white shadow-sm ${tones[tone]}`}><p className="text-sm opacity-75">{label}</p><p className="mt-2 text-2xl font-bold" dir="ltr">{value}</p>{hint && <p className="mt-2 text-xs opacity-75">{hint}</p>}</article>;
}

function Ranking({ title, icon: Icon, items, showRevenue = true }: { title: string; icon: typeof UserRound; items: RankedMetric[]; showRevenue?: boolean }) {
  const max = Math.max(...items.map((item) => showRevenue ? item.revenue : item.count), 1);
  return <section className="rounded-2xl border bg-white p-6 shadow-sm">
    <div className="flex items-center gap-3"><Icon className="text-violet-600" /><h2 className="text-lg font-bold">{title}</h2></div>
    {items.length === 0 ? <p className="py-10 text-center text-sm text-slate-500">لا توجد بيانات مسجلة خلال الفترة المحددة.</p> : <div className="mt-6 space-y-5">{items.map((item, index) => <div key={item.name}>
      <div className="mb-2 flex items-center justify-between gap-3"><div className="min-w-0"><p className="truncate font-semibold text-slate-900"><bdi>{number(index + 1)}. {item.name}</bdi></p><p className="text-xs text-slate-500">{number(item.count)} {showRevenue ? "علاج" : "جلسة"}</p></div>{showRevenue && <p className="shrink-0 font-bold" dir="ltr">{money(item.revenue)}</p>}</div>
      <div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-violet-600" style={{ width: `${((showRevenue ? item.revenue : item.count) / max) * 100}%` }} /></div>
    </div>)}</div>}
  </section>;
}

function DoctorPerformance({ items, showRevenue }: { items: DoctorMetric[]; showRevenue: boolean }) {
  return <section className="rounded-2xl border bg-white p-6 shadow-sm">
    <div className="flex items-center gap-3"><UserRound className="text-violet-600" /><div><h2 className="text-lg font-bold">أداء الطبيب</h2><p className="text-sm text-slate-500">الجلسات ونجاح العلاج واستغلال جدول المواعيد{showRevenue ? " والدخل المحقق" : ""}</p></div></div>
    {items.length === 0 ? <p className="py-10 text-center text-sm text-slate-500">لا يوجد نشاط مسجل للأطباء خلال الفترة المحددة.</p> : <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[640px] text-right text-sm"><thead><tr className="border-b text-slate-500"><th className="pb-3 font-medium">الطبيب</th><th className="pb-3 font-medium">الجلسات</th>{showRevenue && <th className="pb-3 font-medium">الدخل</th>}<th className="pb-3 font-medium">النجاح</th><th className="pb-3 font-medium">استغلال الجدول</th></tr></thead><tbody>{items.map((item) => <tr key={item.name} className="border-b last:border-0"><td className="py-4 font-semibold">{item.name}</td><td className="py-4">{number(item.count)}</td>{showRevenue && <td className="py-4 font-semibold" dir="ltr">{money(item.revenue)}</td>}<td className="py-4" dir="ltr">{number(item.successRate)}%</td><td className="py-4"><div className="flex items-center gap-2"><div className="h-2 w-20 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-cyan-500" style={{ width: `${item.utilizationRate}%` }} /></div><span dir="ltr">{number(item.utilizationRate)}%</span></div></td></tr>)}</tbody></table></div>}
  </section>;
}

export default function ClinicAnalyticsDashboard() {
  const financeAllowed = usePermission("reports.finance.view").allowed;
  const doctorRevenueAllowed = usePermission("reports.doctor_revenue.view").allowed;
  const marketingSpendAllowed = usePermission("marketing.spend.view").allowed;
  const feedbackAllowed = usePermission("reports.feedback.view").allowed;
  const loyaltyAllowed = usePermission("loyalty.view").allowed;
  const exportAllowed = usePermission("reports.export").allowed;
  const range = useDateRange();
  const { clinic, selectedBranch, isLoading: clinicLoading } = useClinic();
  const clinicId = clinic?.id ?? 0;
  const branchId = selectedBranch?.id ?? 0;
  const { data, isLoading, error, refetch, isFetching } = useClinicAnalytics(clinicId, branchId, range.from, range.to, { finance: financeAllowed, doctorRevenue: doctorRevenueAllowed, marketingSpend: marketingSpendAllowed, feedback: feedbackAllowed, loyalty: loyaltyAllowed });

  if (clinicLoading || isLoading) return <div className="rounded-2xl bg-white p-12 text-center shadow-sm">جارٍ تحميل تحليلات العيادة...</div>;
  if (!clinicId || !branchId) return <div className="rounded-2xl border border-amber-200 bg-amber-50 p-6 text-amber-800">حدد العيادة والفرع لعرض التقارير.</div>;
  if (error || !data) return <div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-red-700"><p className="font-bold">تعذر تحميل التحليلات</p><p className="mt-2 text-sm">{error instanceof Error ? error.message : "حدث خطأ غير متوقع"}</p><Button className="mt-4" onClick={() => void refetch()}>إعادة المحاولة</Button></div>;

  const report = data;
  const trendMax = Math.max(...data.monthlyTrend.map((item) => item.revenue), 1);
  const bookingMax = Math.max(...data.monthlyTrend.map((item) => item.bookings), 1);
  const dailyMax = Math.max(...data.dailyTrend.map((item) => item.revenue), 1);
  function exportReport() { const rows = [["المؤشر", "القيمة"], ["المواعيد", String(report.booking.total)], ["المكتمل", String(report.booking.completed)], ["عدم الحضور", String(report.booking.noShows)], ...(financeAllowed ? [["دخل الشهر", String(report.revenue.month)], ["المبالغ المستحقة", String(report.finance.outstanding)]] : [])]; const blob = new Blob(["\ufeff" + rows.map((row) => row.join(",")).join("\n")], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `panthera-report-${range.from}-${range.to}.csv`; link.click(); URL.revokeObjectURL(url); }

  const sections = [...(financeAllowed ? [["الإيرادات", "revenue"]] : []), ["المواعيد", "booking"], ["أداء الطبيب", "doctors"], ["التسويق", "marketing"], ...(feedbackAllowed || loyaltyAllowed ? [["تجربة المريض", "experience"]] : []), ...(financeAllowed ? [["المالية", "finance"]] : [])];
  return <div className="space-y-7" dir="rtl">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-violet-600">تحليلات العيادة</p><h1 className="mt-1 text-3xl font-bold text-slate-950">التقارير والأداء</h1><p className="mt-2 text-sm text-slate-500">{clinic?.name} · {selectedBranch?.name}</p></div><div className="flex gap-2">{exportAllowed && <Button variant="outline" onClick={exportReport}>تصدير</Button>}<Button variant="outline" onClick={() => void refetch()} disabled={isFetching}><RefreshCw className={isFetching ? "animate-spin" : ""} />{isFetching ? "جارٍ التحديث" : "تحديث"}</Button></div></header>
    <DateRangeFilter />
    <nav aria-label="أقسام التحليلات" className="sticky top-3 z-20 flex gap-2 overflow-x-auto rounded-2xl border bg-white/95 p-2 shadow-sm backdrop-blur">{sections.map(([label, target]) => <a key={target} href={`#${target}`} className="shrink-0 rounded-xl px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-950 hover:text-white">{label}</a>)}</nav>

    {financeAllowed && <section id="revenue" className="scroll-mt-24 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="إيرادات اليوم" value={money(data.revenue.today)} tone="green" /><Metric label="إيرادات هذا الشهر" value={money(data.revenue.month)} hint={`${data.revenue.trendPercent >= 0 ? "+" : ""}${data.revenue.trendPercent.toFixed(1)}% مقارنة بالشهر السابق`} tone="blue" /><Metric label="الإيرادات المتوقعة" value={money(data.revenue.forecast)} hint="تقدير وفق معدل التحصيل الحالي" /><Metric label="المبالغ المستحقة" value={money(data.finance.outstanding)} hint={`نسبة التحصيل ${number(data.finance.collectionRate)}%`} tone={data.finance.outstanding > 0 ? "orange" : "green"} /></section>}
    <section id="booking" className="scroll-mt-24 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="نسبة الاكتمال" value={`${number(data.booking.completionRate)}%`} hint={`${number(data.booking.completed)} موعد مكتمل`} /><Metric label="نسبة عدم الحضور" value={`${number(data.booking.noShowRate)}%`} hint={`${number(data.booking.noShows)} حالة عدم حضور`} tone={data.booking.noShowRate > 15 ? "orange" : "slate"} /><Metric label="نسبة الإلغاء" value={`${number(data.booking.cancellationRate)}%`} hint={`${number(data.booking.cancelled)} موعد ملغي`} />{financeAllowed && <Metric label="المبالغ المستردة" value={money(data.finance.refunded)} />}</section>

    <section className="grid gap-6 xl:grid-cols-[1.4fr_1fr]">{financeAllowed && <div className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><TrendingUp className="text-emerald-600" /><div><h2 className="font-bold">اتجاه الإيرادات خلال 6 أشهر</h2><p className="text-sm text-slate-500">المبالغ المحصلة شهريًا</p></div></div><div className="mt-8 flex h-64 items-end gap-3">{data.monthlyTrend.map((item) => <div key={item.label} className="flex h-full flex-1 flex-col items-center justify-end gap-2"><span className="text-xs font-semibold">{item.revenue ? money(item.revenue) : "—"}</span><div className="flex h-44 w-full items-end rounded-xl bg-slate-100 p-1"><div className="w-full rounded-lg bg-emerald-500" style={{ height: `${item.revenue ? Math.max((item.revenue / trendMax) * 100, 6) : 2}%` }} /></div><span className="text-xs text-slate-500">{item.label}</span></div>)}</div></div>}<div className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><CalendarCheck className="text-blue-600" /><div><h2 className="font-bold">حجم المواعيد</h2><p className="text-sm text-slate-500">المواعيد المسجلة شهريًا</p></div></div><div className="mt-7 space-y-4">{data.monthlyTrend.map((item) => <div key={item.label}><div className="mb-1 flex justify-between text-sm"><span>{item.label}</span><strong>{number(item.bookings)}</strong></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-blue-500" style={{ width: `${(item.bookings / bookingMax) * 100}%` }} /></div></div>)}</div></div></section>
    {financeAllowed && <section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><BarChart3 className="text-cyan-600" /><div><h2 className="font-bold">الإيرادات اليومية</h2><p className="text-sm text-slate-500">المبالغ المحصلة خلال آخر 14 يومًا</p></div></div><div className="mt-7 flex h-52 items-end gap-2 overflow-x-auto">{data.dailyTrend.map((item) => <div key={item.label} className="flex h-full min-w-10 flex-1 flex-col items-center justify-end gap-2"><div className="flex h-36 w-full items-end rounded-lg bg-slate-100 p-1" title={`${item.label}: ${money(item.revenue)}`}><div className="w-full rounded-md bg-cyan-500" style={{ height: `${item.revenue ? Math.max((item.revenue / dailyMax) * 100, 5) : 2}%` }} /></div><span className="text-[10px] text-slate-500">{item.label}</span></div>)}</div></section>}

    <div id="doctors" className="scroll-mt-24"><DoctorPerformance items={data.doctors} showRevenue={doctorRevenueAllowed} /></div>
    <section className="grid gap-6 lg:grid-cols-2">{doctorRevenueAllowed && <Ranking title="ترتيب دخل الطبيب" icon={UserRound} items={data.doctors} />}<Ranking title="أداء الخدمات" icon={Stethoscope} items={data.services} showRevenue={doctorRevenueAllowed} /></section>
    <section id="marketing" className="scroll-mt-24 space-y-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="العملاء المحتملون" value={number(data.marketing.totalLeads)} tone="blue" /><Metric label="الحجوزات المحولة" value={number(data.marketing.convertedLeads)} tone="green" /><Metric label="نسبة التحويل" value={`${number(data.marketing.conversionRate)}%`} />{marketingSpendAllowed && <Metric label="تكلفة الحجز" value={data.marketing.costPerBooking == null ? "غير متاح" : money(data.marketing.costPerBooking)} hint={`الإنفاق المسجل: ${money(data.marketing.spend)}`} />}</div><div className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Megaphone className="text-fuchsia-600" /><div><h2 className="font-bold">مصادر العملاء والحملات</h2><p className="text-sm text-slate-500">الحجوزات ونسبة التحويل حسب المصدر</p></div></div>{data.marketing.sources.length === 0 ? <p className="py-10 text-center text-sm text-slate-500">لا توجد مصادر عملاء مسجلة خلال الفترة المحددة.</p> : <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-right text-sm"><thead><tr className="border-b text-slate-500"><th className="pb-3">المصدر</th><th className="pb-3">العملاء</th><th className="pb-3">المحولون</th><th className="pb-3">التحويل</th>{marketingSpendAllowed && <><th className="pb-3">الإنفاق</th><th className="pb-3">الإيراد</th><th className="pb-3">العائد</th></>}</tr></thead><tbody>{data.marketing.sources.map((item) => <tr key={item.source} className="border-b last:border-0"><td className="py-4 font-semibold">{item.source}</td><td>{number(item.leads)}</td><td>{number(item.converted)}</td><td><span className="inline-flex items-center gap-1"><Target className="h-4 w-4 text-emerald-600" />{number(item.conversionRate)}%</span></td>{marketingSpendAllowed && <><td>{money(item.spend)}</td><td className="font-semibold">{money(item.revenue)}</td><td>{item.roi == null ? "—" : `${item.roi.toFixed(1)}%`}</td></>}</tr>)}</tbody></table></div>}</div></section>
    {(feedbackAllowed || loyaltyAllowed) && <section id="experience" className="scroll-mt-24 space-y-5">
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{feedbackAllowed && <><Metric label="متوسط تقييم المرضى" value={data.experience.count ? `${data.experience.average.toFixed(1)} / 5` : "— / 5"} tone="orange" /><Metric label="عدد التقييمات" value={number(data.experience.count)} /></>}{loyaltyAllowed && <><Metric label="أعضاء برنامج الولاء" value={number(data.loyalty.members)} tone="blue" /><Metric label="النقاط المتاحة" value={number(data.loyalty.availablePoints)} tone="green" /></>}</div>
      <div className="grid gap-6 xl:grid-cols-2">{feedbackAllowed && <div className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Heart className="text-rose-500" /><div><h2 className="font-bold">تقييمات تطبيق المريض</h2><p className="text-sm text-slate-500">آخر التقييمات المرتبطة بزيارات مكتملة</p></div></div><div className="mt-5 space-y-3">{data.experience.recent.length === 0 ? <p className="py-8 text-center text-sm text-slate-500">لا توجد تقييمات خلال الفترة المحددة.</p> : data.experience.recent.map(item=><div key={item.id} className="rounded-xl bg-slate-50 p-4"><div className="flex items-center justify-between gap-3"><b>{item.customer ? `${item.customer.first_name??""} ${item.customer.last_name??""}`.trim() || item.customer.customer_code : "مريض"}</b><span className="inline-flex items-center gap-1 font-black text-amber-600"><Star className="size-4 fill-current" />{number(item.rating)} / 5</span></div>{item.comment && <p className="mt-2 text-sm text-slate-700">{item.comment}</p>}{item.tags?.length>0 && <div className="mt-2 flex flex-wrap gap-1">{item.tags.map(tag=><span key={tag} className="rounded-full bg-white px-2 py-1 text-xs text-slate-600">{tag}</span>)}</div>}</div>)}</div></div>}{loyaltyAllowed && <div className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Star className="text-lime-600" /><div><h2 className="font-bold">برنامج الولاء</h2><p className="text-sm text-slate-500">توزيع العضويات والنقاط الفعلية في تطبيق المريض</p></div></div><div className="mt-5 space-y-4">{data.loyalty.tiers.map(item=><div key={item.tier}><div className="mb-1 flex justify-between"><span>{({silver:"فضي",gold:"ذهبي",platinum:"بلاتيني"} as Record<string,string>)[item.tier]??item.tier}</span><b>{number(item.count)}</b></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-lime-500" style={{width:`${data.loyalty.members ? (item.count/data.loyalty.members)*100 : 0}%`}} /></div></div>)}</div><div className="mt-6 rounded-xl bg-slate-950 p-4 text-white"><p className="text-xs text-slate-400">إجمالي النقاط المكتسبة تاريخيًا</p><strong className="mt-1 block text-2xl">{number(data.loyalty.lifetimePoints)}</strong></div></div>}</div>
    </section>}
    {financeAllowed && <section id="finance" className="scroll-mt-24 grid gap-6 lg:grid-cols-[1fr_1.2fr]"><div className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><CreditCard className="text-cyan-600" /><h2 className="font-bold">طرق الدفع</h2></div><div className="mt-5 space-y-3">{data.paymentMethods.map((item) => <div key={item.method} className="flex items-center justify-between rounded-xl bg-slate-50 p-4"><div><p className="font-semibold">{paymentMethod[item.method] ?? item.method.replaceAll("_", " ")}</p><p className="text-xs text-slate-500">{number(item.count)} عملية دفع</p></div><strong dir="ltr">{money(item.amount)}</strong></div>)}</div></div><div className="rounded-2xl bg-slate-950 p-6 text-white shadow-sm"><div className="flex items-center gap-3"><Activity className="text-cyan-400" /><h2 className="text-lg font-bold">مؤشرات المالية</h2></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-white/10 p-4"><CircleDollarSign className="text-emerald-400" /><p className="mt-3 text-sm text-slate-300">متوسط الدفعة</p><strong className="text-xl" dir="ltr">{money(data.revenue.averagePayment)}</strong></div><div className="rounded-xl bg-white/10 p-4"><RotateCcw className="text-orange-400" /><p className="mt-3 text-sm text-slate-300">نسبة الاسترداد</p><strong className="text-xl" dir="ltr">{number(data.finance.refundRate)}%</strong></div></div></div></section>}
  </div>;
}
