"use client";
import { useEffect, useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Headphones, Plus, Send } from "lucide-react";
import { toast } from "sonner";
import { useLocale } from "@/components/LocaleProvider";
import { usePermission } from "@/features/users/hooks/usePermission";
import { createClient } from "@/lib/supabase/client";
import { createTicket, getMessages, getTickets, sendMessage, updateTicket } from "./api";

const statusAr={open:"مفتوحة",in_progress:"قيد المعالجة",resolved:"تم الحل",closed:"مغلقة"}as const;
const categoryAr={question:"استفسار",problem:"مشكلة",suggestion:"اقتراح"}as const;
function supportError(error:unknown,isArabic:boolean){const message=error instanceof Error?error.message:String(error);if(message.includes("SUPPORT_STAFF_PROFILE_REQUIRED"))return isArabic?"حساب الدخول غير مرتبط بملف موظف نشط. أضف البريد نفسه للموظف ثم أعد تسجيل الدخول.":"Your login is not linked to an active staff profile. Add the same email to the employee, then sign in again.";if(message.includes("SUPPORT_CREATE_PERMISSION_REQUIRED"))return isArabic?"صلاحية إنشاء طلبات الدعم غير مفعلة لهذا المستخدم.":"This user does not have permission to create support requests.";if(message.includes("SUPPORT_TICKET_CLOSED"))return isArabic?"هذه المحادثة مغلقة. أنشئ طلب دعم جديدًا.":"This conversation is closed. Create a new support request.";return isArabic?"تعذر إرسال الطلب. راجع اتصال الإنترنت ثم حاول مرة أخرى.":"The request could not be sent. Check the connection and try again."}
export default function SupportCenter(){
 const{isArabic,text}=useLocale(),qc=useQueryClient(),manage=usePermission("support.manage");const[selected,setSelected]=useState<number|null>(null),[newOpen,setNewOpen]=useState(false),[body,setBody]=useState("");
 const tickets=useQuery({queryKey:["support-tickets"],queryFn:getTickets,refetchInterval:15000}),messages=useQuery({queryKey:["support-messages",selected],queryFn:()=>getMessages(selected!),enabled:!!selected}),active=tickets.data?.find(x=>x.id===selected);
 useEffect(()=>{const db=createClient(),channel=db.channel("support-chat").on("postgres_changes",{event:"*",schema:"public",table:"support_tickets"},()=>void qc.invalidateQueries({queryKey:["support-tickets"]})).on("postgres_changes",{event:"INSERT",schema:"public",table:"support_messages"},()=>{void qc.invalidateQueries({queryKey:["support-tickets"]});void qc.invalidateQueries({queryKey:["support-messages",selected]})}).subscribe();return()=>{void db.removeChannel(channel)}},[qc,selected]);
 const sending=useMutation({mutationFn:()=>sendMessage(selected!,body.trim()),onSuccess:async()=>{setBody("");await qc.invalidateQueries({queryKey:["support-messages",selected]})},onError:error=>toast.error(supportError(error,isArabic))});
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const id=await createTicket({subject:String(f.get("subject")),category:String(f.get("category")),priority:String(f.get("priority")),body:String(f.get("body"))});setNewOpen(false);setSelected(id);await qc.invalidateQueries({queryKey:["support-tickets"]});toast.success(text("Request sent","تم إرسال الطلب"))}catch(error){toast.error(supportError(error,isArabic))}}
 return <div className="space-y-5" dir={isArabic?"rtl":"ltr"}><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-black text-cyan-700">PANTHERA SUPPORT</p><h1 className="text-3xl font-black">{manage.allowed?text("Support inbox","صندوق وارد الدعم"):text("Technical support","الدعم الفني")}</h1><p className="mt-2 text-slate-500">{manage.allowed?text("Receive and resolve staff requests.","استقبل طلبات الموظفين وتابع حلها."):text("Ask about the system or report a work problem.","اسأل عن النظام أو أبلغ عن مشكلة أثناء العمل.")}</p></div><button onClick={()=>setNewOpen(true)} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-[#101c25] px-5 font-bold text-white"><Plus className="size-5"/>{text("New request","طلب جديد")}</button></header>
 {newOpen&&<form onSubmit={add} className="grid gap-3 rounded-3xl border bg-white p-5"><h2 className="text-xl font-black">{text("Start support chat","بدء محادثة دعم")}</h2><input required minLength={3} name="subject" placeholder={text("Subject","عنوان الطلب")} className="h-12 rounded-xl border px-4"/><div className="grid gap-3 sm:grid-cols-2"><select name="category" className="h-12 rounded-xl border px-4"><option value="question">{text("System question","استفسار عن النظام")}</option><option value="problem">{text("Problem","مشكلة")}</option><option value="suggestion">{text("Suggestion","اقتراح")}</option></select><select name="priority" className="h-12 rounded-xl border px-4"><option value="normal">{text("Normal","عادية")}</option><option value="high">{text("High","عالية")}</option><option value="urgent">{text("Urgent","عاجلة")}</option><option value="low">{text("Low","منخفضة")}</option></select></div><textarea required name="body" rows={4} placeholder={text("Describe the question or problem...","اشرح الاستفسار أو المشكلة...")} className="rounded-xl border p-4"/><div className="flex gap-2"><button className="rounded-xl bg-cyan-600 px-5 py-3 font-bold text-white">{text("Send","إرسال")}</button><button type="button" onClick={()=>setNewOpen(false)} className="rounded-xl border px-5 py-3 font-bold">{text("Cancel","إلغاء")}</button></div></form>}
 <div className="grid min-h-[620px] overflow-hidden rounded-3xl border bg-white shadow-sm lg:grid-cols-[340px_1fr]"><aside className="border-b lg:border-b-0 lg:border-e"><div className="border-b p-4 font-black">{text("Conversations","المحادثات")} ({tickets.data?.length??0})</div><div className="max-h-[560px] overflow-y-auto">{tickets.data?.map(ticket=><button key={ticket.id} onClick={()=>setSelected(ticket.id)} className={`block w-full border-b p-4 text-start ${selected===ticket.id?"bg-cyan-50":"hover:bg-slate-50"}`}><span className="flex justify-between gap-2"><strong className="truncate">{ticket.subject}</strong><small>#{ticket.id}</small></span>{manage.allowed&&<p className="mt-1 text-xs text-slate-500">{ticket.requester?.staff_name||ticket.requester?.email}</p>}<p className="mt-2 flex justify-between text-xs"><span>{isArabic?categoryAr[ticket.category]:ticket.category}</span><span className={ticket.status==="resolved"?"text-emerald-600":"text-amber-600"}>{isArabic?statusAr[ticket.status]:ticket.status.replace("_"," ")}</span></p></button>)}{!tickets.isLoading&&!tickets.data?.length&&<p className="p-8 text-center text-slate-500">{text("No conversations yet.","لا توجد محادثات حتى الآن.")}</p>}</div></aside>
 <section className="flex min-h-[500px] flex-col">{!active?<div className="grid flex-1 place-items-center text-center"><div><Headphones className="mx-auto size-14 text-cyan-600"/><h2 className="mt-3 font-black">{text("Choose a conversation","اختر محادثة")}</h2></div></div>:<><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><h2 className="font-black">{active.subject}</h2><p className="text-xs text-slate-500">#{active.id}</p></div>{manage.allowed&&<select value={active.status} onChange={async e=>{await updateTicket(active.id,e.target.value);await qc.invalidateQueries({queryKey:["support-tickets"]})}} className="h-10 rounded-xl border px-3"><option value="open">{text("Open","مفتوحة")}</option><option value="in_progress">{text("In progress","قيد المعالجة")}</option><option value="resolved">{text("Resolved","تم الحل")}</option><option value="closed">{text("Closed","مغلقة")}</option></select>}</div><div className="flex-1 space-y-3 overflow-y-auto bg-slate-50 p-4">{messages.data?.map(message=>{const mine=manage.allowed?message.sender_staff_id!==active.requester_staff_id:message.sender_staff_id===active.requester_staff_id;return <div key={message.id} className={`flex ${mine?"justify-end":"justify-start"}`}><div className={`max-w-[85%] rounded-2xl px-4 py-3 ${mine?"bg-[#101c25] text-white":"border bg-white"}`}><p className="whitespace-pre-wrap text-sm leading-6">{message.body}</p><small className={mine?"text-slate-300":"text-slate-400"}>{message.sender?.staff_name}</small></div></div>})}</div>{active.status!=="closed"&&<form onSubmit={e=>{e.preventDefault();if(body.trim())sending.mutate()}} className="flex gap-2 border-t p-3"><textarea rows={1} value={body} onChange={e=>setBody(e.target.value)} placeholder={text("Write a message...","اكتب رسالة...")} className="min-h-12 flex-1 resize-none rounded-xl border p-3"/><button disabled={!body.trim()} className="grid size-12 place-items-center rounded-xl bg-cyan-600 text-white disabled:opacity-50"><Send className="size-5"/></button></form>}</>}</section></div></div>;
}
