"use client";
import {useState,type FormEvent} from "react";
import {BadgeCheck,CalendarClock,Clock,RefreshCw,ShieldCheck,UserPlus,Users} from "lucide-react";
import {useQueryClient} from "@tanstack/react-query";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {useClinic} from "@/features/clinic/hooks/useClinic";
import {addStaff,assignRole,saveAttendance,saveShift,updateStaff} from "../api/staff.api";
import {useStaffData} from "../hooks/useStaffData";

const days=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
function time(value:string|null){if(!value)return "—";return new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit",hour12:true}).format(new Date(value));}

export default function StaffDashboard(){
 const {clinic,selectedBranch,isLoading:clinicLoading}=useClinic();const clinicId=clinic?.id??0;const branchId=selectedBranch?.id??0;
 const {data,isLoading,error,refetch,isFetching}=useStaffData(clinicId,branchId);const queryClient=useQueryClient();const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 async function run(action:()=>Promise<unknown>,success:string){setBusy(true);setMessage("");try{await action();await queryClient.invalidateQueries({queryKey:["staff-hr",clinicId,branchId]});setMessage(success);}catch(e){setMessage(e instanceof Error?e.message:"Operation failed");}finally{setBusy(false);}}
 async function createMember(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const el=e.currentTarget;await run(()=>addStaff({clinic_id:clinicId,branch_id:branchId,staff_name:String(f.get("name")),employee_code:String(f.get("code")||"")||null,role:String(f.get("type")),department:String(f.get("department")||"")||null,job_title:String(f.get("title")||"")||null,phone:String(f.get("phone")||"")||null,email:String(f.get("email")||"")||null,hire_date:String(f.get("hire")||"")||null,salary:Number(f.get("salary")||0),employment_status:"active",is_active:true}),"Employee added.");el.reset();}
 async function attendance(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const now=new Date().toISOString();const mode=String(f.get("mode"));await run(()=>saveAttendance({clinic_id:clinicId,branch_id:branchId,staff_id:Number(f.get("staff")),work_date:String(f.get("date")),status:String(f.get("status")),...(mode==="in"?{check_in:now}:{check_out:now})}),mode==="in"?"Check-in recorded.":"Check-out recorded.");}
 async function shift(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(()=>saveShift({clinic_id:clinicId,branch_id:branchId,staff_id:Number(f.get("staff")),weekday:Number(f.get("day")),start_time:String(f.get("start")),end_time:String(f.get("end")),is_working:true}),"Schedule saved.");}
 async function role(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(()=>assignRole(Number(f.get("staff")),Number(f.get("role"))),"Role assigned.");}
 if(clinicLoading||isLoading)return <div className="rounded-2xl bg-white p-12 text-center">Loading Staff & HR...</div>;
 if(!clinicId||!branchId)return <div className="rounded-2xl border border-amber-200 bg-amber-50 p-6">Select a clinic and branch.</div>;
 if(error||!data)return <div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-red-700"><strong>Staff & HR is not active yet.</strong><p className="mt-2 text-sm">{error instanceof Error?error.message:"Run the Phase 6 SQL setup."}</p></div>;
 const active=data.members.filter(i=>i.is_active&&i.employment_status!=="terminated");const doctors=active.filter(i=>i.role?.toLowerCase().includes("doctor"));const today=new Date().toISOString().slice(0,10);const todayAttendance=data.attendance.filter(i=>i.work_date===today);const present=todayAttendance.filter(i=>["present","late"].includes(i.status)).length;
 return <div className="space-y-7">
  <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-wider text-indigo-700">Phase 6</p><h1 className="mt-1 text-3xl font-black">Staff & HR</h1><p className="mt-2 text-slate-500">Employees, attendance, schedules, roles and permissions in one workspace.</p></div><Button variant="outline" onClick={()=>void refetch()} disabled={isFetching}><RefreshCw className={isFetching?"animate-spin":""}/> Refresh</Button></header>
  {message&&<div className="rounded-xl border border-indigo-200 bg-indigo-50 p-4 text-sm font-medium text-indigo-900">{message}</div>}
  <nav className="sticky top-3 z-20 flex gap-2 overflow-x-auto rounded-2xl border bg-white/95 p-2 shadow-sm backdrop-blur">{[["Overview","overview"],["Employees","employees"],["Attendance","attendance"],["Schedule","schedule"],["Roles","roles"]].map(([l,id])=><a key={id} href={`#${id}`} className="shrink-0 rounded-xl px-4 py-2 text-sm font-semibold hover:bg-slate-950 hover:text-white">{l}</a>)}</nav>
  <section id="overview" className="scroll-mt-24 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Active employees",active.length,Users],["Doctors",doctors.length,BadgeCheck],["Present today",present,Clock],["HR roles",data.roles.length,ShieldCheck]].map(([l,v,I])=>{const Icon=I as typeof Users;return <article key={String(l)} className="rounded-2xl bg-slate-950 p-5 text-white"><Icon className="text-indigo-300"/><p className="mt-4 text-sm text-slate-400">{String(l)}</p><p className="mt-1 text-3xl font-bold">{String(v)}</p></article>;})}</section>
  <section id="employees" className="scroll-mt-24 grid gap-6 xl:grid-cols-[1fr_1.7fr]"><form onSubmit={createMember} className="space-y-3 rounded-2xl border bg-white p-6 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-bold"><UserPlus/> Add employee</h2><Input name="name" required placeholder="Full name"/><div className="grid grid-cols-2 gap-3"><Input name="code" placeholder="Employee code"/><select name="type" required className="h-9 rounded-md border px-3"><option value="doctor">Doctor</option><option value="nurse">Nurse</option><option value="reception">Reception</option><option value="coordinator">Coordinator</option><option value="finance">Finance</option><option value="admin">Admin</option></select><Input name="department" placeholder="Department"/><Input name="title" placeholder="Job title"/><Input name="phone" placeholder="Phone"/><Input name="email" type="email" placeholder="Email"/><Input name="hire" type="date"/><Input name="salary" type="number" min="0" placeholder="Salary"/></div><Button disabled={busy}>Add employee</Button></form><div className="overflow-x-auto rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Employee directory</h2><table className="mt-5 w-full min-w-[720px] text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="pb-3">Employee</th><th>Type</th><th>Department</th><th>Contact</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.members.map(m=><tr key={m.id} className="border-b last:border-0"><td className="py-4"><strong>{m.staff_name}</strong><p className="text-xs text-slate-500">{m.employee_code||m.job_title||"—"}</p></td><td className="capitalize">{m.role||"—"}</td><td>{m.department||"—"}</td><td>{m.phone||m.email||"—"}</td><td className="capitalize">{m.employment_status||"active"}</td><td><Button size="sm" variant="outline" disabled={busy} onClick={()=>void run(()=>updateStaff(m.id,{is_active:!m.is_active,employment_status:m.is_active?"inactive":"active"}),m.is_active?"Employee deactivated.":"Employee activated.")}>{m.is_active?"Deactivate":"Activate"}</Button></td></tr>)}</tbody></table></div></section>
  <section id="attendance" className="scroll-mt-24 grid gap-6 xl:grid-cols-[1fr_1.6fr]"><form onSubmit={attendance} className="space-y-3 rounded-2xl border bg-white p-6 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-bold"><Clock/> Attendance</h2><select name="staff" required className="h-10 w-full rounded-md border px-3"><option value="">Employee</option>{active.map(m=><option key={m.id} value={m.id}>{m.staff_name}</option>)}</select><Input name="date" type="date" required defaultValue={today}/><select name="status" className="h-10 w-full rounded-md border px-3"><option value="present">Present</option><option value="late">Late</option><option value="absent">Absent</option><option value="leave">Leave</option><option value="sick">Sick</option></select><select name="mode" className="h-10 w-full rounded-md border px-3"><option value="in">Check in now</option><option value="out">Check out now</option></select><Button disabled={busy}>Record attendance</Button></form><div className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">This month attendance</h2><div className="mt-5 space-y-3">{data.attendance.slice(0,30).map(a=><div key={a.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 p-4"><div><p className="font-semibold">{a.member?.staff_name}</p><p className="text-xs text-slate-500">{a.work_date} · {a.status}</p></div><span className="text-sm">{time(a.check_in)} — {time(a.check_out)}</span></div>)}</div></div></section>
  <section id="schedule" className="scroll-mt-24 grid gap-6 xl:grid-cols-[1fr_1.6fr]"><form onSubmit={shift} className="space-y-3 rounded-2xl border bg-white p-6 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-bold"><CalendarClock/> Work schedule</h2><select name="staff" required className="h-10 w-full rounded-md border px-3"><option value="">Employee</option>{active.map(m=><option key={m.id} value={m.id}>{m.staff_name}</option>)}</select><select name="day" className="h-10 w-full rounded-md border px-3">{days.map((d,i)=><option key={d} value={i}>{d}</option>)}</select><div className="grid grid-cols-2 gap-3"><Input name="start" required type="time"/><Input name="end" required type="time"/></div><Button disabled={busy}>Save schedule</Button></form><div className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Weekly schedules</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{data.shifts.map(s=><div key={s.id} className="rounded-xl bg-slate-50 p-4"><p className="font-semibold">{s.member?.staff_name}</p><p className="text-sm text-slate-500">{days[s.weekday]} · {s.start_time.slice(0,5)}–{s.end_time.slice(0,5)}</p></div>)}</div></div></section>
  <section id="roles" className="scroll-mt-24 grid gap-6 xl:grid-cols-[1fr_1.6fr]"><form onSubmit={role} className="space-y-3 rounded-2xl border bg-white p-6 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-bold"><ShieldCheck/> Assign role</h2><select name="staff" required className="h-10 w-full rounded-md border px-3"><option value="">Employee</option>{active.map(m=><option key={m.id} value={m.id}>{m.staff_name}</option>)}</select><select name="role" required className="h-10 w-full rounded-md border px-3"><option value="">HR role</option>{data.roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><Button disabled={busy}>Assign role</Button></form><div className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Roles & permissions</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{data.roles.map(r=><div key={r.id} className="rounded-xl border p-4"><p className="font-semibold">{r.name}</p><p className="mt-1 text-xs text-slate-500">{r.description}</p><div className="mt-3 flex flex-wrap gap-1">{(r.permissions??[]).map(x=>x.permission&&<span key={x.permission.id} className="rounded-full bg-indigo-50 px-2 py-1 text-[10px] font-medium text-indigo-700">{x.permission.name}</span>)}</div></div>)}</div></div></section>
 </div>;
}
