"use client";

import Link from "next/link";
import { useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Building2, DoorOpen, Plus, Stethoscope, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { useClinic } from "@/features/clinic/hooks/useClinic";
import { useMasterData } from "@/features/master-data/hooks/useMasterData";
import { usePermissionAccess } from "@/features/users/hooks/usePermissionAccess";
import type { MasterBranch, MasterRoom } from "@/features/master-data/types/master-data";
import { isApprovedDoctor } from "@/features/master-data/utils/doctors";
import { saveBranch, saveRoom } from "../api/master-settings.api";

const field = "h-11 w-full rounded-xl border bg-white px-3 outline-none focus:border-cyan-500";
export default function MasterSettings() {
  const { clinic } = useClinic(); const access = usePermissionAccess(); const master = useMasterData(); const qc = useQueryClient();
  const [branch, setBranch] = useState<Partial<MasterBranch> | null>(null), [room, setRoom] = useState<Partial<MasterRoom> | null>(null);
  const canManageBranches = access.can("branches.manage", "settings.manage"), canManageRooms = access.can("rooms.manage", "settings.manage");
  const refresh = async () => { await Promise.all([qc.invalidateQueries({queryKey:["master-data"]}),qc.invalidateQueries({queryKey:["clinic-context"]}),qc.invalidateQueries({queryKey:["appointment-master-data"]})]); };
  const branchMutation = useMutation({ mutationFn: saveBranch, onSuccess: async()=>{await refresh();setBranch(null);toast.success("تم حفظ الفرع");} });
  const roomMutation = useMutation({ mutationFn: saveRoom, onSuccess: async()=>{await refresh();setRoom(null);toast.success("تم حفظ الغرفة");} });
  if (master.isLoading) return <div className="rounded-2xl border bg-white p-12 text-center">جارٍ تحميل البيانات الأساسية…</div>;
  if (master.error) return <div className="rounded-2xl bg-red-50 p-6 text-red-700">{master.error.message}</div>;
  const data = master.data; if (!clinic || !data) return <div>اختر العيادة أولًا.</div>;
  return <main className="space-y-5" dir="rtl"><header><h1 className="text-3xl font-black">البيانات الأساسية</h1><p className="text-slate-500">الفروع والغرف والأطباء والخدمات المستخدمة في النظام كله.</p></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Building2/>} label="الفروع" value={data.branches.length}/><Metric icon={<DoorOpen/>} label="الغرف" value={data.rooms.length}/><Metric icon={<UsersRound/>} label="الأطباء" value={data.staff.filter(isApprovedDoctor).length}/><Metric icon={<Stethoscope/>} label="الخدمات" value={data.services.length}/></section>
    <section className="grid gap-5 xl:grid-cols-2"><Catalog title="الفروع" action={canManageBranches && <button onClick={()=>setBranch({is_active:true})} className="rounded-xl bg-slate-950 px-4 py-2 font-bold text-white"><Plus className="ms-1 inline size-4"/>فرع</button>}>{branch && <BranchForm draft={branch} setDraft={setBranch} save={() => branchMutation.mutate({clinic_id:clinic.id,name:branch.name || "",...branch})}/>}<div className="grid gap-2">{data.branches.map(item=><button key={item.id} onClick={()=>canManageBranches&&setBranch(item)} className="rounded-xl border p-3 text-start hover:bg-slate-50"><b>{item.name}</b><span className="block text-xs text-slate-500">{item.code || "بدون رمز"} · {item.phone || "بدون هاتف"} · {item.is_active?"نشط":"متوقف"}</span></button>)}</div></Catalog>
      <Catalog title="الغرف" action={canManageRooms && <button onClick={()=>setRoom({is_active:true,branch_id:data.branches[0]?.id})} className="rounded-xl bg-slate-950 px-4 py-2 font-bold text-white"><Plus className="ms-1 inline size-4"/>غرفة</button>}>{room && <RoomForm draft={room} branches={data.branches} setDraft={setRoom} save={() => roomMutation.mutate({branch_id:Number(room.branch_id),name:room.name || "",...room})}/>}<div className="grid gap-2">{data.rooms.map(item=><button key={item.id} onClick={()=>canManageRooms&&setRoom(item)} className="rounded-xl border p-3 text-start hover:bg-slate-50"><b>{item.name}</b><span className="block text-xs text-slate-500">{data.branches.find(x=>x.id===item.branch_id)?.name || "فرع غير محدد"} · {item.room_type || "غرفة علاج"}</span></button>)}</div></Catalog>
    </section>
    <Catalog title="الخدمات والأسعار" action={<Link href="/price-list" className="rounded-xl bg-cyan-600 px-4 py-2 font-bold text-white">إدارة الخدمات والأسعار</Link>}><div className="grid gap-2 md:grid-cols-2">{data.services.map(service=><div key={service.id} className="rounded-xl border p-3"><b>{service.name_ar || service.name}</b><span className="block text-xs text-slate-500">{service.category_ar || service.category || "بدون تصنيف"} · {service.default_price.toLocaleString("en-US")} ر.س · {service.duration_minutes} دقيقة</span></div>)}</div></Catalog>
  </main>;
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <div className="flex items-center gap-3 rounded-2xl border bg-white p-4 shadow-sm"><span className="grid size-11 place-items-center rounded-xl bg-cyan-50 text-cyan-700">{icon}</span><div><span className="text-sm text-slate-500">{label}</span><b className="block text-2xl">{value.toLocaleString("en-US")}</b></div></div>}
function Catalog({title,action,children}:{title:string;action:React.ReactNode;children:React.ReactNode}){return <section className="space-y-4 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl font-black">{title}</h2>{action}</div>{children}</section>}
function BranchForm({draft,setDraft,save}:{draft:Partial<MasterBranch>;setDraft:(x:Partial<MasterBranch>|null)=>void;save:()=>void}){return <div className="grid gap-2 rounded-xl bg-slate-50 p-3 sm:grid-cols-2"><input className={field} value={draft.name||""} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="اسم الفرع"/><input className={field} value={draft.code||""} onChange={e=>setDraft({...draft,code:e.target.value})} placeholder="الرمز"/><input className={field} value={draft.phone||""} onChange={e=>setDraft({...draft,phone:e.target.value})} placeholder="الهاتف"/><input className={field} value={draft.address||""} onChange={e=>setDraft({...draft,address:e.target.value})} placeholder="العنوان"/><label className="flex items-center gap-2"><input type="checkbox" checked={draft.is_active??true} onChange={e=>setDraft({...draft,is_active:e.target.checked})}/>نشط</label><div className="flex gap-2"><button disabled={!draft.name?.trim()} onClick={save} className="flex-1 rounded-xl bg-cyan-600 text-white">حفظ</button><button onClick={()=>setDraft(null)} className="rounded-xl border px-4">إلغاء</button></div></div>}
function RoomForm({draft,branches,setDraft,save}:{draft:Partial<MasterRoom>;branches:MasterBranch[];setDraft:(x:Partial<MasterRoom>|null)=>void;save:()=>void}){return <div className="grid gap-2 rounded-xl bg-slate-50 p-3 sm:grid-cols-2"><input className={field} value={draft.name||""} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="اسم الغرفة"/><select className={field} value={draft.branch_id||""} onChange={e=>setDraft({...draft,branch_id:Number(e.target.value)})}><option value="">حدد الفرع</option>{branches.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input className={field} value={draft.room_type||""} onChange={e=>setDraft({...draft,room_type:e.target.value})} placeholder="نوع الغرفة"/><label className="flex items-center gap-2"><input type="checkbox" checked={draft.is_active??true} onChange={e=>setDraft({...draft,is_active:e.target.checked})}/>نشطة</label><div className="flex gap-2 sm:col-span-2"><button disabled={!draft.name?.trim()||!draft.branch_id} onClick={save} className="flex-1 rounded-xl bg-cyan-600 py-3 text-white">حفظ</button><button onClick={()=>setDraft(null)} className="rounded-xl border px-4">إلغاء</button></div></div>}
