"use client";

import { FormEvent, ReactNode, useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { FileText, Link2, Printer, Workflow } from "lucide-react";
import { toast } from "sonner";
import { useLocale } from "@/components/LocaleProvider";
import { useClinic } from "@/features/clinic/hooks/useClinic";
import { usePermissionAccess } from "@/features/users/hooks/usePermissionAccess";
import { defaultOperationalSettings, getOperationalSettings, saveOperationalSettings, type OperationalSettings } from "../api/operational-settings.api";
import RecurringExpenseSettings from "./RecurringExpenseSettings";
import PrintLayoutFields from "./PrintLayoutFields";

const card="space-y-4 rounded-2xl border bg-white p-5 shadow-sm";
const field="min-h-11 w-full rounded-xl border bg-white px-3 py-2 outline-none focus:border-cyan-500";
export default function OperationalSettingsCenter(){
  const {locale,isArabic,text}=useLocale(); const {clinic}=useClinic(); const access=usePermissionAccess(); const clinicId=clinic?.id??0; const qc=useQueryClient();
  const query=useQuery({queryKey:["operational-settings",clinicId],queryFn:()=>getOperationalSettings(clinicId),enabled:clinicId>0});
  const [draft,setDraft]=useState<OperationalSettings>(()=>defaultOperationalSettings(clinicId));
  useEffect(()=>{
    // The persisted query value becomes the editable draft after load/save.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    if(query.data)setDraft(query.data)
  },[query.data]);
  const canTemplates=access.can("settings.templates.manage","settings.manage"),canIntegrations=access.can("settings.integrations.manage","settings.manage"),canProcesses=access.can("settings.processes.manage","settings.manage"),canPrint=access.can("settings.print.manage","settings.manage");
  const save=useMutation({mutationFn:saveOperationalSettings,onSuccess:async()=>{await qc.invalidateQueries({queryKey:["operational-settings",clinicId]});toast.success(text("Operational settings saved and applied.","تم حفظ إعدادات التشغيل وتطبيقها على النظام."))}});
  async function submit(event:FormEvent){event.preventDefault();await save.mutateAsync(draft)}
  if(!access.isLoading&&!access.can("settings.view","settings.manage","settings.templates.manage","settings.integrations.manage","settings.processes.manage","settings.print.manage"))return <div className="rounded-2xl bg-amber-50 p-6 text-amber-800">{text("Operational settings are unavailable under your permissions.","إعدادات التشغيل غير متاحة لك حسب صلاحياتك.")}</div>;
  const toggle=(english:string,arabic:string,key:keyof OperationalSettings)=><Toggle label={text(english,arabic)} checked={Boolean(draft[key])} onChange={value=>setDraft({...draft,[key]:value})}/>;
  return <form onSubmit={submit} className="space-y-5" dir={isArabic?"rtl":"ltr"}>
    <header><h1 className="text-3xl font-black">{text("Operations, integrations and printing","إعدادات التشغيل والربط والطباعة")}</h1><p className="text-slate-500">{text("Central settings applied to messages, invoices, printing and workflows across the system.","إعدادات مركزية تنعكس على الرسائل والفواتير والطباعة وإجراءات العمل في كل النظام.")}</p></header>
    <div className="grid gap-5 xl:grid-cols-2">
      {canTemplates&&<section className={card}><Title icon={<FileText/>} text={text("Message templates","قوالب الرسائل")}/><label className="text-sm font-bold">{text("Default channel","القناة الافتراضية")}<select className={`${field} mt-1`} value={draft.template_default_channel} onChange={e=>setDraft({...draft,template_default_channel:e.target.value as OperationalSettings["template_default_channel"]})}><option value="email">{text("Email","البريد الإلكتروني")}</option><option value="sms">{text("SMS","الرسائل النصية")}</option><option value="whatsapp">WhatsApp</option></select></label><Template label={text("Appointment confirmation","تأكيد الموعد")} value={draft.appointment_confirmation_template} onChange={value=>setDraft({...draft,appointment_confirmation_template:value})}/><Template label={text("Appointment reminder","تذكير الموعد")} value={draft.appointment_reminder_template} onChange={value=>setDraft({...draft,appointment_reminder_template:value})}/><Template label={text("Appointment cancellation","إلغاء الموعد")} value={draft.appointment_cancelled_template} onChange={value=>setDraft({...draft,appointment_cancelled_template:value})}/><Template label={text("Payment receipt","إيصال الدفع")} value={draft.payment_receipt_template} onChange={value=>setDraft({...draft,payment_receipt_template:value})}/><Template label={text("General follow-up","المتابعة العامة")} value={draft.follow_up_template} onChange={value=>setDraft({...draft,follow_up_template:value})}/><Template label={text("Post-treatment follow-up","المتابعة بعد العلاج")} value={draft.treatment_follow_up_template} onChange={value=>setDraft({...draft,treatment_follow_up_template:value})}/><Template label={text("Birthday greeting","تهنئة عيد الميلاد")} value={draft.birthday_template} onChange={value=>setDraft({...draft,birthday_template:value})}/><p className="text-xs text-slate-500">{text("Variables","المتغيرات")}: {"{{patient}} {{clinic}} {{date}} {{time}} {{amount}} {{invoice}} {{appointment}} {{service}}"}</p></section>}
      {canIntegrations&&<section className={card}><Title icon={<Link2/>} text={text("Communication channels and integrations","قنوات التواصل والتكاملات")}/>{toggle("Email","البريد الإلكتروني","email_enabled")}{toggle("WhatsApp","واتساب","whatsapp_enabled")}{toggle("SMS","الرسائل النصية","sms_enabled")}{toggle("Google Calendar","تقويم Google","google_calendar_enabled")}<div className="grid gap-2 text-xs"><IntegrationState label={text("Email","البريد الإلكتروني")} active={draft.email_enabled} text={text}/><IntegrationState label="WhatsApp" active={draft.whatsapp_enabled} text={text}/><IntegrationState label={text("SMS","الرسائل النصية")} active={draft.sms_enabled} text={text}/><IntegrationState label="Google Calendar" active={draft.google_calendar_enabled} text={text}/></div><p className="rounded-xl bg-amber-50 p-3 text-xs text-amber-800">{text("Enabling an integration allows the system to use it. Secret credentials remain server-side and are never shown to employees.","يتيح التفعيل استخدام التكامل داخل النظام. تبقى بيانات الاعتماد السرية في الخادم ولا تظهر للموظفين.")}</p></section>}
      {canProcesses&&<section className={card}><Title icon={<Workflow/>} text={text("Operational rules","قواعد التشغيل")}/>{toggle("Confirm appointments automatically","تأكيد المواعيد تلقائيًا","auto_confirm_appointments")}{toggle("Create follow-up after treatment","إنشاء متابعة بعد العلاج","auto_create_follow_up")}{toggle("Require patient phone number","رقم الهاتف إلزامي في ملف المريض","require_patient_phone")}{toggle("Require national ID","رقم الهوية إلزامي في ملف المريض","require_national_id")}</section>}
      {canPrint&&<section className={card}><Title icon={<Printer/>} text={text("Invoice printing","طباعة الفواتير")}/><input className={field} value={draft.invoice_header??""} onChange={e=>setDraft({...draft,invoice_header:e.target.value||null})} placeholder={text("Invoice header","عنوان أعلى الفاتورة")}/><input className={field} value={draft.tax_number??""} onChange={e=>setDraft({...draft,tax_number:e.target.value||null})} placeholder={text("Clinic tax number","الرقم الضريبي للعيادة")} dir="ltr"/><textarea className={field} value={draft.invoice_footer??""} onChange={e=>setDraft({...draft,invoice_footer:e.target.value||null})} placeholder={text("Invoice footer","نص أسفل الفاتورة")}/>{toggle("Show QR code","إظهار رمز QR","invoice_show_qr")}{toggle("Show barcode","إظهار الباركود","invoice_show_barcode")}{toggle("Show tax number","إظهار الرقم الضريبي","invoice_show_tax_number")}</section>}
    </div>
    {canProcesses&&<RecurringExpenseSettings/>}{canPrint&&<section className={card}><Title icon={<Printer/>} text={text("Document print layout","تخطيط طباعة كل المستندات")}/><PrintLayoutFields draft={draft} setDraft={setDraft}/></section>}
    {(canTemplates||canIntegrations||canProcesses||canPrint)&&<div className="flex items-center justify-between rounded-2xl border bg-white p-4"><span className="text-xs text-slate-500">{text("Last update","آخر تحديث")}: {draft.updated_at?new Date(draft.updated_at).toLocaleString(locale==="ar"?"ar-SA-u-nu-latn":"en-US"):text("Not saved yet","لم تُحفظ بعد")} {draft.updater?.staff_name?`${text("by","بواسطة")} ${draft.updater.staff_name}`:""}</span><button disabled={save.isPending} className="rounded-xl bg-slate-950 px-6 py-3 font-bold text-white">{save.isPending?text("Saving...","جاري الحفظ..."):text("Save and apply","حفظ وتطبيق")}</button></div>}
  </form>;
}
function Title({icon,text}:{icon:ReactNode;text:string}){return <h2 className="flex items-center gap-2 text-xl font-black text-slate-900">{icon}{text}</h2>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="flex items-center justify-between rounded-xl border p-3"><span className="font-bold">{label}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="size-5 accent-cyan-600"/></label>}
function Template({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label><span className="mb-1 block text-sm font-bold">{label}</span><textarea className={field} value={value} onChange={e=>onChange(e.target.value)} rows={2}/></label>}
function IntegrationState({label,active,text}:{label:string;active:boolean;text:(en:string,ar:string)=>string}){return <div className="flex justify-between rounded-lg bg-slate-50 px-3 py-2"><span>{label}</span><b className={active?"text-emerald-600":"text-slate-400"}>{active?text("Enabled","مفعّل"):text("Disabled","غير مفعّل")}</b></div>}
