"use client";
import { useLocale } from "@/components/LocaleProvider";
import type { OperationalSettings } from "../api/operational-settings.api";
const field="min-h-11 w-full rounded-xl border bg-white px-3 py-2";
export default function PrintLayoutFields({draft,setDraft}:{draft:OperationalSettings;setDraft:(value:OperationalSettings)=>void}){
  const {text}=useLocale();
  const toggle=(english:string,arabic:string,key:keyof OperationalSettings)=><label className="flex items-center justify-between rounded-xl border p-3"><span className="font-bold">{text(english,arabic)}</span><input type="checkbox" checked={Boolean(draft[key])} onChange={e=>setDraft({...draft,[key]:e.target.checked})} className="size-5 accent-cyan-600"/></label>;
  const margins=[[text("Top","علوي"),"print_margin_top_mm"],[text("Bottom","سفلي"),"print_margin_bottom_mm"],[text("Right","يمين"),"print_margin_right_mm"],[text("Left","يسار"),"print_margin_left_mm"]];
  return <div className="space-y-3"><div className="grid grid-cols-2 gap-3"><select className={field} value={draft.print_page_size} onChange={e=>setDraft({...draft,print_page_size:e.target.value})}><option>A4</option><option>A5</option><option>Letter</option></select><select className={field} value={draft.print_orientation} onChange={e=>setDraft({...draft,print_orientation:e.target.value})}><option value="portrait">{text("Portrait","طولي")}</option><option value="landscape">{text("Landscape","عرضي")}</option></select><select className={field} value={draft.print_date_format} onChange={e=>setDraft({...draft,print_date_format:e.target.value})}><option value="dd/MM/yyyy">DD/MM/YYYY</option><option value="yyyy-MM-dd">YYYY-MM-DD</option></select><select className={field} value={draft.print_font_family} onChange={e=>setDraft({...draft,print_font_family:e.target.value})}><option>Arial</option><option>Tajawal</option><option>Cairo</option></select></div><div className="grid grid-cols-4 gap-2">{margins.map(([label,key])=><label key={key} className="text-xs">{label} (mm)<input type="number" min="0" className={field} value={Number(draft[key as keyof OperationalSettings]??0)} onChange={e=>setDraft({...draft,[key]:Number(e.target.value)})}/></label>)}</div>{toggle("Show logo","إظهار الشعار","print_show_logo")}{toggle("Grayscale","ألوان أبيض وأسود","print_grayscale")}{toggle("Hide patient file number","إخفاء رقم ملف المريض","print_hide_patient_code")}{toggle("Hide national ID","إخفاء رقم الهوية","print_hide_national_id")}{toggle("Show doctor name","إظهار اسم الطبيب","print_show_doctor")}{toggle("Show patient name","إظهار اسم المريض","print_show_patient")}{toggle("Show date","إظهار التاريخ","print_show_date")}<input className={field} value={draft.print_watermark??""} onChange={e=>setDraft({...draft,print_watermark:e.target.value||null})} placeholder={text("Optional watermark","علامة مائية اختيارية")}/></div>;
}
