"use client";
import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarClock, Plus, RefreshCcw } from "lucide-react";
import { toast } from "sonner";
import { useLocale } from "@/components/LocaleProvider";
import { createClient } from "@/lib/supabase/client";
import { useClinic } from "@/features/clinic/hooks/useClinic";
import { usePermissionAccess } from "@/features/users/hooks/usePermissionAccess";
const client=createClient(),field="h-11 rounded-xl border px-3 text-sm";
type Row={id:number;name:string;amount:number;due_day:number;account_key:string;supplier_name:string|null;last_generated_month:string|null};
export default function RecurringExpenseSettings(){
  const {isArabic,text}=useLocale(),{clinic,selectedBranch}=useClinic(),access=usePermissionAccess(),clinicId=clinic?.id??0,branchId=selectedBranch?.id??0,qc=useQueryClient(),canManage=access.can("settings.recurring_expenses.manage","settings.manage","accounting.manage");
  const query=useQuery({queryKey:["recurring-expenses",clinicId,branchId],enabled:clinicId>0&&branchId>0,queryFn:async()=>{const{data,error}=await client.from("clinic_recurring_expenses").select("*").eq("clinic_id",clinicId).eq("branch_id",branchId).order("due_day");if(error)throw new Error(error.message);return(data??[])as Row[]}});
  const[show,setShow]=useState(false),[form,setForm]=useState({name:"",amount:"",due_day:"1",account_key:"other_expense",supplier_name:""});
  const refresh=()=>{void qc.invalidateQueries({queryKey:["recurring-expenses"]});void qc.invalidateQueries({queryKey:["clinic-expenses"]})};
  const add=useMutation({mutationFn:async()=>{const{error}=await client.from("clinic_recurring_expenses").insert({clinic_id:clinicId,branch_id:branchId,name:form.name,amount:Number(form.amount),due_day:Number(form.due_day),account_key:form.account_key,supplier_name:form.supplier_name||null});if(error)throw new Error(error.message)},onSuccess:refresh});
  const generate=useMutation({mutationFn:async()=>{const{data,error}=await client.rpc("generate_recurring_expenses",{p_branch_id:branchId,p_month:new Date().toISOString().slice(0,10)});if(error)throw new Error(error.message);return Number(data??0)},onSuccess:n=>{refresh();toast.success(text(`${n} monthly expenses generated.`,`تم إنشاء ${n} مصروف شهري.`))}});
  async function submit(e:FormEvent){e.preventDefault();await add.mutateAsync();setShow(false);setForm({...form,name:"",amount:""});toast.success(text("Monthly expense saved.","تم حفظ المصروف الشهري."))}
  if(!access.can("settings.recurring_expenses.view","settings.recurring_expenses.manage","settings.manage","accounting.manage"))return null;
  const accounts=[{"key":"salaries","en":"Salaries","ar":"الرواتب"},{"key":"rent","en":"Rent","ar":"الإيجار"},{"key":"utilities","en":"Utilities","ar":"المرافق"},{"key":"marketing","en":"Marketing","ar":"التسويق"},{"key":"administrative","en":"Administrative expenses","ar":"مصروفات إدارية"},{"key":"other_expense","en":"Other expenses","ar":"مصروفات أخرى"}];
  return <section className="space-y-4 rounded-2xl border bg-white p-5" dir={isArabic?"rtl":"ltr"}><div className="flex flex-wrap justify-between gap-2"><div><h2 className="flex items-center gap-2 text-xl font-black"><CalendarClock/>{text("Monthly expenses","المصروفات الشهرية")}</h2><p className="text-sm text-slate-500">{text("Generate rent, salaries and subscriptions automatically in the expense center.","أنشئ الإيجار والرواتب والاشتراكات تلقائيًا داخل مركز المصروفات.")}</p></div>{canManage&&<div className="flex gap-2"><button type="button" onClick={()=>generate.mutate()} className="rounded-xl border px-4 py-2 font-bold"><RefreshCcw className="me-2 inline size-4"/>{text("Generate this month","إنشاء مصروفات الشهر")}</button><button type="button" onClick={()=>setShow(v=>!v)} className="rounded-xl bg-slate-950 px-4 py-2 font-bold text-white"><Plus className="me-2 inline size-4"/>{text("Monthly item","بند شهري")}</button></div>}</div>
  {show&&<form onSubmit={submit} className="grid gap-3 rounded-xl bg-slate-50 p-4 md:grid-cols-5"><input required className={field} placeholder={text("Expense name","اسم المصروف")} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required min="0.01" step="0.01" type="number" className={field} placeholder={text("Amount","المبلغ")} value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><input required min="1" max="28" type="number" className={field} placeholder={text("Due day","يوم الاستحقاق")} value={form.due_day} onChange={e=>setForm({...form,due_day:e.target.value})}/><select className={field} value={form.account_key} onChange={e=>setForm({...form,account_key:e.target.value})}>{accounts.map(x=><option key={x.key} value={x.key}>{text(x.en,x.ar)}</option>)}</select><input className={field} placeholder={text("Supplier","المورد")} value={form.supplier_name} onChange={e=>setForm({...form,supplier_name:e.target.value})}/><button className="rounded-xl bg-cyan-600 py-3 font-bold text-white md:col-span-5">{text("Save monthly item","حفظ البند الشهري")}</button></form>}
  <div className="overflow-auto"><table className="w-full min-w-[700px] text-sm"><thead><tr>{[text("Name","الاسم"),text("Amount","المبلغ"),text("Due day","يوم الاستحقاق"),text("Account","الحساب"),text("Supplier","المورد"),text("Last generated month","آخر شهر تم إنشاؤه")].map(x=><th key={x} className="border-b p-3 text-start">{x}</th>)}</tr></thead><tbody>{query.data?.map(x=><tr key={x.id}><td className="border-b p-3 font-bold">{x.name}</td><td className="border-b p-3" dir="ltr">SAR {Number(x.amount).toLocaleString("en-US")}</td><td className="border-b p-3">{x.due_day}</td><td className="border-b p-3">{accounts.find(a=>a.key===x.account_key)?text(accounts.find(a=>a.key===x.account_key)!.en,accounts.find(a=>a.key===x.account_key)!.ar):x.account_key}</td><td className="border-b p-3">{x.supplier_name||"—"}</td><td className="border-b p-3">{x.last_generated_month||text("Not generated yet","لم يُنشأ بعد")}</td></tr>)}</tbody></table></div></section>;
}
