"use client";
/* The current timestamp is a deliberate snapshot for the live-presence calculation. */
/* eslint-disable react-hooks/purity */
import {Activity,Clock3,RefreshCw,Smartphone,UserCheck,UsersRound} from "lucide-react";
import {Button} from "@/components/ui/button";
import {useLocale} from "@/components/LocaleProvider";
import {useClinic} from "@/features/clinic/hooks/useClinic";
import {usePermission} from "@/features/users/hooks/usePermission";
import {usePatientAppAnalytics} from "../hooks/usePatientAppAnalytics";

function date(value:string,arabic:boolean){return new Intl.DateTimeFormat(arabic?"ar-SA-u-nu-latn":"en-GB",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Riyadh"}).format(new Date(value));}
export default function PatientAppAnalytics(){const{isArabic,text}=useLocale();const{clinic,selectedBranch,isLoading:clinicLoading}=useClinic();const q=usePatientAppAnalytics(clinic?.id??0,selectedBranch?.id??0);const identity=usePermission("patient_app.identity.view");if(clinicLoading||q.isLoading)return <div className="rounded-3xl border bg-white p-12 text-center">{text("Loading app activity...","جارٍ تحميل نشاط التطبيق...")}</div>;if(q.error||!q.data)return <div className="rounded-3xl border border-red-200 bg-red-50 p-6 text-red-700">{text("App analytics could not be loaded. Apply the latest database update first.","تعذر تحميل تحليلات التطبيق. طبّق آخر تحديث لقاعدة البيانات أولًا.")}</div>;
const now=Date.now(),active=q.data.presence.filter(item=>item.app_state==="active"&&now-new Date(item.last_seen_at).getTime()<=90000),today=q.data.sessions.filter(item=>now-new Date(item.opened_at).getTime()<=86400000),uniqueToday=new Set(today.map(item=>item.customer_id)).size,totalOpens=q.data.presence.reduce((sum,item)=>sum+item.total_opens,0);
return <div className="space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold text-cyan-700">{text("PATIENT APP","تطبيق المرضى")}</p><h1 className="mt-1 text-3xl font-black">{text("Live app usage","استخدام التطبيق لحظيًا")}</h1><p className="mt-2 text-slate-500">{text("Active now means the app sent a heartbeat during the last 90 seconds.","النشط الآن يعني أن التطبيق أرسل نبضًا خلال آخر 90 ثانية.")}</p></div><Button variant="outline" onClick={()=>void q.refetch()} disabled={q.isFetching}><RefreshCw className={q.isFetching?"animate-spin":""}/>{text("Refresh","تحديث")}</Button></header>
<section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card icon={Activity} label={text("Active now","نشط الآن")} value={active.length} tone="green"/><Card icon={UserCheck} label={text("Used today","استخدموا اليوم")} value={uniqueToday}/><Card icon={UsersRound} label={text("Registered patients","مرضى مسجلون")} value={q.data.registeredPatients}/><Card icon={Smartphone} label={text("Total app opens","إجمالي مرات الفتح")} value={totalOpens}/></section>
<section className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="text-xl font-black">{text("Patient activity details","تفاصيل نشاط المرضى")}</h2><p className="mt-1 text-sm text-slate-500">{text("Device, version, last activity and open count.","الجهاز والإصدار وآخر نشاط وعدد مرات الفتح.")}</p></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-4 text-start">{text("Patient","المريض")}</th><th className="p-4 text-start">{text("Status","الحالة")}</th><th className="p-4 text-start">{text("Device","الجهاز")}</th><th className="p-4 text-start">{text("Last activity","آخر نشاط")}</th><th className="p-4 text-start">{text("Opens","مرات الفتح")}</th></tr></thead><tbody className="divide-y">{q.data.presence.map(item=>{const live=item.app_state==="active"&&now-new Date(item.last_seen_at).getTime()<=90000;const name=identity.allowed?`${item.customers?.first_name??""} ${item.customers?.last_name??""}`.trim():text("Hidden patient","مريض مخفي");return <tr key={item.id}><td className="p-4"><p className="font-bold">{name||text("Unnamed patient","مريض بدون اسم")}</p>{identity.allowed&&<p className="text-xs text-slate-500" dir="ltr">{item.customers?.phone||item.customers?.email||item.customers?.customer_code||"—"}</p>}</td><td className="p-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${live?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{live?text("Active now","نشط الآن"):text("Offline","غير متصل")}</span></td><td className="p-4"><p className="font-semibold">{item.platform||"—"}</p><p className="text-xs text-slate-500">{item.app_version?`${text("Version","الإصدار")} ${item.app_version}`:"—"}</p></td><td className="p-4"><span className="flex items-center gap-2"><Clock3 className="size-4 text-slate-400"/>{date(item.last_seen_at,isArabic)}</span></td><td className="p-4 font-black">{item.total_opens}</td></tr>})}</tbody></table></div>{!q.data.presence.length&&<div className="p-12 text-center text-slate-500">{text("No app activity has been recorded yet. It will appear after patients install the updated app.","لم يُسجل نشاط بعد. سيظهر هنا بعد تثبيت المرضى لنسخة التطبيق المحدثة.")}</div>}</section></div>}
function Card({icon:Icon,label,value,tone="slate"}:{icon:typeof Activity;label:string;value:number;tone?:"slate"|"green"}){return <article className={`rounded-3xl p-5 ${tone==="green"?"bg-emerald-600 text-white":"border bg-white"}`}><Icon className="size-6"/><p className="mt-4 text-sm opacity-70">{label}</p><strong className="text-3xl">{value}</strong></article>}
