import{createClient}from"@/lib/supabase/client";import type{AgentAnswer,AgentContext,AgentKind,AgentTask,AgentWorkspace}from"../types/agents";const supabase=createClient();
export async function getAgentWorkspace(clinicId:number,branchId:number,includeFinance=false):Promise<AgentWorkspace>{const now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()),tomorrow=new Date(today);tomorrow.setDate(tomorrow.getDate()+1);const month=new Date(now.getFullYear(),now.getMonth(),1);
 const[a,c,f,p,tr,t,ca,l,i,at]=await Promise.all([
  supabase.from("appointments").select("id,status,appointment_at,customer_id,service_id,customers(first_name,last_name,phone),services(name)").eq("clinic_id",clinicId).eq("branch_id",branchId).gte("appointment_at",today.toISOString()).lt("appointment_at",tomorrow.toISOString()),
  supabase.from("customers").select("id",{count:"exact",head:true}).eq("clinic_id",clinicId).eq("branch_id",branchId).neq("status","inactive"),
  supabase.from("follow_ups").select("id,status,scheduled_at,customer_id,customers(first_name,last_name,phone)").eq("clinic_id",clinicId).eq("branch_id",branchId).not("status","in",'("completed","cancelled")'),
  includeFinance?supabase.from("payments").select("amount,payment_status,payment_date,customer_id,customers(first_name,last_name,phone)").eq("clinic_id",clinicId).eq("branch_id",branchId):Promise.resolve({data:[],error:null}),
  supabase.from("treatments").select("price,discount,final_price,status").eq("clinic_id",clinicId).eq("branch_id",branchId),
  supabase.from("treatment_sessions").select("id,status,treatment_items(service_id,services(name))").eq("clinic_id",clinicId).eq("branch_id",branchId).gte("session_date",month.toISOString()),
  supabase.from("marketing_campaigns").select("id,status,channel").eq("clinic_id",clinicId).eq("branch_id",branchId),
  supabase.from("marketing_leads").select("id,status,source").eq("clinic_id",clinicId).eq("branch_id",branchId).gte("created_at",month.toISOString()),
  supabase.from("inventory_products").select("id,name,current_stock,minimum_stock").eq("clinic_id",clinicId).eq("branch_id",branchId).eq("is_active",true),
  supabase.from("hr_attendance").select("id,status").eq("clinic_id",clinicId).eq("branch_id",branchId).eq("work_date",today.toISOString().slice(0,10))]);
 const suggestions=await supabase.from("patient_automation_suggestions").select("id,title,suggested_action,priority",{count:"exact"}).eq("clinic_id",clinicId).eq("branch_id",branchId).eq("status","open").order("created_at",{ascending:true}).limit(20);
 const error=a.error||c.error||f.error||p.error||tr.error||t.error||ca.error||l.error||i.error||at.error||suggestions.error;if(error)throw new Error(error.message);
 const payments=(p.data??[]).filter(x=>!['cancelled','refunded'].includes(x.payment_status??'')),revenueMonth=payments.filter(x=>x.payment_date&&new Date(x.payment_date)>=month).reduce((s,x)=>s+Number(x.amount??0),0),collected=payments.reduce((s,x)=>s+Number(x.amount??0),0),treatmentValue=(tr.data??[]).filter(x=>x.status!=="cancelled").reduce((s,x)=>s+Number(x.final_price??Math.max(Number(x.price??0)-Number(x.discount??0),0)),0);
 const serviceMap=new Map<string,number>();for(const session of t.data??[])for(const item of session.treatment_items??[]){const rel=Array.isArray(item.services)?item.services[0]:item.services;const name=rel?.name||"Unspecified";serviceMap.set(name,(serviceMap.get(name)??0)+1);}
 const sourceMap=new Map<string,number>();for(const lead of l.data??[]){const name=lead.source||"Unknown";sourceMap.set(name,(sourceMap.get(name)??0)+1);}
 const context:AgentContext={appointmentsToday:(a.data??[]).length,pendingConfirmations:(a.data??[]).filter(x=>x.status==="booked").length,pendingFollowUps:(f.data??[]).length,completedTreatments:(t.data??[]).filter(x=>x.status==="completed").length,activeCustomers:c.count??0,revenueMonth,outstanding:Math.max(treatmentValue-collected,0),activeCampaigns:(ca.data??[]).filter(x=>x.status==="active").length,marketingLeads:(l.data??[]).length,lowStockProducts:(i.data??[]).filter(x=>Number(x.current_stock)<=Number(x.minimum_stock)).length,staffPresentToday:(at.data??[]).filter(x=>["present","late"].includes(x.status)).length,topServices:[...serviceMap].map(([name,count])=>({name,count})).sort((x,y)=>y.count-x.count).slice(0,5),topSources:[...sourceMap].map(([name,count])=>({name,count})).sort((x,y)=>y.count-x.count).slice(0,5)};
 const task=(id:string,title:string,detail:string,href:string,priority:AgentTask["priority"]):AgentTask=>({id,title,detail,href,priority});
 const automated=(suggestions.data??[]).slice(0,5).map(x=>task(`patient-${x.id}`,x.title,x.suggested_action,"/appointments",x.priority==="urgent"||x.priority==="high"?"high":x.priority==="low"?"low":"medium"));
 const tasks:Record<AgentKind,AgentTask[]>={reception:[...automated,task("confirm","تأكيد حجوزات اليوم",`${context.pendingConfirmations} موعد يحتاج إلى تأكيد.`,"/appointments","high"),task("follow","إكمال المتابعات",`${context.pendingFollowUps} متابعة مفتوحة.`,"/follow-ups","medium")],doctor:[task("sessions","مراجعة جلسات العلاج",`${context.completedTreatments} جلسة مكتملة هذا الشهر.`,"/treatments","medium"),task("stock","فحص المواد السريرية",`${context.lowStockProducts} صنف عند أو تحت حد إعادة الطلب.`,"/inventory",context.lowStockProducts?"high":"low")],marketing:[task("leads","متابعة العملاء المحتملين",`${context.marketingLeads} عميل محتمل مسجل هذا الشهر.`,"/marketing#leads","high"),task("campaigns","مراجعة الحملات",`${context.activeCampaigns} حملة نشطة.`,"/marketing#campaigns","medium")],finance:[task("payments","مراجعة التحصيل",`${context.revenueMonth.toLocaleString("en-US")} ر.س مسجلة هذا الشهر.`,"/payments","high"),task("reports","فتح التحليلات المالية","راجع اتجاهات التحصيل والاسترداد.","/reports#finance","medium")],ceo:[task("today","حالة العيادة اليوم",`${context.appointmentsToday} موعد و${context.staffPresentToday} موظفًا حاضرًا.`,"/dashboard","high"),task("performance","مراجعة الأداء","افتح تحليلات الإيراد والأطباء والتسويق والحجوزات.","/reports","medium")]};return{context,tasks};}
export async function askAgent(agent:AgentKind,question:string,context:AgentContext):Promise<AgentAnswer>{const response=await fetch("/api/ai/agents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({agent,question,context})});const body=await response.json();if(!response.ok)throw new Error(body.error||"AI agent is unavailable");return body;}
