"use client";
import Link from"next/link";
import{CalendarClock,FileHeart,FileText,ReceiptText,Stethoscope,UserRound}from"lucide-react";
import{toast}from"sonner";
import{Dialog,DialogContent,DialogHeader,DialogTitle}from"@/components/ui/dialog";
import{useLocale}from"@/components/LocaleProvider";
import{useUpdateAppointment}from"@/features/appointments/hooks/useUpdateAppointment";
import type{Appointment,AppointmentStatus}from"@/features/appointments/types/appointment";
import type{Payment}from"@/features/payments/types/payment";
import InvoiceDialog from"@/features/payments/components/InvoiceDialog";
import AddPaymentDialog from"@/features/payments/components/AddPaymentDialog";

const statuses:AppointmentStatus[]=["booked","confirmed","arrived","completed","cancelled","no_show"];
export default function AppointmentCustomerWorkspace({appointment,payments,open,onOpenChange,canManage}:{appointment:Appointment|null;payments:Payment[];open:boolean;onOpenChange:(v:boolean)=>void;canManage:boolean}){
 const{isArabic,text}=useLocale(),update=useUpdateAppointment();if(!appointment)return null;const c=appointment.customers,date=new Date(appointment.appointment_at),customerPayments=payments.filter(p=>p.customer_id===appointment.customer_id);const label=(s:AppointmentStatus)=>({booked:text("Booked","محجوز"),confirmed:text("Confirmed","مؤكد"),arrived:text("Arrived","تم تسجيل الوصول"),completed:text("Completed","مكتمل"),cancelled:text("Cancelled","تم الإلغاء"),no_show:text("No show","لم يحضر")})[s];
 const cell=(title:string,value:React.ReactNode)=><div className="grid min-h-11 grid-cols-[96px_1fr] border-b sm:grid-cols-[112px_1fr]"><b className="bg-fuchsia-700 p-2 text-xs text-white">{title}</b><span className="p-2 text-xs font-semibold">{value||"—"}</span></div>;
 const action="rounded-lg bg-sky-600 px-2.5 py-1.5 text-xs font-bold text-white";
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[82vh] overflow-y-auto p-0 sm:max-w-3xl" dir={isArabic?"rtl":"ltr"}><DialogHeader className="bg-fuchsia-700 p-3 text-white"><DialogTitle className="flex items-center gap-2 text-lg"><UserRound className="size-5"/>{`${c?.first_name??""} ${c?.last_name??""}`.trim()||text("Patient","المريض")}</DialogTitle></DialogHeader><div className="flex flex-wrap gap-1.5 border-b bg-slate-50 p-2"><Link className={action} href={`/customers/${appointment.customer_id}`}><FileHeart className="me-1 inline size-3.5"/>{text("Patient file","ملف المريض")}</Link><Link className={action} href="/treatments"><Stethoscope className="me-1 inline size-3.5"/>{text("Treatments","العلاجات")}</Link><Link className={action} href="/payments"><ReceiptText className="me-1 inline size-3.5"/>{text("Payments","المدفوعات")}</Link><Link className={action} href="/appointments"><CalendarClock className="me-1 inline size-3.5"/>{text("Edit appointment","تعديل الموعد")}</Link></div>
 <div className="grid border-fuchsia-200 md:grid-cols-2"><div>{cell(text("Name","الاسم"),`${c?.first_name??""} ${c?.last_name??""}`.trim())}{cell(text("Phone","رقم الهاتف"),<span dir="ltr">{c?.phone}</span>)}{cell(text("Email","البريد الإلكتروني"),c?.email)}{cell(text("National ID","رقم الهوية"),c?.national_id)}{cell(text("File number","رقم الملف"),c?.customer_code)}</div><div>{cell(text("Doctor","الطبيبة / الطبيب"),appointment.staff?.staff_name)}{cell(text("Service","الخدمة"),appointment.services?.name)}{cell(text("Room","الغرفة"),appointment.rooms?.name)}{cell(text("Date and time","اليوم والوقت"),date.toLocaleString(isArabic?"ar-SA":"en-US",{dateStyle:"medium",timeStyle:"short"}))}{cell(text("Source","مصدر الحجز"),appointment.source)}</div></div>
 <div className="grid md:grid-cols-3">{cell(text("Gender","الجنس"),c?.gender)}{cell(text("Birth date","تاريخ الميلاد"),c?.date_of_birth)}{cell(text("Notes","التفاصيل"),appointment.notes)}</div>
 <div className="border-t p-3"><h3 className="mb-2 text-sm font-black">{text("Appointment status","حالة الموعد")}</h3><div className="flex flex-wrap gap-1.5">{statuses.map(s=><button key={s} disabled={!canManage||update.isPending} onClick={async()=>{try{await update.mutateAsync({id:appointment.id,status:s});toast.success(text("Status updated","تم تحديث الحالة"))}catch(e){toast.error(e instanceof Error?e.message:String(e))}}} className={`rounded-lg px-2.5 py-1.5 text-xs font-black ${appointment.status===s?"bg-fuchsia-700 text-white":"border bg-white"} disabled:opacity-50`}>{label(s)}</button>)}</div></div>
 <div className="border-t p-3"><div className="mb-2 flex flex-wrap items-center justify-between gap-2"><h3 className="flex items-center gap-2 text-sm font-black"><FileText className="size-4"/>{text("Invoices and payments","الفواتير والمدفوعات")}</h3><AddPaymentDialog clinicId={appointment.clinic_id} branchId={appointment.branch_id} initialCustomerId={appointment.customer_id} initialAppointmentId={appointment.id} triggerLabelEn="Issue invoice" triggerLabelAr="إصدار فاتورة"/></div>{customerPayments.length?<div className="grid gap-1.5">{customerPayments.map(p=><div key={p.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border p-2 text-xs"><div><b>{p.invoice_number||`ZRN-${p.id}`}</b><p className="text-slate-500">{p.payment_date?new Date(p.payment_date).toLocaleString(isArabic?"ar-SA":"en-US"):"—"} · {p.payment_method}</p></div><div className="flex items-center gap-2"><b>{new Intl.NumberFormat(isArabic?"ar-SA":"en-SA",{style:"currency",currency:p.currency||"SAR"}).format(Number(p.amount))}</b><InvoiceDialog payment={p}/></div></div>)}</div>:<p className="rounded-lg bg-slate-50 p-3 text-center text-xs text-slate-500">{text("No invoices for this patient yet","لا توجد فواتير لهذا المريض حتى الآن")}</p>}</div></DialogContent></Dialog>;
}
