"use client";
import {useMemo,useState} from "react";
import {Activity,BrainCircuit,CalendarClock,Camera,FileHeart,History,ReceiptText,ShieldPlus,Stethoscope,UserRound} from "lucide-react";
import {toast} from "sonner";
import {useQuery} from "@tanstack/react-query";
import {Dialog,DialogContent,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {useLocale} from "@/components/LocaleProvider";
import {useUpdateAppointment} from "@/features/appointments/hooks/useUpdateAppointment";
import {appointmentStatuses,appointmentStatusLabelAr,appointmentStatusLabelEn,appointmentStatusSolid} from "@/features/appointments/appointment-status";
import type{Appointment,AppointmentStatus}from "@/features/appointments/types/appointment";
import type{Payment}from "@/features/payments/types/payment";
import type{Customer}from "@/features/customers/types/customer";
import InvoiceDialog from "@/features/payments/components/InvoiceDialog";
import AddPaymentDialog from "@/features/payments/components/AddPaymentDialog";
import {getReferralSources} from "@/features/customers/api/customer.api";
import {PatientCatalogBadge} from "@/features/customers/components/PatientCatalogBadge";
import PatientReceiptGallery from "@/features/customers/components/PatientReceiptGallery";
import {customerFileNumber} from "@/features/customers/utils/customerIdentity";
import SaudiMoney from "@/components/SaudiMoney";

type View="file"|"intelligence"|"medical"|"timeline"|"activity"|"gallery"|"treatments"|"payments"|"appointment";
type Props={appointment:Appointment|null;payments:Payment[];customer?:Customer;open:boolean;onOpenChange:(value:boolean)=>void;canManage:boolean};

export default function AppointmentCustomerWorkspace({appointment,payments,customer,open,onOpenChange,canManage}:Props){
 const{isArabic,text}=useLocale(),update=useUpdateAppointment();
 const[view,setView]=useState<View>("file");
 const referrals=useQuery({queryKey:["referral-sources",appointment?.clinic_id],queryFn:()=>getReferralSources(appointment?.clinic_id??0),enabled:!!appointment?.clinic_id});
 const appointmentCustomerId=appointment?.customer_id;
 const customerPayments=useMemo(()=>appointmentCustomerId?payments.filter(payment=>payment.customer_id===appointmentCustomerId):[],[appointmentCustomerId,payments]);
 if(!appointment)return null;
 const c=customer??appointment.customers,date=new Date(appointment.appointment_at),name=`${c?.first_name??""} ${c?.last_name??""}`.trim()||text("Patient","المريض");
 const cell=(title:string,value:React.ReactNode)=><div className="m-1 grid min-h-11 grid-cols-[104px_1fr] overflow-hidden rounded-xl border border-[#516e84]/25 bg-white/90 shadow-sm sm:grid-cols-[122px_1fr]"><b className="bg-gradient-to-br from-[#516e84] via-[#68879b] to-[#385a70] p-2.5 text-xs text-white">{title}</b><span className="p-2.5 text-xs font-bold text-[#233b4d]">{value||"—"}</span></div>;
 const action=(id:View,Icon:typeof FileHeart,label:string)=><button type="button" onClick={()=>setView(id)} className={`rounded-xl px-3 py-2 text-xs font-bold transition ${view===id?"bg-gradient-to-r from-cyan-500 to-blue-600 text-white shadow-lg shadow-cyan-500/20":"border border-slate-200 bg-white/80 text-slate-700 hover:border-cyan-300 hover:bg-cyan-50"}`}><Icon className="me-1 inline size-3.5"/>{label}</button>;
 const profileAction=(id:View,Icon:typeof FileHeart,label:string)=><button type="button" onClick={()=>setView(id)} className={`flex shrink-0 items-center gap-1.5 rounded-xl px-3 py-2 text-xs font-black transition ${view===id?"bg-gradient-to-r from-[#516e84] to-[#385a70] text-white shadow-md":"text-[#3c5568] hover:bg-[#516e84]/10"}`}><Icon className="size-3.5"/>{label}</button>;
 const appointmentId=appointment.id;
 async function setStatus(status:AppointmentStatus){try{await update.mutateAsync({id:appointmentId,status});toast.success(text("Status updated","تم تحديث الحالة"))}catch(error){toast.error(error instanceof Error?error.message:String(error))}}
 const tags=customer?.tags??[],source=appointment.creator?.staff_name?text("Staff booking","حجز بواسطة موظف"):appointment.source;
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[86vh] overflow-y-auto overflow-x-hidden border-[#516e84]/30 bg-gradient-to-br from-white via-[#eef5f7] to-[#dce9ee] p-0 shadow-2xl sm:max-w-[860px]" dir={isArabic?"rtl":"ltr"}>
  <DialogHeader className="relative overflow-hidden bg-gradient-to-r from-[#516e84] via-[#68879b] to-[#385a70] px-5 py-4 text-white"><div className="absolute -end-8 -top-12 size-36 rounded-full bg-white/15 blur-2xl"/><DialogTitle className="relative flex items-center gap-3 text-base"><span className="grid size-9 place-items-center rounded-xl bg-white/15 ring-1 ring-white/20"><UserRound className="size-5"/></span><span><small className="block text-[10px] font-bold text-cyan-100">{text("Patient workspace","مساحة عمل المريض")}</small>{name}</span></DialogTitle></DialogHeader>
  <div className="flex flex-wrap gap-2 border-b border-white/80 bg-white/60 p-3 backdrop-blur-xl">{action("file",FileHeart,text("Patient file","ملف المريض"))}{action("treatments",Stethoscope,text("Treatments","العلاجات"))}{action("payments",ReceiptText,text("Payments","المدفوعات"))}{action("appointment",CalendarClock,text("Edit appointment","تعديل الموعد"))}</div>
  <nav className="flex gap-1 overflow-x-auto border-b border-[#516e84]/15 bg-white/75 p-2">{profileAction("file",FileHeart,text("Overview","نظرة عامة"))}{profileAction("intelligence",BrainCircuit,text("Intelligence & analysis","الذكاء والتحليل"))}{profileAction("medical",ShieldPlus,text("Medical record","السجل الطبي"))}{profileAction("timeline",History,text("Timeline","التسلسل الزمني"))}{profileAction("activity",Activity,text("Activity","النشاط"))}{profileAction("gallery",Camera,text("Patient Gallery","معرض العميل"))}</nav>
  {(tags.length>0||customer?.referral_source)&&<div className="flex flex-wrap items-center gap-1.5 border-b px-3 py-2">{tags.map(tag=><PatientCatalogBadge key={tag.id} name={tag.name} color={tag.color}/>)}{customer?.referral_source&&<PatientCatalogBadge prefix={text("Referral","الإحالة")} name={customer.referral_source} color={referrals.data?.find(item=>item.id===customer.referral_source_id)?.color}/>}</div>}
  {view==="file"&&<><div className="grid p-1 md:grid-cols-2"><div>{cell(text("Name","الاسم"),name)}{cell(text("File number","رقم الملف"),c?customerFileNumber(c):null)}{cell(text("Phone","رقم الهاتف"),<span dir="ltr">{c?.phone}</span>)}{cell(text("Secondary phone","الهاتف الثاني"),<span dir="ltr">{customer?.secondary_phone}</span>)}{cell(text("Email","البريد الإلكتروني"),c?.email)}{cell(text("National ID","رقم الهوية"),c?.national_id)}</div><div>{cell(text("Doctor","الطبيب"),appointment.staff?.staff_name)}{cell(text("Service","الخدمة"),appointment.services?.name)}{cell(text("Room","الغرفة"),appointment.rooms?.name)}{cell(text("Branch","الفرع"),appointment.branches?.name||customer?.branch_name)}{cell(text("Date and time","اليوم والوقت"),date.toLocaleString(isArabic?"ar-SA-u-nu-latn":"en-US",{dateStyle:"medium",timeStyle:"short"}))}{cell(text("Source","مصدر الحجز"),source)}{appointment.creator?.staff_name&&cell(text("Created by","أنشئ بواسطة"),appointment.creator.staff_name)}</div></div><div className="grid p-1 sm:grid-cols-3">{cell(text("Gender","الجنس"),c?.gender)}{cell(text("Nationality","الجنسية"),customer?.nationality)}{cell(text("Birth date","تاريخ الميلاد"),c?.date_of_birth)}{cell(text("Status","الحالة"),customer?.status)}{cell(text("Referral","الإحالة"),customer?.referral_source)}{cell(text("Notes","التفاصيل"),appointment.notes)}</div></>}
  {view==="intelligence"&&<div className="grid gap-2 p-3 sm:grid-cols-2">{cell(text("Total payments","إجمالي المدفوعات"),<SaudiMoney value={customer?.total_paid}/>)}{cell(text("Outstanding","المتبقي"),<SaudiMoney value={customer?.remaining}/>)}{cell(text("Wallet balance","رصيد المحفظة"),<SaudiMoney value={customer?.wallet_balance}/>)}{cell(text("Available points","النقاط المتاحة"),customer?.points_available)}</div>}
  {view==="medical"&&<div className="grid p-3 md:grid-cols-2"><div>{cell(text("Insurance company","شركة التأمين"),customer?.insurance_company)}{cell(text("Policy number","رقم الوثيقة"),customer?.insurance_policy_number)}{cell(text("Policy class","فئة التأمين"),customer?.insurance_policy_class)}{cell(text("Insurance expiry","انتهاء التأمين"),customer?.insurance_expiry)}</div><div>{cell(text("Emergency contact","جهة اتصال الطوارئ"),customer?.emergency_contact_name)}{cell(text("Emergency phone","هاتف الطوارئ"),customer?.emergency_contact_phone)}{cell(text("Occupation","الوظيفة"),customer?.occupation)}{cell(text("Marital status","الحالة الاجتماعية"),customer?.marital_status)}</div></div>}
  {view==="timeline"&&<div className="grid p-3 md:grid-cols-2"><div>{cell(text("Created at","تم الإنشاء"),customer?.created_at&&new Date(customer.created_at).toLocaleString(isArabic?"ar-SA-u-nu-latn":"en-US"))}{cell(text("Selected at","تم التحديد"),customer?.selected_at&&new Date(customer.selected_at).toLocaleString(isArabic?"ar-SA-u-nu-latn":"en-US"))}</div><div>{cell(text("Previous appointment","الموعد السابق"),customer?.previous_appointment_at&&new Date(customer.previous_appointment_at).toLocaleString(isArabic?"ar-SA-u-nu-latn":"en-US"))}{cell(text("Active appointment","الموعد النشط"),customer?.active_appointment_at&&new Date(customer.active_appointment_at).toLocaleString(isArabic?"ar-SA-u-nu-latn":"en-US"))}</div></div>}
  {view==="activity"&&<div className="grid p-3 md:grid-cols-2"><div>{cell(text("Appointment status","حالة الموعد"),isArabic?appointmentStatusLabelAr[appointment.status]:appointmentStatusLabelEn[appointment.status])}{cell(text("Created channel","قناة الإنشاء"),appointment.created_from_channel)}</div><div>{cell(text("Today payments","مدفوعات اليوم"),<SaudiMoney value={customer?.today_paid}/>)}{cell(text("Last payment","آخر دفعة"),customer?.last_payment_at&&new Date(customer.last_payment_at).toLocaleString(isArabic?"ar-SA-u-nu-latn":"en-US"))}</div></div>}
  {view==="gallery"&&customer&&<div className="p-3"><PatientReceiptGallery customerId={customer.id} clinicId={appointment.clinic_id} branchId={appointment.branch_id} payments={customerPayments}/></div>}
  {view==="treatments"&&<div className="p-3"><h3 className="mb-2 font-black">{text("Appointment treatment","علاج الموعد")}</h3><div className="rounded-xl border bg-white/80 p-3"><b>{appointment.services?.name||"—"}</b><p className="mt-1 text-xs text-slate-500">{appointment.staff?.staff_name||"—"} · {appointment.rooms?.name||"—"}</p></div></div>}
  {view==="payments"&&<div className="p-3"><div className="mb-2 flex items-center justify-between"><h3 className="font-black">{text("Invoices and payments","الفواتير والمدفوعات")}</h3><AddPaymentDialog clinicId={appointment.clinic_id} branchId={appointment.branch_id} initialCustomerId={appointment.customer_id} initialAppointmentId={appointment.id} triggerLabelEn="Issue invoice" triggerLabelAr="إصدار فاتورة"/></div>{customerPayments.length?<div className="grid gap-1.5">{customerPayments.map(payment=><div key={payment.id} className="flex items-center justify-between rounded-lg border bg-white/80 p-2 text-xs"><div><b>{payment.invoice_number||`ZRN-${payment.id}`}</b><p className="text-slate-500">{payment.payment_method}</p></div><div className="flex items-center gap-2"><b><SaudiMoney value={payment.amount}/></b><InvoiceDialog payment={payment}/></div></div>)}</div>:<p className="rounded-lg bg-white/70 p-4 text-center text-xs text-slate-500">{text("No invoices yet","لا توجد فواتير حتى الآن")}</p>}</div>}
  {view==="appointment"&&<div className="p-3"><h3 className="mb-2 font-black">{text("Appointment status","حالة الموعد")}</h3><div className="flex flex-wrap gap-1.5">{appointmentStatuses.map(status=><button key={status} disabled={!canManage||update.isPending} onClick={()=>void setStatus(status)} className={`rounded-lg px-2.5 py-1.5 text-xs font-black ${appointmentStatusSolid[status]} ${appointment.status===status?"ring-2 ring-[#385a70] ring-offset-2":"opacity-75"} disabled:opacity-40`}>{isArabic?appointmentStatusLabelAr[status]:appointmentStatusLabelEn[status]}</button>)}</div></div>}
 </DialogContent></Dialog>;
}
