"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { BarChart3, CalendarDays, CircleDollarSign, FileText, RefreshCw, Search } from "lucide-react";
import { useLocale } from "@/components/LocaleProvider";
import { useClinic } from "@/features/clinic/hooks/useClinic";
import { useAppointments } from "@/features/appointments/hooks/useAppointments";
import { useMasterData } from "@/features/appointments/hooks/useMasterData";
import { usePayments } from "@/features/payments/hooks/usePayments";
import type { Appointment, AppointmentStatus } from "@/features/appointments/types/appointment";
import DateRangeFilter from "@/features/date-range/DateRangeFilter";
import { isWithinDateRange } from "@/features/date-range/date-range";
import { useDateRange } from "@/features/date-range/useDateRange";
import { groupServiceFamilies, serviceFamilyLabel } from "@/features/services/service-family";
import { usePermission } from "@/features/users/hooks/usePermission";
import AppointmentCustomerWorkspace from "./AppointmentCustomerWorkspace";
import InvoiceDialog from "@/features/payments/components/InvoiceDialog";
import AddPaymentDialog from "@/features/payments/components/AddPaymentDialog";

const statusColor: Record<AppointmentStatus, string> = { booked: "bg-[#168bd2]", confirmed: "bg-[#204da8]", arrived: "bg-[#17b9a6]", completed: "bg-[#126b36]", cancelled: "bg-[#cf1b79]", no_show: "bg-[#7b160f]" };
const legend: Array<[string, string]> = [["محجوز", "bg-[#168bd2]"], ["مؤكد", "bg-[#204da8]"], ["تم تسجيل الوصول", "bg-[#17b9a6]"], ["جارى العمل", "bg-[#6d258c]"], ["مكتمل", "bg-[#126b36]"], ["متأخر", "bg-[#ef7b13]"], ["تم الألغاء", "bg-[#cf1b79]"], ["لم يتم الحضور", "bg-[#7b160f]"], ["قائمة الإنتظار", "bg-[#adb414]"], ["ملحوظة", "bg-[#888]" ]];

export default function DashboardOverview() {
  const { isArabic } = useLocale(); const { clinic, selectedBranch } = useClinic(); const range = useDateRange(); const clinicId = clinic?.id ?? 0; const branchId = selectedBranch?.id ?? 0;
  const canManage = usePermission("appointments.manage").allowed;
  const [doctorId, setDoctorId] = useState("all"); const [serviceFamily, setServiceFamily] = useState("all"); const [search, setSearch] = useState(""); const [selectedAppointment, setSelectedAppointment] = useState<Appointment | null>(null); const [tab, setTab] = useState<"home" | "payments" | "summary">("home");
  const appointmentsQuery = useAppointments(clinicId, branchId); const paymentsQuery = usePayments(clinicId, branchId); const masterQuery = useMasterData();
  const doctors = useMemo(() => (masterQuery.data?.staff ?? []).filter((x) => x.is_active && x.role?.toLowerCase() === "doctor"), [masterQuery.data]);
  const services = useMemo(() => (masterQuery.data?.services ?? []).filter((x) => x.is_active), [masterQuery.data]); const families = useMemo(() => groupServiceFamilies(services), [services]); const serviceIds = useMemo(() => families.find((x) => x.key === serviceFamily)?.serviceIds ?? [], [families, serviceFamily]);
  const appointments = useMemo(() => (appointmentsQuery.data ?? []).filter((x) => { const patient = `${x.customers?.first_name ?? ""} ${x.customers?.last_name ?? ""} ${x.customers?.phone ?? ""}`.toLowerCase(); return isWithinDateRange(x.appointment_at, range) && (doctorId === "all" || x.doctor_id === Number(doctorId)) && (serviceFamily === "all" || (x.service_id != null && serviceIds.includes(x.service_id))) && (!search.trim() || patient.includes(search.trim().toLowerCase())); }).sort((a, b) => +new Date(a.appointment_at) - +new Date(b.appointment_at)), [appointmentsQuery.data, range, doctorId, serviceFamily, serviceIds, search]);
  const payments = useMemo(() => (paymentsQuery.data ?? []).filter((x) => isWithinDateRange(x.payment_date ?? x.created_at, range) && (doctorId === "all" || x.appointments?.doctor_id === Number(doctorId))), [paymentsQuery.data, range, doctorId]);
  const outstanding = payments.filter((x) => Number(x.balance_due ?? 0) > 0 && !["cancelled", "refunded"].includes(x.payment_status)); const invoiceAppointmentIds = new Set((paymentsQuery.data ?? []).map((x) => x.appointment_id).filter((id): id is number => id != null)); const needsInvoice = appointments.filter((x) => x.status === "completed" && !invoiceAppointmentIds.has(x.id));
  const money = (n: number) => new Intl.NumberFormat("ar-SA", { style: "currency", currency: "SAR", maximumFractionDigits: 2 }).format(n); const serviceName = (id: number | null) => { const s = services.find((x) => x.id === id); return s ? serviceFamilyLabel(s, true) : "خدمة"; }; const busy = appointmentsQuery.isFetching || paymentsQuery.isFetching;
  return <div className="-m-3 min-h-[calc(100vh-60px)] bg-[#eef4f9] text-[12px] md:-m-4" dir={isArabic ? "rtl" : "ltr"}>
    <div className="border-b bg-white px-3"><div className="mx-auto grid max-w-[1800px] grid-cols-3 text-center"><button onClick={() => setTab("home")} className={`border-b-2 py-2 font-bold ${tab === "home" ? "border-[#0879b8] text-[#075985]" : "border-transparent"}`}><CalendarDays className="me-1 inline size-4" />اللوحة الرئيسية</button><button onClick={() => setTab("payments")} className={`border-b-2 py-2 font-bold ${tab === "payments" ? "border-[#0879b8] text-[#075985]" : "border-transparent"}`}><CircleDollarSign className="me-1 inline size-4" />المدفوعات</button><button onClick={() => setTab("summary")} className={`border-b-2 py-2 font-bold ${tab === "summary" ? "border-[#0879b8] text-[#075985]" : "border-transparent"}`}><BarChart3 className="me-1 inline size-4" />ملخص</button></div></div>
    <div className="mx-auto max-w-[1800px] space-y-2 p-2">
      <section className="grid items-end gap-2 md:grid-cols-[2fr_1fr_1fr_auto]"><DateRangeFilter /><label><span className="mb-1 block font-bold">الطبيب المعالج</span><select value={doctorId} onChange={(e) => setDoctorId(e.target.value)} className="h-9 w-full rounded border bg-white px-2"><option value="all">الطبيب المعالج</option>{doctors.map((x) => <option key={x.id} value={x.id}>{x.staff_name}</option>)}</select></label><label><span className="mb-1 block font-bold">مخصصة ل</span><select value={serviceFamily} onChange={(e) => setServiceFamily(e.target.value)} className="h-9 w-full rounded border bg-white px-2"><option value="all">مخصصة ل</option>{families.map((x) => <option key={x.key} value={x.key}>{x.nameAr}</option>)}</select></label><div className="rounded bg-cyan-50 px-4 py-2 text-lg font-black text-[#075985]">{new Intl.DateTimeFormat("ar-SA", { hour: "2-digit", minute: "2-digit", second: "2-digit", timeZone: "Asia/Riyadh" }).format(new Date())}</div></section>
      <label className="flex h-9 items-center gap-2 rounded border bg-white px-3"><Search className="size-4 text-slate-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="البحث عن المرضى" className="w-full outline-none" /></label>
      {tab === "payments" ? <PaymentFeed payments={payments} search={search} busy={busy} onRefresh={() => void paymentsQuery.refetch()} /> : <section className="grid min-h-[650px] gap-2 xl:grid-cols-2">
        <div className="flex min-h-0 flex-col overflow-hidden rounded border bg-white"><header className="border-b p-2"><div className="flex items-center justify-between"><strong className="text-base"><CalendarDays className="me-2 inline size-5 text-[#0b8ecb]" />المواعيد</strong><Link href="/appointments" className="text-[#0879b8]">إظهار الكل</Link></div><div className="mt-2 flex flex-wrap gap-1">{legend.map(([label, color]) => <span key={label} className={`${color} rounded px-2 py-1 text-[10px] font-bold text-white`}>{label}</span>)}</div></header><div className="grid max-h-[610px] gap-1 overflow-y-auto p-2">{appointments.map((x) => { const customer = `${x.customers?.first_name ?? ""} ${x.customers?.last_name ?? ""}`.trim() || "مريض"; const start = new Date(x.appointment_at); const end = new Date(start.getTime() + (x.services?.duration_minutes ?? 30) * 60000); const tf = (d: Date) => new Intl.DateTimeFormat("ar-SA", { hour: "2-digit", minute: "2-digit", hour12: true, timeZone: "Asia/Riyadh" }).format(d); return <button key={x.id} onClick={() => setSelectedAppointment(x)} className={`${statusColor[x.status]} rounded p-3 text-right text-white shadow-sm`}><div className="flex items-start justify-between"><b className="text-sm">{customer}</b><span className="rounded bg-white/90 px-2 py-0.5 text-[10px] font-bold text-slate-800">{serviceName(x.service_id)}</span></div><div className="mt-1 flex flex-wrap items-center justify-between gap-2"><span>{x.staff?.staff_name ?? "—"}</span><b>{tf(start)} - {tf(end)}</b></div>{x.notes && <p className="mt-1 truncate rounded bg-black/15 px-2 py-1">{x.notes}</p>}</button>; })}{!appointments.length && <p className="py-20 text-center text-slate-400">لا توجد بيانات</p>}</div><button onClick={() => void appointmentsQuery.refetch()} className="m-2 ms-auto grid size-9 place-items-center rounded bg-[#0879b8] text-white"><RefreshCw className={`size-4 ${busy ? "animate-spin" : ""}`} /></button></div>
        <div className="flex min-h-0 flex-col overflow-hidden rounded border bg-white"><header className="flex items-center justify-between border-b p-2"><strong className="text-base"><FileText className="me-2 inline size-5 text-[#0879b8]" />الفواتير</strong><Link href="/payments" className="text-[#0879b8]">إظهار الكل</Link></header><label className="border-b p-2"><input type="checkbox" defaultChecked className="me-2" />مطلوب للدفع فقط</label><div className="grid max-h-[610px] gap-2 overflow-y-auto p-2">{needsInvoice.map((x) => <article key={`new-${x.id}`} className="rounded border border-amber-200 bg-amber-50 p-3"><div className="flex justify-between"><b>{`${x.customers?.first_name ?? ""} ${x.customers?.last_name ?? ""}`.trim()}</b><span className="rounded bg-amber-200 px-2 py-1 text-[10px] font-bold">مطلوب فاتورة</span></div><p className="my-2 text-amber-900">{serviceName(x.service_id)} · {x.staff?.staff_name}</p><div className="[&_button]:w-full [&_button]:bg-[#bd5100] [&_button]:text-white"><AddPaymentDialog clinicId={clinicId} branchId={branchId} initialCustomerId={x.customer_id} initialAppointmentId={x.id} triggerLabelEn="Issue invoice" triggerLabelAr="إصدار الفاتورة" /></div></article>)}{outstanding.map((p) => <article key={p.id} className="rounded border border-rose-200 bg-rose-50 p-3"><div className="flex justify-between"><b>{`${p.customers?.first_name ?? ""} ${p.customers?.last_name ?? ""}`.trim()}</b><b className="text-rose-700">{money(Number(p.balance_due))}</b></div><p className="my-2 text-slate-500">{p.invoice_number || `ZRN-${p.id}`} · {p.appointments?.staff?.staff_name || "—"}</p><InvoiceDialog payment={p} /></article>)}{!needsInvoice.length && !outstanding.length && <p className="py-20 text-center text-slate-400">لا توجد بيانات</p>}</div><button onClick={() => void paymentsQuery.refetch()} className="m-2 ms-auto grid size-9 place-items-center rounded bg-[#0879b8] text-white"><RefreshCw className={`size-4 ${busy ? "animate-spin" : ""}`} /></button></div>
      </section>}
    </div><AppointmentCustomerWorkspace appointment={selectedAppointment} payments={paymentsQuery.data ?? []} open={!!selectedAppointment} onOpenChange={(value) => { if (!value) setSelectedAppointment(null); }} canManage={canManage} />
  </div>;
}

function PaymentFeed({ payments, search, busy, onRefresh }: { payments: ReturnType<typeof usePayments>["data"] extends infer T ? NonNullable<T> : never; search: string; busy: boolean; onRefresh: () => void }) {
  const query = search.trim().toLowerCase();
  const rows = (payments ?? []).filter((payment) => !query || `${payment.customers?.first_name ?? ""} ${payment.customers?.last_name ?? ""} ${payment.customers?.phone ?? ""} ${payment.customers?.customer_code ?? ""} ${payment.invoice_number ?? ""}`.toLowerCase().includes(query)).sort((a, b) => +new Date(b.payment_date ?? b.created_at) - +new Date(a.payment_date ?? a.created_at));
  const methodLabel = (method: string) => ({ cash: "نقدي", card: "بطاقة بنكية - مدى", bank_transfer: "تحويل بنكي", split: "دفع مختلط", tabby: "تابي", tamara: "تمارا", other: "أخرى" })[method] ?? method;
  const relative = (value: string | null) => value ? new Intl.DateTimeFormat("ar-SA", { dateStyle: "short", timeStyle: "short", timeZone: "Asia/Riyadh" }).format(new Date(value)) : "—";
  return <section className="grid min-h-[650px] gap-2 xl:grid-cols-2"><div className="flex min-h-0 flex-col overflow-hidden rounded border bg-white"><header className="flex items-center justify-between border-b p-3"><strong className="text-base"><CircleDollarSign className="me-2 inline size-5 text-[#0b8ecb]" />المدفوعات</strong><span className="rounded-full bg-cyan-50 px-3 py-1 font-black text-[#0879b8]">{rows.length}</span></header><div className="grid max-h-[650px] gap-1 overflow-y-auto p-2">{rows.map((payment) => { const name = `${payment.customers?.first_name ?? ""} ${payment.customers?.last_name ?? ""}`.trim() || "عميل"; const paid = Number(payment.paid_amount ?? payment.amount ?? 0); return <article key={payment.id} className="grid grid-cols-[auto_1fr_auto] items-center gap-3 border-b bg-[#f8fafc] p-3"><span className="grid size-8 place-items-center rounded-full border-2 border-emerald-400 text-lg font-black text-emerald-500">✓</span><div><div className="flex flex-wrap items-center gap-2"><b className="text-sm text-[#075985]">{name}</b><span className="text-slate-500">#{payment.customers?.customer_code || payment.customer_id}</span></div><p className="mt-1 text-[#0a8fb5]" dir="ltr">{payment.customers?.phone || "—"}</p><div className="mt-2 flex flex-wrap gap-2"><span className="rounded bg-sky-400 px-2 py-1 font-bold text-white">{methodLabel(payment.payment_method)}</span><span className="text-slate-500">{relative(payment.payment_date ?? payment.created_at)}</span></div></div><div className="text-left"><b className="block text-base text-emerald-500">{new Intl.NumberFormat("ar-SA", { style: "currency", currency: payment.currency || "SAR", maximumFractionDigits: 2 }).format(paid)}</b><div className="mt-3 [&_button]:border-emerald-300 [&_button]:text-emerald-700"><InvoiceDialog payment={payment} /></div></div></article>; })}{!rows.length && <p className="py-20 text-center text-slate-400">لا توجد بيانات</p>}</div><button onClick={onRefresh} className="m-2 ms-auto grid size-9 place-items-center rounded bg-[#0879b8] text-white"><RefreshCw className={`size-4 ${busy ? "animate-spin" : ""}`} /></button></div><div className="rounded border bg-white"><button className="flex w-full items-center justify-between border-b p-4 font-bold"><span>الرسوم البيانية للوحة الرئيسية</span><span>‹</span></button><div className="grid place-items-center p-16 text-center text-slate-400"><BarChart3 className="mb-3 size-12 text-slate-300" /><p>ملخص المدفوعات حسب طريقة الدفع يظهر هنا</p><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded border p-3"><b className="block text-lg text-emerald-600">{new Intl.NumberFormat("ar-SA").format(rows.reduce((sum, item) => sum + Number(item.paid_amount ?? 0), 0))}</b><span>إجمالي المحصل</span></div><div className="rounded border p-3"><b className="block text-lg text-[#0879b8]">{rows.length}</b><span>عدد المدفوعات</span></div></div></div></div></section>;
}
