"use client";
import Link from"next/link";
import{useMemo,useState}from"react";
import{Banknote,CalendarDays,CheckCircle2,Clock3,FileText,RefreshCw,Search,UserRound,type LucideIcon}from"lucide-react";
import{useLocale}from"@/components/LocaleProvider";
import{useClinic}from"@/features/clinic/hooks/useClinic";
import{useAppointments}from"@/features/appointments/hooks/useAppointments";
import{useMasterData}from"@/features/appointments/hooks/useMasterData";
import{usePayments}from"@/features/payments/hooks/usePayments";
import type{Appointment,AppointmentStatus}from"@/features/appointments/types/appointment";
import DateRangeFilter from"@/features/date-range/DateRangeFilter";
import{isWithinDateRange}from"@/features/date-range/date-range";
import{useDateRange}from"@/features/date-range/useDateRange";
import{groupServiceFamilies,serviceFamilyLabel}from"@/features/services/service-family";
import{usePermission}from"@/features/users/hooks/usePermission";
import{useSecureUiMetrics}from"@/features/dashboard/hooks/useSecureUiMetrics";
import AppointmentCustomerWorkspace from"./AppointmentCustomerWorkspace";
import InvoiceDialog from"@/features/payments/components/InvoiceDialog";

const statusStyles:Record<AppointmentStatus,string>={booked:"border-sky-200 bg-sky-50 text-sky-800",confirmed:"border-blue-200 bg-blue-50 text-blue-800",arrived:"border-violet-200 bg-violet-50 text-violet-800",completed:"border-emerald-200 bg-emerald-50 text-emerald-800",cancelled:"border-rose-200 bg-rose-50 text-rose-800",no_show:"border-slate-200 bg-slate-100 text-slate-700"};
export default function DashboardOverview(){
 const{isArabic,text}=useLocale(),{clinic,selectedBranch}=useClinic(),range=useDateRange();const clinicId=clinic?.id??0,branchId=selectedBranch?.id??0;
 const financeAllowed=usePermission("dashboard.finance.view").allowed,appointmentsCountAllowed=usePermission("dashboard.appointments_count.view").allowed,completedCountAllowed=usePermission("dashboard.completed_patients_count.view").allowed,invoiceCountAllowed=usePermission("dashboard.invoice_count.view").allowed,collectionsAllowed=usePermission("dashboard.collections_total.view").allowed,canManage=usePermission("appointments.manage").allowed;
 const[doctorId,setDoctorId]=useState("all"),[serviceFamily,setServiceFamily]=useState("all"),[search,setSearch]=useState(""),[selectedAppointment,setSelectedAppointment]=useState<Appointment|null>(null);
 const appointmentsQuery=useAppointments(clinicId,branchId),paymentsQuery=usePayments(clinicId,branchId),masterQuery=useMasterData();
 const doctors=useMemo(()=>(masterQuery.data?.staff??[]).filter(x=>x.is_active&&x.role?.toLowerCase()==="doctor"),[masterQuery.data]);const services=useMemo(()=>(masterQuery.data?.services??[]).filter(x=>x.is_active),[masterQuery.data]);const families=useMemo(()=>groupServiceFamilies(services),[services]);const serviceIds=useMemo(()=>families.find(x=>x.key===serviceFamily)?.serviceIds??[],[families,serviceFamily]);
 const appointments=useMemo(()=>(appointmentsQuery.data??[]).filter(x=>{const patient=`${x.customers?.first_name??""} ${x.customers?.last_name??""} ${x.customers?.phone??""}`.toLowerCase();return isWithinDateRange(x.appointment_at,range)&&(doctorId==="all"||x.doctor_id===Number(doctorId))&&(serviceFamily==="all"||(x.service_id!=null&&serviceIds.includes(x.service_id)))&&(!search.trim()||patient.includes(search.trim().toLowerCase()))}).sort((a,b)=>+new Date(a.appointment_at)-+new Date(b.appointment_at)),[appointmentsQuery.data,range,doctorId,serviceFamily,serviceIds,search]);
 const payments=useMemo(()=>(paymentsQuery.data??[]).filter(x=>isWithinDateRange(x.payment_date??x.created_at,range)&&(doctorId==="all"||x.appointments?.doctor_id===Number(doctorId))&&(serviceFamily==="all"||(x.appointments?.service_id!=null&&serviceIds.includes(x.appointments.service_id))||x.payment_invoice_items?.some(line=>serviceIds.includes(line.service_id)))),[paymentsQuery.data,range,doctorId,serviceFamily,serviceIds]);
 const secure=useSecureUiMetrics(branchId,range.from,range.to,doctorId==="all"?null:Number(doctorId),serviceFamily==="all"?null:serviceIds),money=(n:number)=>new Intl.NumberFormat(isArabic?"ar-SA":"en-SA",{style:"currency",currency:"SAR",maximumFractionDigits:2}).format(n),serviceName=(id:number|null)=>{const s=services.find(x=>x.id===id);return s?serviceFamilyLabel(s,isArabic):text("Service","خدمة")},statusLabel=(s:AppointmentStatus)=>({booked:text("Booked","محجوز"),confirmed:text("Confirmed","مؤكد"),arrived:text("Arrived","تم الوصول"),completed:text("Completed","مكتمل"),cancelled:text("Cancelled","ملغي"),no_show:text("No show","لم يحضر")})[s];
 const outstanding=payments.filter(x=>Number(x.balance_due??0)>0&&!['cancelled','refunded'].includes(x.payment_status)),invoiceAppointmentIds=new Set((paymentsQuery.data??[]).map(x=>x.appointment_id).filter((id):id is number=>id!=null)),needsInvoice=appointments.filter(x=>x.status==="completed"&&!invoiceAppointmentIds.has(x.id));
 const metrics:Array<[string,string|number,LucideIcon]>=[...(appointmentsCountAllowed?[[text("Appointments","المواعيد"),secure.data?.appointments??0,CalendarDays]as[string,string|number,LucideIcon]]:[]),...(completedCountAllowed?[[text("Completed patients","المرضى المكتملون"),secure.data?.completedPatients??0,CheckCircle2]as[string,string|number,LucideIcon]]:[]),...(invoiceCountAllowed?[[text("Invoices","الفواتير"),secure.data?.invoiceCount??0,FileText]as[string,string|number,LucideIcon]]:[]),...((collectionsAllowed||financeAllowed)?[[text("Collected","المحصل"),money(secure.data?.collected??0),Banknote]as[string,string|number,LucideIcon]]:[])];
 const busy=appointmentsQuery.isFetching||paymentsQuery.isFetching;
 return <div className="space-y-3" dir={isArabic?"rtl":"ltr"}>
  <section className="overflow-hidden rounded-2xl bg-[#071826] text-white shadow-xl"><div className="flex flex-col gap-3 p-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[10px] font-black tracking-[.22em] text-cyan-300">PANTHERA</p><h1 className="mt-1 text-2xl font-black">{text("Your clinic, live and under control","عيادتك لحظة بلحظة")}</h1></div><div className="flex gap-2"><Link href="/appointments" className="rounded-lg bg-cyan-400 px-3 py-2 text-xs font-black text-slate-950">{text("New appointment","موعد جديد")}</Link><button onClick={()=>{void appointmentsQuery.refetch();void paymentsQuery.refetch()}} className="grid size-9 place-items-center rounded-lg bg-white/10" aria-label={text("Refresh","تحديث")}><RefreshCw className={`size-4 ${busy?"animate-spin":""}`}/></button></div></div><div className="grid border-t border-white/10 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label,value,Icon])=><div key={label} className="flex items-center gap-3 border-white/10 p-3 sm:border-s"><Icon className="size-4 text-cyan-300"/><div><p className="text-[10px] text-slate-400">{label}</p><p className="text-xl font-black">{value}</p></div></div>)}</div></section>
  <section className="space-y-2 rounded-xl border bg-white p-3"><DateRangeFilter/><div className="grid gap-2 xl:grid-cols-[1.25fr_1fr_1fr_auto]"><label className="flex items-center gap-2 rounded-lg border bg-slate-50 px-3"><Search className="size-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={text("Search patient","البحث عن مريض")} className="h-9 w-full bg-transparent text-xs outline-none"/></label><select value={doctorId} onChange={e=>setDoctorId(e.target.value)} className="h-9 rounded-lg border px-2 text-xs"><option value="all">{text("All doctors","كل الطبيبات")}</option>{doctors.map(x=><option key={x.id} value={x.id}>{x.staff_name}</option>)}</select><select value={serviceFamily} onChange={e=>setServiceFamily(e.target.value)} className="h-9 rounded-lg border px-2 text-xs"><option value="all">{text("All services","كل الخدمات")}</option>{families.map(x=><option key={x.key} value={x.key}>{isArabic?x.nameAr:x.nameEn}</option>)}</select><button onClick={()=>{setDoctorId("all");setServiceFamily("all");setSearch("");range.setPreset("today")}} className="h-9 rounded-lg border px-3 text-xs font-bold">{text("Reset","إعادة ضبط")}</button></div></section>
  <section className="grid gap-3 xl:grid-cols-2">
   <div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><header className="flex items-center justify-between border-b p-3"><div><h2 className="font-black">{text("Appointments","المواعيد")}</h2><p className="text-xs text-slate-500">{appointments.length} {text("appointments","موعد")}</p></div><CalendarDays className="size-5 text-cyan-600"/></header><div className="grid max-h-[62vh] gap-2 overflow-y-auto p-3">{appointments.length?appointments.map(x=>{const customer=`${x.customers?.first_name??""} ${x.customers?.last_name??""}`.trim()||text("Patient","مريض"),time=new Intl.DateTimeFormat(isArabic?"ar-SA":"en-US",{hour:"numeric",minute:"2-digit",hour12:true,timeZone:"Asia/Riyadh"}).format(new Date(x.appointment_at));return <button key={x.id} onClick={()=>setSelectedAppointment(x)} className={`rounded-xl border p-3 text-start ${statusStyles[x.status]}`}><div className="flex items-center justify-between"><span className="flex items-center gap-2"><UserRound className="size-4"/><b>{customer}</b></span><span className="rounded-full bg-white/80 px-2 py-1 text-[10px] font-black">{statusLabel(x.status)}</span></div><div className="mt-2 grid gap-1 text-xs sm:grid-cols-3"><span><Clock3 className="me-1 inline size-3.5"/>{time}</span><span>{x.staff?.staff_name||text("Department","قسم")}</span><span>{serviceName(x.service_id)}</span></div></button>}):<p className="py-16 text-center text-sm text-slate-400">{text("No appointments","لا توجد مواعيد")}</p>}</div></div>
   <div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><header className="flex items-center justify-between border-b p-3"><div><h2 className="font-black">{text("Invoices required for payment","الفواتير المطلوبة للدفع")}</h2><p className="text-xs text-slate-500">{outstanding.length+needsInvoice.length} {text("items require action","حالة تحتاج إجراء")}</p></div><FileText className="size-5 text-rose-600"/></header><div className="grid max-h-[62vh] gap-2 overflow-y-auto p-3">{needsInvoice.map(x=><article key={`new-${x.id}`} className="rounded-xl border border-amber-200 bg-amber-50 p-3"><div className="flex justify-between gap-2"><div><b>{`${x.customers?.first_name??""} ${x.customers?.last_name??""}`.trim()}</b><p className="text-xs text-amber-800">{serviceName(x.service_id)} · {x.staff?.staff_name}</p></div><span className="h-fit rounded-full bg-amber-200 px-2 py-1 text-[10px] font-black text-amber-900">{text("Invoice required","مطلوب فاتورة")}</span></div><Link href="/payments" className="mt-2 block rounded-lg bg-amber-700 px-3 py-2 text-center text-xs font-black text-white">{text("Issue invoice","إصدار الفاتورة")}</Link></article>)}{outstanding.map(p=><article key={p.id} className="rounded-xl border border-rose-200 bg-rose-50 p-3"><div className="flex items-start justify-between gap-2"><div><b>{`${p.customers?.first_name??""} ${p.customers?.last_name??""}`.trim()}</b><p className="text-xs text-slate-500">{p.invoice_number||`ZRN-${p.id}`} · {p.appointments?.staff?.staff_name||"—"}</p></div><b className="text-rose-700">{money(Number(p.balance_due))}</b></div><div className="mt-2 flex justify-end"><InvoiceDialog payment={p}/></div></article>)}{!needsInvoice.length&&!outstanding.length&&<p className="py-16 text-center text-sm text-emerald-700">{text("No invoices require payment","لا توجد فواتير مطلوبة للدفع")}</p>}</div></div>
  </section><AppointmentCustomerWorkspace appointment={selectedAppointment} payments={paymentsQuery.data??[]} open={!!selectedAppointment} onOpenChange={v=>{if(!v)setSelectedAppointment(null)}} canManage={canManage}/>
 </div>;
}
