export const PAGE_PERMISSION_GROUPS: Record<string, readonly string[]> = {
  "/tasks": ["tasks.view", "tasks.create", "tasks.manage"],
  "/customers": [
    "customers.view",
    "customers.details.view",
    "customers.create",
    "customers.edit",
    "customers.deactivate",
    "customers.export",
    "customers.manage",
    "patient_documents.view",
    "patient_documents.create",
    "patient_documents.manage",
  ],
  "/appointments": [
    "appointments.view",
    "appointments.create",
    "appointments.edit",
    "appointments.cancel",
    "appointments.patient_requests.manage",
    "appointments.manage",
    "calendar.view",
  ],
  "/calendar": ["calendar.view", "appointments.manage"],
  "/follow-ups": ["followups.view", "followups.manage"],
  "/treatments": [
    "treatments.view",
    "treatments.create",
    "treatments.edit",
    "treatments.complete",
    "treatments.manage",
    "medical.view",
    "medical.edit",
  ],
  "/payments": [
    "payments.view",
    "payments.amounts.view",
    "payments.invoice_count.view",
    "payments.total.view",
    "payments.paid_total.view",
    "payments.remaining_total.view",
    "payments.create",
    "payments.refund",
    "payments.invoice.print",
    "payments.manage",
  ],
  "/price-list": ["services.view", "services.manage", "settings.manage"],
  "/inventory": ["inventory.view", "inventory.cost.view", "inventory.manage"],
  "/staff": [
    "staff.view",
    "staff.salary.view",
    "staff.manage",
    "staff.attendance.manage",
    "staff.schedule.manage",
  ],
  "/marketing": ["marketing.view", "marketing.spend.view", "marketing.manage"],
  "/reports": [
    "reports.view",
    "reports.finance.view",
    "reports.doctor_revenue.view",
    "reports.feedback.view",
    "reports.export",
  ],
  "/accounting": [
    "accounting.view",
    "accounting.manage",
    "incomes.view",
    "incomes.create",
    "incomes.manage",
    "expenses.view",
    "expenses.create",
    "expenses.pay",
    "expenses.manage",
    "payments.manage",
    "reports.finance.view",
  ],
  "/patient-app": ["patient_app.analytics", "patient_app.identity.view"],
  "/ask-zernio": ["ai.view", "ai.use"],
  "/ai-agents": ["ai.view", "ai.use"],
  "/enterprise": ["enterprise.view", "enterprise.manage", "audit.view"],
  "/logs": ["audit.view"],
  "/messages": ["messages.view", "messages.reply", "messages.manage"],
  "/support": ["support.create", "support.manage", "settings.manage"],
  "/settings/users": ["users.manage"],
  "/settings/clinic-context": [
    "branches.view",
    "branches.manage",
    "settings.view",
    "settings.manage",
  ],
  "/settings/master-data": [
    "branches.view",
    "branches.manage",
    "rooms.view",
    "rooms.manage",
    "services.view",
    "services.manage",
    "settings.view",
    "settings.manage",
  ],
  "/settings/patient-catalogs": ["patient_catalogs.manage", "settings.manage"],
  "/settings/operations": [
    "settings.templates.manage",
    "settings.integrations.manage",
    "settings.processes.manage",
    "settings.print.manage",
    "settings.manage",
  ],
  "/settings": [
    "settings.view",
    "settings.manage",
    "users.manage",
    "branches.view",
    "branches.manage",
    "rooms.view",
    "rooms.manage",
    "services.view",
    "services.manage",
    "patient_catalogs.manage",
    "settings.templates.manage",
    "settings.integrations.manage",
    "settings.processes.manage",
    "settings.print.manage",
  ],
  "/api/ai": ["ai.use"],
  "/api/payments": ["payments.manage"],
  "/api/reports": ["reports.view", "reports.export"],
  "/api/admin/users": ["users.manage"],
};

export function permissionsForPath(pathname: string) {
  const prefix = Object.keys(PAGE_PERMISSION_GROUPS)
    .sort((left, right) => right.length - left.length)
    .find(
      (candidate) =>
        pathname === candidate || pathname.startsWith(`${candidate}/`),
    );
  return prefix ? PAGE_PERMISSION_GROUPS[prefix] : null;
}
