"use client";
import Link from "next/link";
import {LockKeyhole,Search,X} from "lucide-react";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {useLocale} from "@/components/LocaleProvider";
import {useClinic} from "@/features/clinic/hooks/useClinic";
import {useCurrentPermissions} from "@/features/users/hooks/useCurrentPermissions";
import {allNavItems} from "@/components/nav-items";

type Result={id:string;title:string;subtitle:string;href:string;permission:string};
const norm=(value:string)=>value.trim().toLocaleLowerCase("ar");
const includes=(values:Array<string|null|undefined>,query:string)=>values.some(value=>norm(value??"").includes(query));

export default function GlobalSearch(){const[open,setOpen]=useState(false),[query,setQuery]=useState(""),[results,setResults]=useState<Result[]>([]),[loading,setLoading]=useState(false);const{isArabic,text}=useLocale();const{clinic,selectedBranch}=useClinic();const permissionsQuery=useCurrentPermissions();const permissions=permissionsQuery.data??new Set<string>();
const pageMatches=useMemo(()=>{const q=norm(query);if(!q)return[];return allNavItems.filter(([en,ar,,,permission,keywords])=>includes([en,ar,...keywords],q)).map(([en,ar,href,,permission])=>({id:`page-${href}`,title:isArabic?ar:en,subtitle:permissions.has(permission)?text("System section","قسم في النظام"):text("Not available to you","غير متوفر لك"),href,permission,locked:!permissions.has(permission)}));},[query,isArabic,permissions,text]);
useEffect(()=>{if(!open||norm(query).length<2||!clinic?.id){setResults([]);return}const timer=setTimeout(()=>void search(),250);return()=>clearTimeout(timer);
async function search(){setLoading(true);const q=norm(query);const supabase=createClient();const clinicId=clinic?.id??0,branchId=selectedBranch?.id;const jobs:Array<Promise<void>>=[];const add=(permission:string,job:()=>PromiseLike<{data:unknown[]|null;error:unknown}>,map:(row:any)=>Result)=>{if(!permissions.has(permission))return;jobs.push(Promise.resolve(job()).then(({data})=>{if(data)found.push(...data.map(map))}).catch(()=>undefined))};const found:Result[]=[];
add("customers.view",()=>supabase.from("customers").select("id,first_name,last_name,phone,customer_code,email").eq("clinic_id",clinicId).limit(12),row=>({id:`customer-${row.id}`,title:`${row.first_name??""} ${row.last_name??""}`.trim()||text("Patient","مريض"),subtitle:[row.phone,row.customer_code,row.email].filter(Boolean).join(" · "),href:`/customers/${row.id}`,permission:"customers.view"}));
add("appointments.view",()=>supabase.from("appointments").select("id,status,appointment_at,notes,customers(first_name,last_name,phone),services(name),staff(staff_name)").eq("clinic_id",clinicId).limit(30),row=>({id:`appointment-${row.id}`,title:`${text("Appointment","موعد")} #${row.id}`,subtitle:[row.customers?.first_name,row.customers?.last_name,row.customers?.phone,row.services?.name,row.staff?.staff_name,row.status].filter(Boolean).join(" · "),href:"/appointments",permission:"appointments.view"}));
add("treatments.view",()=>supabase.from("treatments").select("id,service_name,doctor_name,status,notes").eq("clinic_id",clinicId).limit(30),row=>({id:`treatment-${row.id}`,title:row.service_name||`${text("Treatment","علاج")} #${row.id}`,subtitle:[row.doctor_name,row.status,row.notes].filter(Boolean).join(" · "),href:"/treatments",permission:"treatments.view"}));
add("payments.view",()=>supabase.from("payments").select("id,invoice_number,reference_number,payment_status,notes,customers(first_name,last_name,phone)").eq("clinic_id",clinicId).limit(30),row=>({id:`payment-${row.id}`,title:row.invoice_number||`${text("Invoice","فاتورة")} #${row.id}`,subtitle:[row.reference_number,row.customers?.first_name,row.customers?.last_name,row.customers?.phone,row.payment_status].filter(Boolean).join(" · "),href:"/payments",permission:"payments.view"}));
add("services.view",()=>supabase.from("services").select("id,name,name_ar,name_en,code,category").eq("clinic_id",clinicId).limit(50),row=>({id:`service-${row.id}`,title:(isArabic?row.name_ar:row.name_en)||row.name,subtitle:[row.code,row.category].filter(Boolean).join(" · "),href:"/price-list",permission:"services.view"}));
add("staff.view",()=>supabase.from("staff").select("id,staff_name,employee_code,role,department,phone,email").eq("clinic_id",clinicId).limit(40),row=>({id:`staff-${row.id}`,title:row.staff_name||`${text("Employee","موظف")} #${row.id}`,subtitle:[row.employee_code,row.role,row.department,row.phone,row.email].filter(Boolean).join(" · "),href:"/staff",permission:"staff.view"}));
add("inventory.view",()=>supabase.from("inventory_products").select("id,name,sku,barcode,category").eq("clinic_id",clinicId).limit(50),row=>({id:`product-${row.id}`,title:row.name,subtitle:[row.sku,row.barcode,row.category].filter(Boolean).join(" · "),href:"/inventory",permission:"inventory.view"}));
await Promise.all(jobs);setResults(found.filter(item=>includes([item.title,item.subtitle],q)).slice(0,30));setLoading(false)}},[open,query,clinic?.id,selectedBranch?.id,permissions,isArabic,text]);
const denied=norm(query).length>=2&&allNavItems.some(item=>!permissions.has(item[4]));
return <><button type="button" onClick={()=>setOpen(true)} aria-label={text("Search anything","ابحث عن أي شيء")} className="hidden h-10 min-w-48 items-center gap-2 rounded-xl border bg-white px-3 text-sm text-slate-400 shadow-sm md:flex"><Search className="size-4"/>{text("Search anything","ابحث عن أي شيء")}</button><button type="button" onClick={()=>setOpen(true)} aria-label={text("Search","بحث")} className="grid size-10 place-items-center rounded-xl border bg-white text-slate-600 shadow-sm md:hidden"><Search className="size-4"/></button>{open&&<div className="fixed inset-0 z-[110] bg-slate-950/50 p-3 backdrop-blur-sm md:p-10" onClick={()=>setOpen(false)}><section dir={isArabic?"rtl":"ltr"} className="mx-auto max-h-[88vh] w-full max-w-2xl overflow-hidden rounded-3xl bg-white shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center gap-3 border-b p-4"><Search className="size-5 text-slate-400"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder={text("Search patients, invoices, appointments, services...","ابحث عن مريض أو فاتورة أو موعد أو خدمة...")} className="h-11 min-w-0 flex-1 bg-transparent outline-none"/><button onClick={()=>setOpen(false)} aria-label={text("Close","إغلاق")}><X className="size-5"/></button></div><div className="max-h-[70vh] overflow-y-auto p-3">{query.trim().length<2?<p className="p-8 text-center text-sm text-slate-500">{text("Type at least two characters to search the whole system.","اكتب حرفين على الأقل للبحث في النظام بالكامل.")}</p>:<>{loading&&<p className="p-4 text-center text-sm text-slate-500">{text("Searching...","جارٍ البحث...")}</p>}{pageMatches.map(item=>item.locked?<div key={item.id} className="flex items-center gap-3 rounded-xl bg-amber-50 p-4 text-amber-800"><LockKeyhole className="size-5"/><div><p className="font-bold">{item.title}</p><p className="text-xs">{text("Not available to you","غير متوفر لك")}</p></div></div>:<Link key={item.id} href={item.href} onClick={()=>setOpen(false)} className="block rounded-xl p-4 hover:bg-slate-50"><p className="font-bold">{item.title}</p><p className="text-xs text-slate-500">{item.subtitle}</p></Link>)}{results.map(item=><Link key={item.id} href={item.href} onClick={()=>setOpen(false)} className="block rounded-xl border-t p-4 hover:bg-slate-50"><p className="font-bold">{item.title}</p><p className="mt-1 text-xs text-slate-500">{item.subtitle}</p></Link>)}{!loading&&!pageMatches.length&&!results.length&&<p className="p-8 text-center text-sm text-slate-500">{text("No matching results were found.","لم يتم العثور على نتائج مطابقة.")}</p>}{denied&&<p className="m-3 flex items-center gap-2 rounded-xl bg-slate-100 p-3 text-xs text-slate-600"><LockKeyhole className="size-4"/>{text("Some results may be unavailable because of your permissions.","قد توجد نتائج أخرى غير متوفرة لك بسبب صلاحيات حسابك.")}</p>}</>}</div></section></div>}</>}
