export type PermissionMeta = {
  moduleAr: string;
  moduleEn: string;
  labelAr: string;
  labelEn: string;
  descriptionAr: string;
  risk?: "sensitive" | "critical";
};

export const permissionMeta: Record<string, PermissionMeta> = {
  "dashboard.view": {
    moduleAr: "لوحة التحكم",
    moduleEn: "Dashboard",
    labelAr: "عرض لوحة التحكم",
    labelEn: "View dashboard",
    descriptionAr: "فتح الصفحة الرئيسية والمؤشرات العامة",
  },
  "dashboard.finance.view": {
    moduleAr: "لوحة التحكم",
    moduleEn: "Dashboard",
    labelAr: "عرض ملخص الدخل",
    labelEn: "View dashboard income",
    descriptionAr: "إظهار الإيراد والمدفوع والمتبقي في لوحة التحكم",
    risk: "sensitive",
  },
  "dashboard.appointments_count.view": {
    moduleAr: "لوحة التحكم",
    moduleEn: "Dashboard",
    labelAr: "عرض عدد المواعيد",
    labelEn: "View appointment count",
    descriptionAr: "إظهار بطاقة عدد المواعيد في الواجهة",
  },
  "dashboard.completed_patients_count.view": {
    moduleAr: "لوحة التحكم",
    moduleEn: "Dashboard",
    labelAr: "عرض المرضى المكتملين",
    labelEn: "View completed patients",
    descriptionAr: "إظهار بطاقة عدد المرضى المكتملين",
  },
  "dashboard.invoice_count.view": {
    moduleAr: "لوحة التحكم",
    moduleEn: "Dashboard",
    labelAr: "عرض عدد الفواتير",
    labelEn: "View invoice count",
    descriptionAr: "إظهار بطاقة عدد الفواتير",
  },
  "dashboard.collections_total.view": {
    moduleAr: "لوحة التحكم",
    moduleEn: "Dashboard",
    labelAr: "عرض إجمالي المحصل",
    labelEn: "View collected total",
    descriptionAr: "إظهار قيمة المحصل في بطاقة لوحة التحكم",
    risk: "sensitive",
  },
  "dashboard.invoiced_total.view": {
    moduleAr: "لوحة التحكم",
    moduleEn: "Dashboard",
    labelAr: "عرض إجمالي الفواتير بالملخص",
    labelEn: "View invoiced summary",
    descriptionAr: "إظهار إجمالي الفواتير في الملخص المالي",
    risk: "sensitive",
  },
  "dashboard.paid_total.view": {
    moduleAr: "لوحة التحكم",
    moduleEn: "Dashboard",
    labelAr: "عرض المدفوع بالملخص",
    labelEn: "View paid summary",
    descriptionAr: "إظهار المدفوع في الملخص المالي",
    risk: "sensitive",
  },
  "dashboard.remaining_total.view": {
    moduleAr: "لوحة التحكم",
    moduleEn: "Dashboard",
    labelAr: "عرض المتبقي بالملخص",
    labelEn: "View remaining summary",
    descriptionAr: "إظهار المتبقي في الملخص المالي",
    risk: "sensitive",
  },
  "customers.view": {
    moduleAr: "المرضى",
    moduleEn: "Patients",
    labelAr: "عرض المرضى",
    labelEn: "View patients",
    descriptionAr: "عرض القائمة والملفات الأساسية",
  },
  "customers.details.view": {
    moduleAr: "المرضى",
    moduleEn: "Patients",
    labelAr: "عرض ملف المريض الكامل",
    labelEn: "View full patient profile",
    descriptionAr: "عرض التاريخ الطبي والمالي والتواصل",
    risk: "sensitive",
  },
  "customers.create": {
    moduleAr: "المرضى",
    moduleEn: "Patients",
    labelAr: "إضافة مريض",
    labelEn: "Create patient",
    descriptionAr: "إنشاء ملف مريض جديد",
  },
  "customers.edit": {
    moduleAr: "المرضى",
    moduleEn: "Patients",
    labelAr: "تعديل بيانات المريض",
    labelEn: "Edit patient",
    descriptionAr: "تعديل البيانات الشخصية والطبية",
  },
  "customers.deactivate": {
    moduleAr: "المرضى",
    moduleEn: "Patients",
    labelAr: "تعطيل ملف المريض",
    labelEn: "Deactivate patient",
    descriptionAr: "إيقاف الملف دون حذفه",
    risk: "critical",
  },
  "customers.export": {
    moduleAr: "المرضى",
    moduleEn: "Patients",
    labelAr: "تصدير بيانات المرضى",
    labelEn: "Export patients",
    descriptionAr: "تنزيل أو استخراج بيانات المرضى",
    risk: "critical",
  },
  "customers.manage": {
    moduleAr: "المرضى",
    moduleEn: "Patients",
    labelAr: "إدارة المرضى - صلاحية شاملة",
    labelEn: "Manage patients - full",
    descriptionAr: "صلاحية توافقية تشمل إجراءات إدارة المرضى",
  },
  "patient_app.analytics": {
    moduleAr: "تطبيق المرضى",
    moduleEn: "Patient app",
    labelAr: "عرض تحليلات التطبيق",
    labelEn: "View app analytics",
    descriptionAr: "عرض أعداد المستخدمين والجلسات",
  },
  "patient_app.identity.view": {
    moduleAr: "تطبيق المرضى",
    moduleEn: "Patient app",
    labelAr: "عرض هوية النشطين",
    labelEn: "View active patient identity",
    descriptionAr: "إظهار أسماء وبيانات المرضى المستخدمين للتطبيق",
    risk: "sensitive",
  },
  "appointments.view": {
    moduleAr: "المواعيد",
    moduleEn: "Appointments",
    labelAr: "عرض المواعيد",
    labelEn: "View appointments",
    descriptionAr: "عرض قوائم المواعيد",
  },
  "appointments.create": {
    moduleAr: "المواعيد",
    moduleEn: "Appointments",
    labelAr: "إنشاء موعد",
    labelEn: "Create appointment",
    descriptionAr: "حجز موعد جديد",
  },
  "appointments.edit": {
    moduleAr: "المواعيد",
    moduleEn: "Appointments",
    labelAr: "تعديل الموعد",
    labelEn: "Edit appointment",
    descriptionAr: "تغيير الوقت أو مقدم الخدمة أو الحالة",
  },
  "appointments.cancel": {
    moduleAr: "المواعيد",
    moduleEn: "Appointments",
    labelAr: "إلغاء الموعد",
    labelEn: "Cancel appointment",
    descriptionAr: "إلغاء موعد قائم",
    risk: "critical",
  },
  "appointments.patient_requests.manage": {
    moduleAr: "المواعيد",
    moduleEn: "Appointments",
    labelAr: "إدارة طلبات تطبيق المرضى",
    labelEn: "Manage patient requests",
    descriptionAr: "قبول ورفض طلبات الحجز الواردة من التطبيق",
  },
  "appointments.manage": {
    moduleAr: "المواعيد",
    moduleEn: "Appointments",
    labelAr: "إدارة المواعيد - صلاحية شاملة",
    labelEn: "Manage appointments - full",
    descriptionAr: "صلاحية توافقية تشمل إجراءات إدارة المواعيد",
  },
  "calendar.view": {
    moduleAr: "المواعيد",
    moduleEn: "Appointments",
    labelAr: "عرض التقويم",
    labelEn: "View calendar",
    descriptionAr: "فتح تقويم المواعيد",
  },
  "followups.view": {
    moduleAr: "المتابعات",
    moduleEn: "Follow-ups",
    labelAr: "عرض المتابعات",
    labelEn: "View follow-ups",
    descriptionAr: "عرض قائمة المتابعات",
  },
  "followups.manage": {
    moduleAr: "المتابعات",
    moduleEn: "Follow-ups",
    labelAr: "إدارة المتابعات",
    labelEn: "Manage follow-ups",
    descriptionAr: "إضافة وتحديث المتابعات",
  },
  "treatments.view": {
    moduleAr: "العلاجات",
    moduleEn: "Treatments",
    labelAr: "عرض العلاجات",
    labelEn: "View treatments",
    descriptionAr: "عرض الجلسات والخطط العلاجية",
  },
  "treatments.create": {
    moduleAr: "العلاجات",
    moduleEn: "Treatments",
    labelAr: "بدء جلسة علاج",
    labelEn: "Start treatment",
    descriptionAr: "إنشاء جلسة أو إجراء جديد",
  },
  "treatments.edit": {
    moduleAr: "العلاجات",
    moduleEn: "Treatments",
    labelAr: "تعديل العلاج",
    labelEn: "Edit treatment",
    descriptionAr: "تعديل تفاصيل الجلسة والخطة",
  },
  "treatments.complete": {
    moduleAr: "العلاجات",
    moduleEn: "Treatments",
    labelAr: "إنهاء جلسة علاج",
    labelEn: "Complete treatment",
    descriptionAr: "اعتماد انتهاء الجلسة ونتيجتها",
  },
  "treatments.manage": {
    moduleAr: "العلاجات",
    moduleEn: "Treatments",
    labelAr: "إدارة العلاجات - صلاحية شاملة",
    labelEn: "Manage treatments - full",
    descriptionAr: "صلاحية توافقية تشمل إجراءات إدارة العلاجات",
  },
  "medical.view": {
    moduleAr: "السجل الطبي",
    moduleEn: "Medical record",
    labelAr: "عرض السجل الطبي",
    labelEn: "View medical record",
    descriptionAr: "عرض الحساسية والأمراض والملاحظات",
    risk: "sensitive",
  },
  "medical.edit": {
    moduleAr: "السجل الطبي",
    moduleEn: "Medical record",
    labelAr: "تعديل السجل الطبي",
    labelEn: "Edit medical record",
    descriptionAr: "تعديل البيانات الطبية الحساسة",
    risk: "critical",
  },
  "payments.view": {
    moduleAr: "المالية",
    moduleEn: "Finance",
    labelAr: "عرض الفواتير",
    labelEn: "View invoices",
    descriptionAr: "عرض الفواتير دون مؤشرات الدخل",
  },
  "payments.amounts.view": {
    moduleAr: "المالية",
    moduleEn: "Finance",
    labelAr: "عرض المبالغ والتحصيل",
    labelEn: "View amounts and collections",
    descriptionAr: "إظهار قيم الفواتير والمدفوع والمتبقي",
    risk: "sensitive",
  },
  "payments.invoice_count.view": {
    moduleAr: "المالية",
    moduleEn: "Finance",
    labelAr: "عرض عدد الفواتير",
    labelEn: "View invoice count",
    descriptionAr: "إظهار بطاقة وعدد الفواتير",
  },
  "payments.total.view": {
    moduleAr: "المالية",
    moduleEn: "Finance",
    labelAr: "عرض إجمالي الفواتير",
    labelEn: "View invoice total",
    descriptionAr: "إظهار إجمالي قيمة الفواتير",
    risk: "sensitive",
  },
  "payments.paid_total.view": {
    moduleAr: "المالية",
    moduleEn: "Finance",
    labelAr: "عرض إجمالي المدفوع",
    labelEn: "View paid total",
    descriptionAr: "إظهار إجمالي المبالغ المدفوعة",
    risk: "sensitive",
  },
  "payments.remaining_total.view": {
    moduleAr: "المالية",
    moduleEn: "Finance",
    labelAr: "عرض إجمالي المتبقي",
    labelEn: "View remaining total",
    descriptionAr: "إظهار إجمالي المبالغ المتبقية",
    risk: "sensitive",
  },
  "payments.create": {
    moduleAr: "المالية",
    moduleEn: "Finance",
    labelAr: "تسجيل دفعة",
    labelEn: "Record payment",
    descriptionAr: "إضافة عملية تحصيل جديدة",
    risk: "critical",
  },
  "payments.refund": {
    moduleAr: "المالية",
    moduleEn: "Finance",
    labelAr: "تنفيذ استرداد",
    labelEn: "Refund payment",
    descriptionAr: "إرجاع مبلغ مدفوع",
    risk: "critical",
  },
  "payments.invoice.print": {
    moduleAr: "المالية",
    moduleEn: "Finance",
    labelAr: "طباعة الفاتورة",
    labelEn: "Print invoice",
    descriptionAr: "عرض وتنزيل نسخة الفاتورة",
  },
  "payments.manage": {
    moduleAr: "المالية",
    moduleEn: "Finance",
    labelAr: "إدارة المالية - صلاحية شاملة",
    labelEn: "Manage finance - full",
    descriptionAr: "صلاحية توافقية تشمل إجراءات المدفوعات",
    risk: "critical",
  },
  "reports.view": {
    moduleAr: "التقارير",
    moduleEn: "Reports",
    labelAr: "عرض تقارير التشغيل",
    labelEn: "View operational reports",
    descriptionAr: "عرض مؤشرات المواعيد والخدمات",
  },
  "reports.finance.view": {
    moduleAr: "التقارير",
    moduleEn: "Reports",
    labelAr: "عرض تقارير الدخل والتحصيل",
    labelEn: "View financial reports",
    descriptionAr: "عرض الإيرادات والتحصيل والمبالغ المستحقة",
    risk: "sensitive",
  },
  "reports.doctor_revenue.view": {
    moduleAr: "التقارير",
    moduleEn: "Reports",
    labelAr: "عرض دخل وأداء الأطباء",
    labelEn: "View doctor revenue",
    descriptionAr: "إظهار ترتيب الدخل لكل طبيب",
    risk: "sensitive",
  },
  "reports.export": {
    moduleAr: "التقارير",
    moduleEn: "Reports",
    labelAr: "تصدير التقارير",
    labelEn: "Export reports",
    descriptionAr: "تنزيل البيانات والتحليلات",
    risk: "critical",
  },
  "services.view": {
    moduleAr: "الخدمات والأسعار",
    moduleEn: "Services & prices",
    labelAr: "عرض الخدمات والأسعار",
    labelEn: "View services and prices",
    descriptionAr: "عرض الكتالوج والأسعار",
  },
  "services.manage": {
    moduleAr: "الخدمات والأسعار",
    moduleEn: "Services & prices",
    labelAr: "إدارة الخدمات والأسعار",
    labelEn: "Manage services and prices",
    descriptionAr: "إضافة وتعديل وإيقاف الخدمات",
  },
  "inventory.view": {
    moduleAr: "المخزون",
    moduleEn: "Inventory",
    labelAr: "عرض المخزون",
    labelEn: "View inventory",
    descriptionAr: "عرض الأصناف والكميات",
  },
  "inventory.cost.view": {
    moduleAr: "المخزون",
    moduleEn: "Inventory",
    labelAr: "عرض تكلفة المخزون",
    labelEn: "View inventory cost",
    descriptionAr: "إظهار أسعار التكلفة وقيمة المخزون",
    risk: "sensitive",
  },
  "inventory.manage": {
    moduleAr: "المخزون",
    moduleEn: "Inventory",
    labelAr: "إدارة المخزون",
    labelEn: "Manage inventory",
    descriptionAr: "إضافة الأصناف والحركات والتسويات",
  },
  "staff.view": {
    moduleAr: "الموظفون",
    moduleEn: "Staff",
    labelAr: "عرض الموظفين",
    labelEn: "View staff",
    descriptionAr: "عرض دليل الموظفين",
  },
  "staff.salary.view": {
    moduleAr: "الموظفون",
    moduleEn: "Staff",
    labelAr: "عرض الرواتب والدخل",
    labelEn: "View salaries",
    descriptionAr: "إظهار رواتب الموظفين والبيانات المالية",
    risk: "sensitive",
  },
  "staff.manage": {
    moduleAr: "الموظفون",
    moduleEn: "Staff",
    labelAr: "إدارة الموظفين",
    labelEn: "Manage staff",
    descriptionAr: "إضافة وتعديل وتعطيل الموظفين",
  },
  "staff.attendance.manage": {
    moduleAr: "الموظفون",
    moduleEn: "Staff",
    labelAr: "إدارة الحضور",
    labelEn: "Manage attendance",
    descriptionAr: "تسجيل وتعديل الحضور والانصراف",
  },
  "staff.schedule.manage": {
    moduleAr: "الموظفون",
    moduleEn: "Staff",
    labelAr: "إدارة جداول العمل",
    labelEn: "Manage schedules",
    descriptionAr: "تعديل الورديات وأيام العمل",
  },
  "marketing.view": {
    moduleAr: "التسويق",
    moduleEn: "Marketing",
    labelAr: "عرض التسويق",
    labelEn: "View marketing",
    descriptionAr: "عرض الحملات والعملاء المحتملين",
  },
  "marketing.spend.view": {
    moduleAr: "التسويق",
    moduleEn: "Marketing",
    labelAr: "عرض الإنفاق والعائد",
    labelEn: "View spend and ROI",
    descriptionAr: "إظهار تكاليف الحملات والعائد",
    risk: "sensitive",
  },
  "marketing.manage": {
    moduleAr: "التسويق",
    moduleEn: "Marketing",
    labelAr: "إدارة الحملات",
    labelEn: "Manage campaigns",
    descriptionAr: "إنشاء وتعديل وإيقاف الحملات",
  },
  "ai.view": {
    moduleAr: "ذكاء بانثيرا",
    moduleEn: "Panthera intelligence",
    labelAr: "عرض أدوات الذكاء",
    labelEn: "View AI tools",
    descriptionAr: "فتح صفحات الذكاء والأتمتة",
  },
  "ai.use": {
    moduleAr: "ذكاء بانثيرا",
    moduleEn: "Panthera intelligence",
    labelAr: "استخدام الذكاء الاصطناعي",
    labelEn: "Use AI",
    descriptionAr: "إرسال طلبات وتحليلات للذكاء الاصطناعي",
  },
  "enterprise.view": {
    moduleAr: "إدارة المؤسسة",
    moduleEn: "Enterprise",
    labelAr: "عرض مركز المؤسسة",
    labelEn: "View enterprise center",
    descriptionAr: "عرض الفروع والمهام وسجل النشاط",
  },
  "enterprise.manage": {
    moduleAr: "إدارة المؤسسة",
    moduleEn: "Enterprise",
    labelAr: "إدارة المؤسسة",
    labelEn: "Manage enterprise",
    descriptionAr: "إدارة المهام ومسارات العمل والفروع",
    risk: "critical",
  },
  "audit.view": {
    moduleAr: "إدارة المؤسسة",
    moduleEn: "Enterprise",
    labelAr: "عرض سجل التدقيق",
    labelEn: "View audit log",
    descriptionAr: "عرض سجل تغييرات المستخدمين",
    risk: "sensitive",
  },
  "settings.view": {
    moduleAr: "الإعدادات",
    moduleEn: "Settings",
    labelAr: "عرض الإعدادات",
    labelEn: "View settings",
    descriptionAr: "فتح صفحات إعداد النظام",
  },
  "settings.manage": {
    moduleAr: "الإعدادات",
    moduleEn: "Settings",
    labelAr: "تعديل إعدادات العيادة",
    labelEn: "Manage settings",
    descriptionAr: "تغيير إعدادات العيادة والبيانات الأساسية",
    risk: "critical",
  },
  "patient_documents.view": {
    moduleAr: "المرضى",
    moduleEn: "Patients",
    labelAr: "عرض مستندات المريض",
    labelEn: "View patient documents",
    descriptionAr: "عرض الوصفات وعروض الأسعار والنماذج والمرفقات المرتبطة بالمريض.",
  },
  "patient_documents.create": {
    moduleAr: "المرضى",
    moduleEn: "Patients",
    labelAr: "إضافة مستند للمريض",
    labelEn: "Create patient documents",
    descriptionAr: "إنشاء وصفة أو عرض سعر أو نموذج أو ملاحظة وربطه بملف المريض.",
  },
  "patient_documents.manage": {
    moduleAr: "المرضى",
    moduleEn: "Patients",
    labelAr: "إدارة مستندات المرضى",
    labelEn: "Manage patient documents",
    descriptionAr: "التحكم الكامل في مستندات وسجلات المرضى المرفقة.",
  },
  "patient_receipts.view": {
    moduleAr: "المرضى",
    moduleEn: "Patients",
    labelAr: "عرض معرض إيصالات المريض",
    labelEn: "View patient receipt gallery",
    descriptionAr: "عرض صور وملفات إيصالات الدفع المرتبطة بالمريض والمدفوعات.",
  },
  "patient_receipts.create": {
    moduleAr: "المرضى",
    moduleEn: "Patients",
    labelAr: "رفع إيصالات المريض",
    labelEn: "Upload patient receipts",
    descriptionAr: "التقاط صورة أو رفع ملف إيصال وربطه بالمريض وبدفعة محددة.",
  },
  "patient_receipts.manage": {
    moduleAr: "المرضى",
    moduleEn: "Patients",
    labelAr: "إدارة معرض إيصالات المرضى",
    labelEn: "Manage patient receipt galleries",
    descriptionAr: "التحكم الكامل في إيصالات الدفع المرفوعة بملفات المرضى.",
    risk: "sensitive",
  },
  "settings.templates.manage": {
    moduleAr: "الإعدادات",
    moduleEn: "Settings",
    labelAr: "إدارة قوالب الرسائل",
    labelEn: "Manage message templates",
    descriptionAr: "إنشاء وتعديل قوالب تأكيد المواعيد وإيصالات الدفع والمتابعات.",
  },
  "settings.integrations.manage": {
    moduleAr: "الإعدادات",
    moduleEn: "Settings",
    labelAr: "إدارة قنوات الربط والتواصل",
    labelEn: "Manage integrations",
    descriptionAr: "التحكم في قنوات البريد وواتساب والرسائل النصية المتاحة للنظام.",
  },
  "settings.processes.manage": {
    moduleAr: "الإعدادات",
    moduleEn: "Settings",
    labelAr: "إدارة قواعد التشغيل",
    labelEn: "Manage process rules",
    descriptionAr: "التحكم في التأكيد والمتابعة الآلية والبيانات الإلزامية للمرضى.",
  },
  "settings.print.manage": {
    moduleAr: "الإعدادات",
    moduleEn: "Settings",
    labelAr: "إدارة إعدادات الطباعة",
    labelEn: "Manage print settings",
    descriptionAr: "تعديل رأس وتذييل الفاتورة وعناصر الباركود والرمز والضريبة.",
  },
  "users.manage": {
    moduleAr: "الإعدادات",
    moduleEn: "Settings",
    labelAr: "إدارة المستخدمين والصلاحيات",
    labelEn: "Manage users and permissions",
    descriptionAr: "دعوة وتعطيل المستخدمين ومنح الصلاحيات",
    risk: "critical",
  },
  "support.create": {
    moduleAr: "الدعم الفني",
    moduleEn: "Support",
    labelAr: "إرسال طلبات الدعم",
    labelEn: "Create support requests",
    descriptionAr: "بدء محادثة مع الدعم الفني ومتابعة الطلبات الخاصة به",
  },
  "support.manage": {
    moduleAr: "الدعم الفني",
    moduleEn: "Support",
    labelAr: "استقبال وإدارة طلبات الدعم",
    labelEn: "Manage support inbox",
    descriptionAr: "عرض محادثات جميع الموظفين والرد عليها وتغيير حالتها",
    risk: "sensitive",
  },
};

Object.assign(permissionMeta, {
  "branches.view": {
    moduleAr: "الفروع",
    moduleEn: "Branches",
    labelAr: "عرض الفروع",
    labelEn: "View branches",
    descriptionAr: "عرض الفروع المتاحة للمستخدم",
  },
  "branches.manage": {
    moduleAr: "الفروع",
    moduleEn: "Branches",
    labelAr: "إدارة الفروع",
    labelEn: "Manage branches",
    descriptionAr: "إضافة الفروع وتعديلها وإيقافها",
    risk: "critical",
  },
  "rooms.view": {
    moduleAr: "الفروع",
    moduleEn: "Branches",
    labelAr: "عرض الغرف",
    labelEn: "View rooms",
    descriptionAr: "عرض غرف العيادة وتجهيزاتها",
  },
  "rooms.manage": {
    moduleAr: "الفروع",
    moduleEn: "Branches",
    labelAr: "إدارة الغرف",
    labelEn: "Manage rooms",
    descriptionAr: "إضافة الغرف وتعديلها وإيقافها",
  },
  "patient_catalogs.manage": {
    moduleAr: "الإعدادات",
    moduleEn: "Settings",
    labelAr: "إدارة علامات المرضى والإحالات",
    labelEn: "Manage patient catalogs",
    descriptionAr: "إدارة العلامات والألوان ومصادر الإحالة على مستوى النظام",
  },
  "tasks.view": {
    moduleAr: "المهام",
    moduleEn: "Tasks",
    labelAr: "عرض المهام",
    labelEn: "View tasks",
    descriptionAr: "عرض المهام المسندة وسجلها",
  },
  "tasks.create": {
    moduleAr: "المهام",
    moduleEn: "Tasks",
    labelAr: "إنشاء مهمة",
    labelEn: "Create tasks",
    descriptionAr: "إنشاء المهام وإسنادها",
  },
  "tasks.manage": {
    moduleAr: "المهام",
    moduleEn: "Tasks",
    labelAr: "إدارة جميع المهام",
    labelEn: "Manage all tasks",
    descriptionAr: "تعديل حالات جميع المهام وإعادة إسنادها",
  },
  "messages.view": {
    moduleAr: "رسائل المرضى",
    moduleEn: "Patient messages",
    labelAr: "عرض الرسائل",
    labelEn: "View messages",
    descriptionAr: "عرض محادثات المرضى المصرح بها",
    risk: "sensitive",
  },
  "messages.reply": {
    moduleAr: "رسائل المرضى",
    moduleEn: "Patient messages",
    labelAr: "الرد على الرسائل",
    labelEn: "Reply to messages",
    descriptionAr: "إرسال الردود للمرضى",
  },
  "messages.manage": {
    moduleAr: "رسائل المرضى",
    moduleEn: "Patient messages",
    labelAr: "إدارة كل الرسائل",
    labelEn: "Manage all messages",
    descriptionAr: "إدارة محادثات المرضى وحالاتها",
    risk: "sensitive",
  },
  "reports.feedback.view": {
    moduleAr: "التقارير",
    moduleEn: "Reports",
    labelAr: "عرض تقييمات المرضى",
    labelEn: "View patient feedback",
    descriptionAr: "عرض التقييمات والتعليقات الواردة من التطبيق",
    risk: "sensitive",
  },
  "loyalty.view": {
    moduleAr: "الولاء والنقاط",
    moduleEn: "Loyalty",
    labelAr: "عرض الأرصدة والنقاط",
    labelEn: "View balances and points",
    descriptionAr: "عرض رصيد المحفظة ونقاط الولاء للمرضى",
    risk: "sensitive",
  },
  "accounting.view": {
    moduleAr: "المحاسبة",
    moduleEn: "Accounting",
    labelAr: "عرض المحاسبة",
    labelEn: "View accounting",
    descriptionAr: "عرض دليل الحسابات والقيود وكشوف الحساب",
    risk: "sensitive",
  },
  "accounting.manage": {
    moduleAr: "المحاسبة",
    moduleEn: "Accounting",
    labelAr: "إدارة المحاسبة",
    labelEn: "Manage accounting",
    descriptionAr: "إنشاء القيود والترحيل والتسويات المحاسبية",
    risk: "critical",
  },
  "expenses.view": {
    moduleAr: "المصروفات",
    moduleEn: "Expenses",
    labelAr: "عرض المصروفات",
    labelEn: "View expenses",
    descriptionAr: "عرض المصروفات والمستحقات والموردين",
    risk: "sensitive",
  },
  "expenses.create": {
    moduleAr: "المصروفات",
    moduleEn: "Expenses",
    labelAr: "إضافة مصروف",
    labelEn: "Create expenses",
    descriptionAr: "تسجيل مصروف أو التزام جديد",
    risk: "critical",
  },
  "expenses.pay": {
    moduleAr: "المصروفات",
    moduleEn: "Expenses",
    labelAr: "دفع المصروفات",
    labelEn: "Pay expenses",
    descriptionAr: "اعتماد دفع المصروف وتسجيل وسيلة السداد",
    risk: "critical",
  },
  "incomes.view": {
    moduleAr: "الإيرادات",
    moduleEn: "Income",
    labelAr: "عرض الإيرادات",
    labelEn: "View income",
    descriptionAr: "عرض الإيرادات والتحصيلات ومصادرها",
    risk: "sensitive",
  },
  "incomes.create": {
    moduleAr: "الإيرادات",
    moduleEn: "Income",
    labelAr: "تسجيل إيراد",
    labelEn: "Create income",
    descriptionAr: "تسجيل إيراد أو تحصيل جديد",
    risk: "critical",
  },
  "expenses.manage": {
    moduleAr: "المصروفات",
    moduleEn: "Expenses",
    labelAr: "إدارة المصروفات بالكامل",
    labelEn: "Manage expenses",
    descriptionAr: "إضافة المصروفات وتعديلها واعتماد سدادها وإدارة الموردين",
    risk: "critical",
  },
  "customers.archive": { moduleAr:"المرضى",moduleEn:"Patients",labelAr:"أرشفة المرضى",labelEn:"Archive patients",descriptionAr:"إيقاف ملف المريض ونقله إلى الأرشيف",risk:"critical" },
  "customers.restore": { moduleAr:"المرضى",moduleEn:"Patients",labelAr:"استعادة المرضى",labelEn:"Restore patients",descriptionAr:"إعادة تنشيط ملف مريض مؤرشف",risk:"critical" },
  "settings.recurring_expenses.view": {
    moduleAr: "الإعدادات",
    moduleEn: "Settings",
    labelAr: "عرض المصروفات الشهرية",
    labelEn: "View recurring expenses",
    descriptionAr: "عرض بنود الإيجار والرواتب والاشتراكات الشهرية المجدولة",
    risk: "sensitive",
  },
  "settings.recurring_expenses.manage": {
    moduleAr: "الإعدادات",
    moduleEn: "Settings",
    labelAr: "إدارة المصروفات الشهرية",
    labelEn: "Manage recurring expenses",
    descriptionAr: "إنشاء البنود الشهرية وترحيلها تلقائيًا إلى مركز المصروفات",
    risk: "critical",
  },
  "incomes.manage": {
    moduleAr: "الإيرادات",
    moduleEn: "Income",
    labelAr: "إدارة سجل الإيرادات بالكامل",
    labelEn: "Manage income register",
    descriptionAr: "إضافة الإيرادات وتعديل مصادرها وربطها بالخزينة والطبيب",
    risk: "critical",
  },
});

Object.assign(permissionMeta, {
  "dashboard.appointments.view": { moduleAr:"لوحة التحكم", moduleEn:"Dashboard", labelAr:"عرض مساحة المواعيد", labelEn:"View appointment workspace", descriptionAr:"إظهار قائمة المواعيد وتفاصيلها في الصفحة الرئيسية" },
  "dashboard.invoices.view": { moduleAr:"لوحة التحكم", moduleEn:"Dashboard", labelAr:"عرض مساحة الفواتير", labelEn:"View invoice workspace", descriptionAr:"إظهار الفواتير المطلوبة للدفع في الصفحة الرئيسية", risk:"sensitive" },
  "dashboard.summary.view": { moduleAr:"لوحة التحكم", moduleEn:"Dashboard", labelAr:"عرض الملخص التشغيلي", labelEn:"View operational summary", descriptionAr:"إظهار تبويب الملخص والمؤشرات التشغيلية" },
  "customers.contact.view": { moduleAr:"المرضى", moduleEn:"Patients", labelAr:"عرض بيانات التواصل", labelEn:"View contact details", descriptionAr:"عرض الهاتف والبريد والعنوان", risk:"sensitive" },
  "customers.financial.view": { moduleAr:"المرضى", moduleEn:"Patients", labelAr:"عرض بيانات المريض المالية", labelEn:"View patient financials", descriptionAr:"عرض الرصيد والفواتير والمدفوعات", risk:"sensitive" },
  "customers.tags.manage": { moduleAr:"المرضى", moduleEn:"Patients", labelAr:"إدارة علامات المريض", labelEn:"Manage patient tags", descriptionAr:"إضافة وإزالة علامات المريض" },
  "customers.referrals.manage": { moduleAr:"المرضى", moduleEn:"Patients", labelAr:"إدارة إحالة المريض", labelEn:"Manage patient referral", descriptionAr:"تحديد وتعديل مصدر الإحالة" },
  "customers.balance.manage": { moduleAr:"المرضى", moduleEn:"Patients", labelAr:"إدارة رصيد المريض", labelEn:"Manage patient balance", descriptionAr:"إضافة أو خصم رصيد محفظة المريض", risk:"critical" },
  "appointments.status.update": { moduleAr:"المواعيد", moduleEn:"Appointments", labelAr:"تغيير حالة الموعد", labelEn:"Update appointment status", descriptionAr:"تغيير الحالة التشغيلية للموعد" },
  "appointments.confirm": { moduleAr:"المواعيد", moduleEn:"Appointments", labelAr:"تأكيد الموعد", labelEn:"Confirm appointment", descriptionAr:"تأكيد المواعيد المحجوزة" },
  "appointments.check_in": { moduleAr:"المواعيد", moduleEn:"Appointments", labelAr:"تسجيل وصول المريض", labelEn:"Check in patient", descriptionAr:"تسجيل وصول المريض للموعد" },
  "appointments.assign_staff": { moduleAr:"المواعيد", moduleEn:"Appointments", labelAr:"إسناد الطبيب أو القسم", labelEn:"Assign doctor or department", descriptionAr:"تغيير مقدم الخدمة المسؤول عن الموعد" },
  "payments.invoice.create": { moduleAr:"المدفوعات", moduleEn:"Finance", labelAr:"إصدار فاتورة", labelEn:"Issue invoices", descriptionAr:"إنشاء وإصدار فاتورة للمريض", risk:"critical" },
  "payments.split.create": { moduleAr:"المدفوعات", moduleEn:"Finance", labelAr:"تسجيل دفع مختلط", labelEn:"Create split payments", descriptionAr:"تقسيم التحصيل بين النقد والبنك والوسائل الأخرى", risk:"critical" },
  "payments.void": { moduleAr:"المدفوعات", moduleEn:"Finance", labelAr:"إلغاء قيد مالي", labelEn:"Void financial records", descriptionAr:"إلغاء فاتورة أو دفعة مع تسجيل العملية", risk:"critical" },
  "services.create": { moduleAr:"الخدمات والأسعار", moduleEn:"Services & prices", labelAr:"إضافة خدمة", labelEn:"Create services", descriptionAr:"إنشاء خدمة أو خيار علاجي" },
  "services.edit": { moduleAr:"الخدمات والأسعار", moduleEn:"Services & prices", labelAr:"تعديل خدمة", labelEn:"Edit services", descriptionAr:"تعديل بيانات الخدمة" },
  "services.prices.manage": { moduleAr:"الخدمات والأسعار", moduleEn:"Services & prices", labelAr:"إدارة الأسعار", labelEn:"Manage prices", descriptionAr:"تعديل الأسعار ومجموعات الأسعار", risk:"critical" },
  "inventory.products.manage": { moduleAr:"المخزون", moduleEn:"Inventory", labelAr:"إدارة المنتجات", labelEn:"Manage products", descriptionAr:"إضافة وتعديل منتجات المخزون" },
  "inventory.stock.adjust": { moduleAr:"المخزون", moduleEn:"Inventory", labelAr:"تعديل رصيد المخزون", labelEn:"Adjust stock", descriptionAr:"تسجيل الحركات والتسويات المخزنية", risk:"critical" },
  "inventory.suppliers.manage": { moduleAr:"المخزون", moduleEn:"Inventory", labelAr:"إدارة الموردين", labelEn:"Manage suppliers", descriptionAr:"إضافة وتعديل الموردين" },
  "inventory.purchase_orders.manage": { moduleAr:"المخزون", moduleEn:"Inventory", labelAr:"إدارة أوامر الشراء", labelEn:"Manage purchase orders", descriptionAr:"إنشاء واستلام أوامر الشراء", risk:"critical" },
  "staff.create": { moduleAr:"الفريق", moduleEn:"Staff", labelAr:"إضافة موظف", labelEn:"Create staff", descriptionAr:"إنشاء سجل موظف جديد" },
  "staff.edit": { moduleAr:"الفريق", moduleEn:"Staff", labelAr:"تعديل موظف", labelEn:"Edit staff", descriptionAr:"تعديل بيانات الموظف" },
  "staff.status.manage": { moduleAr:"الفريق", moduleEn:"Staff", labelAr:"تفعيل وإيقاف الموظف", labelEn:"Manage staff status", descriptionAr:"تفعيل أو إيقاف حساب الموظف", risk:"critical" },
  "accounting.chart.manage": { moduleAr:"المحاسبة", moduleEn:"Accounting", labelAr:"إدارة دليل الحسابات", labelEn:"Manage chart of accounts", descriptionAr:"إضافة وتعديل الحسابات", risk:"critical" },
  "accounting.journal.manage": { moduleAr:"المحاسبة", moduleEn:"Accounting", labelAr:"إدارة القيود اليومية", labelEn:"Manage journal entries", descriptionAr:"إنشاء وترحيل القيود", risk:"critical" },
  "accounting.bank.view": { moduleAr:"المحاسبة", moduleEn:"Accounting", labelAr:"عرض حركات البنك", labelEn:"View bank transactions", descriptionAr:"عرض حساب البنك والتسويات", risk:"sensitive" },
  "accounting.bank.manage": { moduleAr:"المحاسبة", moduleEn:"Accounting", labelAr:"إدارة حركات البنك", labelEn:"Manage bank transactions", descriptionAr:"ترحيل وتسوية حركات البنك", risk:"critical" },
  "accounting.statements.view": { moduleAr:"المحاسبة", moduleEn:"Accounting", labelAr:"عرض كشوف الحساب", labelEn:"View account statements", descriptionAr:"عرض كشوف الأستاذ والحسابات", risk:"sensitive" },
  "reports.automation.view": { moduleAr:"التقارير", moduleEn:"Reports", labelAr:"عرض التقارير التلقائية", labelEn:"View automated reports", descriptionAr:"معاينة تقارير الإدارة المجدولة", risk:"sensitive" },
  "reports.automation.manage": { moduleAr:"التقارير", moduleEn:"Reports", labelAr:"إدارة التقارير التلقائية", labelEn:"Manage automated reports", descriptionAr:"إعداد وإرسال تقارير الإدارة المجدولة", risk:"critical" },
} satisfies Record<string, PermissionMeta>);

export const permissionModuleOrder = [
  "Dashboard",
  "Patients",
  "Patient app",
  "Appointments",
  "Follow-ups",
  "Treatments",
  "Medical record",
  "Finance",
  "Accounting",
  "Expenses",
  "Income",
  "Reports",
  "Loyalty",
  "Services & prices",
  "Inventory",
  "Staff",
  "Marketing",
  "Tasks",
  "Patient messages",
  "Branches",
  "Panthera intelligence",
  "Support",
  "Enterprise",
  "Settings",
];
