begin;

create table if not exists public.patient_appointment_payments (
  id bigint generated by default as identity primary key,
  appointment_id bigint not null unique references public.appointments(id) on delete cascade,
  customer_id bigint not null references public.customers(id) on delete cascade,
  payment_method text not null check(payment_method in('pay_at_clinic','online')),
  payment_status text not null default 'pending' check(payment_status in('pending','processing','paid','failed','cancelled')),
  quoted_amount numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.patient_appointment_payments enable row level security;
drop policy if exists patient_appointment_payment_self on public.patient_appointment_payments;
create policy patient_appointment_payment_self on public.patient_appointment_payments for select to authenticated
using(customer_id=public.current_patient_customer_id());

create or replace function public.patient_booking_providers()
returns table(id bigint,name text,role text)
language sql stable security definer set search_path=public as $$
  select distinct st.id,st.staff_name,coalesce(st.role,'doctor')
  from public.staff st
  join public.staff_services ss on ss.staff_id=st.id and ss.is_active
  where st.is_active and lower(coalesce(st.role,''))='doctor'
    and exists(select 1 from public.staff_working_hours wh where wh.staff_id=st.id and wh.is_working)
  order by st.staff_name
$$;

create or replace function public.patient_provider_services(p_provider_id bigint)
returns table(id bigint,name text,category text,duration_minutes integer,provider_type text,price_from numeric,is_starting_from boolean)
language sql stable security definer set search_path=public as $$
  select s.id,s.name,s.category,s.duration_minutes,s.provider_type,
    min(svp.price) filter(where svp.is_active) as price_from,
    coalesce(bool_or(svp.is_starting_from) filter(where svp.is_active),false) as is_starting_from
  from public.staff_services ss
  join public.services s on s.id=ss.service_id and s.is_active
  left join public.service_variants sv on sv.service_id=s.id and sv.is_active
  left join public.service_variant_prices svp on svp.service_variant_id=sv.id and svp.staff_id=ss.staff_id and svp.is_active
  where ss.staff_id=p_provider_id and ss.is_active
  group by s.id,s.name,s.category,s.duration_minutes,s.provider_type
  order by s.category,s.name
$$;

create or replace function public.patient_book_appointment(p_service_id bigint,p_appointment_at timestamptz,p_notes text default null,p_doctor_id bigint default null)
returns bigint language plpgsql security definer set search_path=public as $$
declare c public.customers%rowtype;v_room_id bigint;v_id bigint;v_duration integer;
begin
  select * into c from public.customers where id=public.current_patient_customer_id();
  if c.id is null then raise exception 'Patient account is not linked'; end if;
  if p_doctor_id is null then raise exception 'Please select a doctor'; end if;
  if p_appointment_at<=now() then raise exception 'Appointment must be in the future'; end if;
  if not exists(select 1 from public.staff_services ss join public.staff st on st.id=ss.staff_id where ss.staff_id=p_doctor_id and ss.service_id=p_service_id and ss.is_active and st.is_active and lower(coalesce(st.role,''))='doctor') then raise exception 'The selected doctor does not provide this service'; end if;
  select duration_minutes into v_duration from public.services where id=p_service_id and is_active;
  if v_duration is null then raise exception 'Service is not available'; end if;
  if not exists(select 1 from public.staff_working_hours wh where wh.staff_id=p_doctor_id and wh.is_working and wh.weekday=extract(dow from p_appointment_at at time zone 'Asia/Riyadh')::integer and (p_appointment_at at time zone 'Asia/Riyadh')::time>=wh.start_time and (p_appointment_at at time zone 'Asia/Riyadh')::time+v_duration*interval '1 minute'<=wh.end_time) then raise exception 'Doctor is not working at this time'; end if;
  select sr.room_id into v_room_id from public.staff_rooms sr
  where sr.staff_id=p_doctor_id and not exists(select 1 from public.appointments a join public.services s on s.id=a.service_id where a.room_id=sr.room_id and coalesce(a.status,'') not in('cancelled','no_show') and p_appointment_at<a.appointment_at+s.duration_minutes*interval '1 minute' and a.appointment_at<p_appointment_at+v_duration*interval '1 minute') order by sr.room_id limit 1;
  if v_room_id is null then raise exception 'No room is available at this time'; end if;
  if exists(select 1 from public.appointments a join public.services s on s.id=a.service_id where a.doctor_id=p_doctor_id and coalesce(a.status,'') not in('cancelled','no_show') and p_appointment_at<a.appointment_at+s.duration_minutes*interval '1 minute' and a.appointment_at<p_appointment_at+v_duration*interval '1 minute') then raise exception 'Doctor is already booked at this time'; end if;
  insert into public.appointments(customer_id,clinic_id,branch_id,service_id,doctor_id,room_id,appointment_at,status,notes,source,created_from_channel)
  values(c.id,c.clinic_id,c.branch_id,p_service_id,p_doctor_id,v_room_id,p_appointment_at,'requested',p_notes,'patient_app','mobile') returning id into v_id;
  insert into public.patient_notifications(customer_id,title,message,notification_type) values(c.id,'Appointment requested','Your appointment request was sent to Panthera Clinics.','appointment');
  return v_id;
end $$;

create or replace function public.patient_select_payment_method(p_appointment_id bigint,p_payment_method text,p_quoted_amount numeric default null)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_customer_id bigint:=public.current_patient_customer_id();v_id bigint;
begin
  if p_payment_method not in('pay_at_clinic','online') then raise exception 'Invalid payment method'; end if;
  if not exists(select 1 from public.appointments where id=p_appointment_id and customer_id=v_customer_id) then raise exception 'Appointment not found'; end if;
  insert into public.patient_appointment_payments(appointment_id,customer_id,payment_method,payment_status,quoted_amount)
  values(p_appointment_id,v_customer_id,p_payment_method,case when p_payment_method='online' then 'processing' else 'pending' end,p_quoted_amount)
  on conflict(appointment_id) do update set payment_method=excluded.payment_method,payment_status=excluded.payment_status,quoted_amount=excluded.quoted_amount,updated_at=now()
  returning id into v_id;return v_id;
end $$;

revoke all on function public.patient_booking_providers() from public;
revoke all on function public.patient_provider_services(bigint) from public;
revoke all on function public.patient_book_appointment(bigint,timestamptz,text,bigint) from public;
revoke all on function public.patient_select_payment_method(bigint,text,numeric) from public;
grant execute on function public.patient_booking_providers() to authenticated;
grant execute on function public.patient_provider_services(bigint) to authenticated;
grant execute on function public.patient_book_appointment(bigint,timestamptz,text,bigint) to authenticated;
grant execute on function public.patient_select_payment_method(bigint,text,numeric) to authenticated;

commit;
