-- Zernio Phase 7 Marketing OS. Safe to run more than once.
begin;
set local lock_timeout='20s';

create table if not exists public.marketing_campaigns(
 id bigint generated by default as identity primary key,
 clinic_id bigint not null references public.clinics(id) on delete cascade,
 branch_id bigint not null references public.branches(id) on delete restrict,
 name text not null,
 channel text not null check(channel in ('whatsapp','instagram','tiktok','google','sms','email','other')),
 status text not null default 'draft' check(status in ('draft','scheduled','active','paused','completed','cancelled')),
 objective text,
 budget numeric not null default 0 check(budget>=0),
 spend numeric not null default 0 check(spend>=0),
 start_date date,
 end_date date,
 audience_segment text,
 offer_text text,
 created_at timestamptz not null default now(),
 unique(clinic_id,branch_id,name)
);

create table if not exists public.marketing_leads(
 id bigint generated by default as identity primary key,
 clinic_id bigint not null references public.clinics(id) on delete cascade,
 branch_id bigint not null references public.branches(id) on delete restrict,
 campaign_id bigint references public.marketing_campaigns(id) on delete set null,
 source text not null,
 full_name text,
 phone text,
 email text,
 status text not null default 'new' check(status in ('new','contacted','qualified','booked','converted','lost')),
 interested_service text,
 customer_id bigint references public.customers(id) on delete set null,
 appointment_id bigint references public.appointments(id) on delete set null,
 assigned_to bigint references public.staff(id) on delete set null,
 notes text,
 created_at timestamptz not null default now(),
 converted_at timestamptz
);

create table if not exists public.marketing_messages(
 id bigint generated by default as identity primary key,
 clinic_id bigint not null references public.clinics(id) on delete cascade,
 branch_id bigint not null references public.branches(id) on delete restrict,
 campaign_id bigint references public.marketing_campaigns(id) on delete cascade,
 lead_id bigint references public.marketing_leads(id) on delete cascade,
 customer_id bigint references public.customers(id) on delete cascade,
 channel text not null check(channel in ('whatsapp','instagram','tiktok','google','sms','email','other')),
 direction text not null default 'outbound' check(direction in ('outbound','inbound')),
 recipient text,
 message_text text not null,
 ai_generated boolean not null default false,
 status text not null default 'draft' check(status in ('draft','queued','sent','delivered','read','failed','replied')),
 scheduled_at timestamptz,
 sent_at timestamptz,
 created_at timestamptz not null default now()
);

create table if not exists public.marketing_source_costs(
 id bigint generated by default as identity primary key,
 clinic_id bigint not null references public.clinics(id) on delete cascade,
 branch_id bigint not null references public.branches(id) on delete restrict,
 source text not null,
 period_month date not null,
 spend numeric not null default 0 check(spend>=0),
 impressions bigint not null default 0,
 clicks bigint not null default 0,
 created_at timestamptz not null default now(),
 unique(clinic_id,branch_id,source,period_month)
);

create or replace function public.sync_marketing_lead_conversion() returns trigger language plpgsql set search_path=public as $$
begin
 if new.appointment_id is not null and new.status in ('new','contacted','qualified') then new.status:='booked'; end if;
 if new.customer_id is not null and new.appointment_id is not null and new.status<>'lost' then new.status:='converted'; end if;
 if new.status='converted' then
  if tg_op='INSERT' then new.converted_at:=coalesce(new.converted_at,now());
  elsif old.status is distinct from 'converted' then new.converted_at:=now(); end if;
 end if;
 return new;
end $$;
drop trigger if exists marketing_lead_conversion_trigger on public.marketing_leads;
create trigger marketing_lead_conversion_trigger before insert or update on public.marketing_leads for each row execute function public.sync_marketing_lead_conversion();

alter table public.marketing_campaigns enable row level security;
alter table public.marketing_leads enable row level security;
alter table public.marketing_messages enable row level security;
alter table public.marketing_source_costs enable row level security;
do $$ declare t text; begin foreach t in array array['marketing_campaigns','marketing_leads','marketing_messages','marketing_source_costs'] loop
 execute format('drop policy if exists "Authenticated users manage %1$s" on public.%1$I',t);
 execute format('create policy "Authenticated users manage %1$s" on public.%1$I for all to authenticated using(true) with check(true)',t);
end loop; end $$;

create index if not exists marketing_campaign_scope_idx on public.marketing_campaigns(clinic_id,branch_id,status);
create index if not exists marketing_lead_scope_idx on public.marketing_leads(clinic_id,branch_id,status,source);
create index if not exists marketing_message_queue_idx on public.marketing_messages(clinic_id,branch_id,status,scheduled_at);

insert into public.hr_permissions(code,name,module)
values('marketing.manage','Manage campaigns and leads','Marketing')
on conflict(code) do update set name=excluded.name,module=excluded.module;

insert into public.hr_role_permissions(role_id,permission_id)
select r.id,p.id from public.hr_roles r cross join public.hr_permissions p
where p.code='marketing.manage' and r.name in ('Admin','Coordinator','Reception')
on conflict do nothing;
commit;
select 'marketing_phase7_ready' as status;
