begin;

create table if not exists public.patient_appointment_requests (
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.clinics(id) on delete restrict,
  branch_id bigint not null references public.branches(id) on delete restrict,
  customer_id bigint not null references public.customers(id) on delete cascade,
  appointment_id bigint not null references public.appointments(id) on delete cascade,
  request_type text not null check(request_type in('reschedule','cancel','check_in','add_to_calendar')),
  preferred_at timestamptz,
  reason text,
  status text not null default 'pending' check(status in('pending','reviewing','approved','declined','completed')),
  handled_by bigint references public.staff(id) on delete set null,
  handled_at timestamptz,
  created_at timestamptz not null default now()
);
create unique index if not exists patient_open_appointment_request_unique on public.patient_appointment_requests(appointment_id,request_type) where status in('pending','reviewing');

create table if not exists public.patient_consents (
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.clinics(id) on delete restrict,
  customer_id bigint not null references public.customers(id) on delete cascade,
  appointment_id bigint references public.appointments(id) on delete cascade,
  consent_type text not null,
  title text not null,
  body text not null,
  version text not null default '1',
  status text not null default 'pending' check(status in('pending','accepted','declined','expired')),
  accepted_name text,
  accepted_at timestamptz,
  created_at timestamptz not null default now(),
  unique(customer_id,appointment_id,consent_type,version)
);

create table if not exists public.patient_messages (
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.clinics(id) on delete restrict,
  branch_id bigint references public.branches(id) on delete restrict,
  customer_id bigint not null references public.customers(id) on delete cascade,
  appointment_id bigint references public.appointments(id) on delete set null,
  sender_type text not null check(sender_type in('patient','staff','system','ai_draft')),
  sender_staff_id bigint references public.staff(id) on delete set null,
  message text not null check(length(trim(message)) between 1 and 2000),
  category text not null default 'general' check(category in('general','booking','payment','aftercare','medical','complaint')),
  requires_reply boolean not null default false,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists patient_messages_customer_idx on public.patient_messages(customer_id,created_at desc);

create table if not exists public.patient_packages (
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.clinics(id) on delete restrict,
  customer_id bigint not null references public.customers(id) on delete cascade,
  service_id bigint references public.services(id) on delete set null,
  package_name text not null,
  total_sessions integer not null check(total_sessions>0),
  used_sessions integer not null default 0 check(used_sessions>=0 and used_sessions<=total_sessions),
  amount_paid numeric not null default 0 check(amount_paid>=0),
  status text not null default 'active' check(status in('active','completed','expired','cancelled')),
  starts_at date not null default current_date,
  expires_at date,
  created_at timestamptz not null default now()
);

create table if not exists public.patient_push_tokens (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  customer_id bigint not null references public.customers(id) on delete cascade,
  expo_push_token text not null unique,
  platform text check(platform in('ios','android','web')),
  is_active boolean not null default true,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.patient_automation_suggestions (
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.clinics(id) on delete restrict,
  branch_id bigint references public.branches(id) on delete restrict,
  customer_id bigint not null references public.customers(id) on delete cascade,
  appointment_id bigint references public.appointments(id) on delete cascade,
  suggestion_type text not null check(suggestion_type in('confirmation','followup','aftercare','payment','retention','complaint')),
  title text not null,
  suggested_action text not null,
  priority text not null default 'medium' check(priority in('low','medium','high','urgent')),
  status text not null default 'open' check(status in('open','approved','dismissed','completed')),
  generated_by text not null default 'rules' check(generated_by in('rules','ai')),
  reviewed_by bigint references public.staff(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);
create unique index if not exists patient_open_suggestion_unique on public.patient_automation_suggestions(customer_id,appointment_id,suggestion_type) where status='open';

do $$ declare v_table text; begin
  foreach v_table in array array['patient_appointment_requests','patient_consents','patient_messages','patient_packages','patient_push_tokens','patient_automation_suggestions'] loop
    execute format('alter table public.%I enable row level security',v_table);
  end loop;
end $$;

drop policy if exists patient_requests_access on public.patient_appointment_requests;
create policy patient_requests_access on public.patient_appointment_requests for select to authenticated using(public.current_staff_id() is not null or customer_id=public.current_patient_customer_id());
drop policy if exists patient_requests_staff_manage on public.patient_appointment_requests;
create policy patient_requests_staff_manage on public.patient_appointment_requests for update to authenticated using(public.current_staff_id() is not null) with check(public.current_staff_id() is not null);
drop policy if exists patient_consents_access on public.patient_consents;
create policy patient_consents_access on public.patient_consents for select to authenticated using(public.current_staff_id() is not null or customer_id=public.current_patient_customer_id());
drop policy if exists patient_consents_staff_manage on public.patient_consents;
create policy patient_consents_staff_manage on public.patient_consents for all to authenticated using(public.current_staff_id() is not null) with check(public.current_staff_id() is not null);
drop policy if exists patient_messages_access on public.patient_messages;
create policy patient_messages_access on public.patient_messages for select to authenticated using(public.current_staff_id() is not null or customer_id=public.current_patient_customer_id());
drop policy if exists patient_messages_staff_manage on public.patient_messages;
create policy patient_messages_staff_manage on public.patient_messages for all to authenticated using(public.current_staff_id() is not null) with check(public.current_staff_id() is not null);
drop policy if exists patient_packages_access on public.patient_packages;
create policy patient_packages_access on public.patient_packages for select to authenticated using(public.current_staff_id() is not null or customer_id=public.current_patient_customer_id());
drop policy if exists patient_packages_staff_manage on public.patient_packages;
create policy patient_packages_staff_manage on public.patient_packages for all to authenticated using(public.current_staff_id() is not null) with check(public.current_staff_id() is not null);
drop policy if exists patient_push_self on public.patient_push_tokens;
create policy patient_push_self on public.patient_push_tokens for select to authenticated using(auth_user_id=auth.uid());
drop policy if exists patient_suggestions_staff on public.patient_automation_suggestions;
create policy patient_suggestions_staff on public.patient_automation_suggestions for all to authenticated using(public.current_staff_id() is not null) with check(public.current_staff_id() is not null);

create or replace function public.patient_concierge_hub()
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_customer_id bigint:=public.current_patient_customer_id();
begin
  if v_customer_id is null then raise exception 'Patient account is not linked'; end if;
  return jsonb_build_object(
    'requests',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'appointmentId',r.appointment_id,'type',r.request_type,'preferredAt',r.preferred_at,'reason',r.reason,'status',r.status,'createdAt',r.created_at) order by r.created_at desc) from patient_appointment_requests r where r.customer_id=v_customer_id),'[]'::jsonb),
    'consents',coalesce((select jsonb_agg(jsonb_build_object('id',c.id,'appointmentId',c.appointment_id,'type',c.consent_type,'title',c.title,'body',c.body,'version',c.version,'status',c.status,'acceptedAt',c.accepted_at) order by c.created_at desc) from patient_consents c where c.customer_id=v_customer_id),'[]'::jsonb),
    'messages',coalesce((select jsonb_agg(jsonb_build_object('id',m.id,'appointmentId',m.appointment_id,'sender',m.sender_type,'message',m.message,'category',m.category,'requiresReply',m.requires_reply,'isRead',m.is_read,'createdAt',m.created_at) order by m.created_at desc) from patient_messages m where m.customer_id=v_customer_id),'[]'::jsonb),
    'packages',coalesce((select jsonb_agg(jsonb_build_object('id',p.id,'name',p.package_name,'totalSessions',p.total_sessions,'usedSessions',p.used_sessions,'amountPaid',p.amount_paid,'status',p.status,'startsAt',p.starts_at,'expiresAt',p.expires_at,'service',s.name) order by p.created_at desc) from patient_packages p left join services s on s.id=p.service_id where p.customer_id=v_customer_id),'[]'::jsonb),
    'upcomingAppointments',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'date',a.appointment_at,'status',a.status,'service',s.name,'provider',st.staff_name) order by a.appointment_at) from appointments a left join services s on s.id=a.service_id left join staff st on st.id=a.doctor_id where a.customer_id=v_customer_id and a.appointment_at>=now() and lower(coalesce(a.status,'')) not in('cancelled','canceled','completed','no_show')),'[]'::jsonb)
  );
end;$$;

create or replace function public.patient_request_appointment_action(p_appointment_id bigint,p_action text,p_preferred_at timestamptz default null,p_reason text default null)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_customer_id bigint:=public.current_patient_customer_id();v_a appointments%rowtype;v_id bigint;
begin
  if p_action not in('reschedule','cancel','check_in','add_to_calendar') then raise exception 'Unsupported appointment action'; end if;
  select * into v_a from appointments where id=p_appointment_id and customer_id=v_customer_id and appointment_at>=now()-interval '4 hours' and lower(coalesce(status,'')) not in('cancelled','canceled','completed','no_show');
  if not found then raise exception 'Appointment is unavailable for this action'; end if;
  if p_action='reschedule' and p_preferred_at is null then raise exception 'Preferred date is required'; end if;
  insert into patient_appointment_requests(clinic_id,branch_id,customer_id,appointment_id,request_type,preferred_at,reason)
  values(v_a.clinic_id,v_a.branch_id,v_customer_id,v_a.id,p_action,p_preferred_at,nullif(trim(coalesce(p_reason,'')),'')) returning id into v_id;
  insert into patient_automation_suggestions(clinic_id,branch_id,customer_id,appointment_id,suggestion_type,title,suggested_action,priority)
  values(v_a.clinic_id,v_a.branch_id,v_customer_id,v_a.id,case when p_action='check_in' then 'confirmation' else 'followup' end,'Patient requested '||replace(p_action,'_',' '),'Review and process the patient request.',case when p_action='check_in' then 'high' else 'medium' end)
  on conflict do nothing;
  return v_id;
end;$$;

create or replace function public.patient_accept_consent(p_consent_id bigint,p_name text)
returns void language plpgsql security definer set search_path=public as $$
declare v_customer_id bigint:=public.current_patient_customer_id();
begin
  if length(trim(coalesce(p_name,'')))<2 then raise exception 'Full name is required'; end if;
  update patient_consents set status='accepted',accepted_name=trim(p_name),accepted_at=now() where id=p_consent_id and customer_id=v_customer_id and status='pending';
  if not found then raise exception 'Consent is unavailable'; end if;
end;$$;

create or replace function public.patient_send_message(p_message text,p_category text default 'general',p_appointment_id bigint default null)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_customer_id bigint:=public.current_patient_customer_id();v_clinic_id bigint;v_branch_id bigint;v_id bigint;
begin
  if p_category not in('general','booking','payment','aftercare','medical','complaint') then raise exception 'Invalid message category'; end if;
  if length(trim(coalesce(p_message,''))) not between 1 and 2000 then raise exception 'Message is empty or too long'; end if;
  select clinic_id,branch_id into v_clinic_id,v_branch_id from customers where id=v_customer_id;
  if p_appointment_id is not null and not exists(select 1 from appointments where id=p_appointment_id and customer_id=v_customer_id) then raise exception 'Invalid appointment'; end if;
  insert into patient_messages(clinic_id,branch_id,customer_id,appointment_id,sender_type,message,category,requires_reply)
  values(v_clinic_id,v_branch_id,v_customer_id,p_appointment_id,'patient',trim(p_message),p_category,true) returning id into v_id;
  insert into patient_automation_suggestions(clinic_id,branch_id,customer_id,appointment_id,suggestion_type,title,suggested_action,priority)
  values(v_clinic_id,v_branch_id,v_customer_id,p_appointment_id,case when p_category='complaint' then 'complaint' else 'followup' end,'New patient message','Review the message and prepare a response.',case when p_category in('complaint','medical') then 'high' else 'medium' end)
  on conflict do nothing;
  return v_id;
end;$$;

create or replace function public.patient_register_push_token(p_token text,p_platform text)
returns void language plpgsql security definer set search_path=public as $$
declare v_customer_id bigint:=public.current_patient_customer_id();
begin
  if auth.uid() is null or v_customer_id is null then raise exception 'Authentication required'; end if;
  if p_platform not in('ios','android','web') then raise exception 'Invalid platform'; end if;
  insert into patient_push_tokens(auth_user_id,customer_id,expo_push_token,platform) values(auth.uid(),v_customer_id,p_token,p_platform)
  on conflict(expo_push_token) do update set auth_user_id=excluded.auth_user_id,customer_id=excluded.customer_id,platform=excluded.platform,is_active=true,last_seen_at=now();
end;$$;

create or replace function public.staff_process_patient_request(p_request_id bigint,p_decision text,p_note text default null)
returns void language plpgsql security definer set search_path=public as $$
declare v_staff_id bigint:=public.current_staff_id();v_request patient_appointment_requests%rowtype;
begin
  if v_staff_id is null then raise exception 'Staff access required'; end if;
  if p_decision not in('approve','decline') then raise exception 'Invalid decision'; end if;
  select * into v_request from patient_appointment_requests where id=p_request_id and status in('pending','reviewing') for update;
  if not found then raise exception 'Request was already handled'; end if;
  if p_decision='approve' then
    if v_request.request_type='cancel' then update appointments set status='cancelled' where id=v_request.appointment_id;
    elsif v_request.request_type='check_in' then update appointments set status='arrived' where id=v_request.appointment_id;
    elsif v_request.request_type='reschedule' then update appointments set appointment_at=v_request.preferred_at,status='booked' where id=v_request.appointment_id;
    end if;
  end if;
  update patient_appointment_requests set status=case when p_decision='approve' then 'completed' else 'declined' end,handled_by=v_staff_id,handled_at=now(),reason=concat_ws(E'\n',reason,nullif(trim(coalesce(p_note,'')),'')) where id=v_request.id;
  update patient_automation_suggestions set status=case when p_decision='approve' then 'completed' else 'dismissed' end,reviewed_by=v_staff_id,reviewed_at=now() where appointment_id=v_request.appointment_id and status='open';
end;$$;

create or replace function public.staff_reply_to_patient(p_customer_id bigint,p_message text,p_category text default 'general',p_appointment_id bigint default null)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_staff_id bigint:=public.current_staff_id();v_clinic_id bigint;v_branch_id bigint;v_id bigint;
begin
  if v_staff_id is null then raise exception 'Staff access required'; end if;
  if length(trim(coalesce(p_message,''))) not between 1 and 2000 then raise exception 'Message is empty or too long'; end if;
  select clinic_id,branch_id into v_clinic_id,v_branch_id from customers where id=p_customer_id;
  insert into patient_messages(clinic_id,branch_id,customer_id,appointment_id,sender_type,sender_staff_id,message,category)
  values(v_clinic_id,v_branch_id,p_customer_id,p_appointment_id,'staff',v_staff_id,trim(p_message),p_category) returning id into v_id;
  return v_id;
end;$$;

create or replace function public.notify_patient_concierge_change()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if tg_table_name='patient_appointment_requests' and old.status is distinct from new.status then
    perform enqueue_patient_notification(new.customer_id,'Appointment request updated','Your request is now '||new.status||'.','appointment_request',1);
  elsif tg_table_name='patient_messages' and tg_op='INSERT' and new.sender_type='staff' then
    perform enqueue_patient_notification(new.customer_id,'New message from Panthera','Your care team sent you a new message.','message',1);
  end if;
  return new;
end;$$;
drop trigger if exists patient_request_status_notify on public.patient_appointment_requests;
create trigger patient_request_status_notify after update of status on public.patient_appointment_requests for each row execute function public.notify_patient_concierge_change();
drop trigger if exists patient_staff_message_notify on public.patient_messages;
create trigger patient_staff_message_notify after insert on public.patient_messages for each row execute function public.notify_patient_concierge_change();

do $$ declare v_sig regprocedure; begin
  foreach v_sig in array array[
    'public.patient_concierge_hub()'::regprocedure,
    'public.patient_request_appointment_action(bigint,text,timestamp with time zone,text)'::regprocedure,
    'public.patient_accept_consent(bigint,text)'::regprocedure,
    'public.patient_send_message(text,text,bigint)'::regprocedure,
    'public.patient_register_push_token(text,text)'::regprocedure
    ,'public.staff_process_patient_request(bigint,text,text)'::regprocedure
    ,'public.staff_reply_to_patient(bigint,text,text,bigint)'::regprocedure
  ] loop execute format('revoke all on function %s from public',v_sig);execute format('grant execute on function %s to authenticated',v_sig); end loop;
end $$;

do $$ declare v_table text; begin
  foreach v_table in array array['patient_appointment_requests','patient_consents','patient_messages','patient_packages','patient_automation_suggestions'] loop
    if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename=v_table) then execute format('alter publication supabase_realtime add table public.%I',v_table); end if;
  end loop;
end $$;

commit;
