begin;

create table if not exists public.patient_payment_intents (
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.clinics(id) on delete restrict,
  branch_id bigint not null references public.branches(id) on delete restrict,
  customer_id bigint not null references public.customers(id) on delete cascade,
  appointment_id bigint not null references public.appointments(id) on delete cascade,
  appointment_payment_id bigint references public.patient_appointment_payments(id) on delete set null,
  provider text not null default 'moyasar' check(provider in('moyasar')),
  amount numeric not null check(amount>0),
  currency text not null default 'SAR',
  status text not null default 'created' check(status in('created','pending','paid','failed','expired','cancelled','refunded')),
  gateway_invoice_id text unique,
  checkout_url text,
  gateway_payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists patient_open_payment_intent_unique on public.patient_payment_intents(appointment_id) where status in('created','pending');
alter table public.patient_payment_intents enable row level security;
drop policy if exists patient_payment_intents_access on public.patient_payment_intents;
create policy patient_payment_intents_access on public.patient_payment_intents for select to authenticated using(public.current_staff_id() is not null or customer_id=public.current_patient_customer_id());

create or replace function public.patient_prepare_online_payment(p_appointment_id bigint)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_customer_id bigint:=public.current_patient_customer_id();v_a appointments%rowtype;v_payment patient_appointment_payments%rowtype;v_intent_id bigint;
begin
  select * into v_a from appointments where id=p_appointment_id and customer_id=v_customer_id and lower(coalesce(status,'')) not in('cancelled','canceled','completed','no_show');
  if not found then raise exception 'Appointment is unavailable for payment'; end if;
  select * into v_payment from patient_appointment_payments where appointment_id=v_a.id;
  if v_payment.id is null or v_payment.quoted_amount is null or v_payment.quoted_amount<=0 then raise exception 'Payment amount is not prepared'; end if;
  insert into patient_payment_intents(clinic_id,branch_id,customer_id,appointment_id,appointment_payment_id,amount,currency)
  values(v_a.clinic_id,v_a.branch_id,v_customer_id,v_a.id,v_payment.id,v_payment.quoted_amount,'SAR')
  on conflict(appointment_id) where status in('created','pending') do update set amount=excluded.amount,updated_at=now()
  returning id into v_intent_id;
  return jsonb_build_object('intentId',v_intent_id,'amount',v_payment.quoted_amount,'currency','SAR','description','Panthera Clinics appointment #'||v_a.id);
end;$$;

create or replace function public.patient_attach_payment_invoice(p_intent_id bigint,p_gateway_invoice_id text,p_checkout_url text)
returns void language plpgsql security definer set search_path=public as $$
begin
  update patient_payment_intents set gateway_invoice_id=p_gateway_invoice_id,checkout_url=p_checkout_url,status='pending',updated_at=now() where id=p_intent_id and customer_id=public.current_patient_customer_id() and status in('created','pending');
  if not found then raise exception 'Payment intent is unavailable'; end if;
end;$$;

revoke all on function public.patient_prepare_online_payment(bigint) from public;
revoke all on function public.patient_attach_payment_invoice(bigint,text,text) from public;
grant execute on function public.patient_prepare_online_payment(bigint) to authenticated;
grant execute on function public.patient_attach_payment_invoice(bigint,text,text) to authenticated;

commit;
