begin;

create table if not exists public.patient_push_deliveries (
  id bigint generated by default as identity primary key,
  notification_id bigint not null references public.patient_notifications(id) on delete cascade,
  customer_id bigint not null references public.customers(id) on delete cascade,
  expo_push_token text not null,
  title text not null,
  body text not null,
  status text not null default 'pending' check(status in('pending','processing','sent','failed','invalid_token')),
  attempts integer not null default 0,
  provider_ticket_id text,
  error_message text,
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  unique(notification_id,expo_push_token)
);
create index if not exists patient_push_pending_idx on public.patient_push_deliveries(status,created_at) where status in('pending','failed');
alter table public.patient_push_deliveries enable row level security;
drop policy if exists patient_push_deliveries_staff on public.patient_push_deliveries;
create policy patient_push_deliveries_staff on public.patient_push_deliveries for select to authenticated using(public.current_staff_id() is not null);

create or replace function public.queue_patient_push_notification()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into patient_push_deliveries(notification_id,customer_id,expo_push_token,title,body)
  select new.id,new.customer_id,t.expo_push_token,new.title,new.message
  from patient_push_tokens t where t.customer_id=new.customer_id and t.is_active
  on conflict(notification_id,expo_push_token) do nothing;
  return new;
end;$$;
drop trigger if exists patient_notification_queue_push on public.patient_notifications;
create trigger patient_notification_queue_push after insert on public.patient_notifications for each row execute function public.queue_patient_push_notification();

create or replace function public.generate_patient_appointment_reminders()
returns integer language plpgsql security definer set search_path=public as $$
declare v_count integer;
begin
  with due as (
    select a.customer_id,a.id,a.appointment_at,s.name service_name,
      case when a.appointment_at between now()+interval '23 hours 45 minutes' and now()+interval '24 hours 15 minutes' then 'appointment_24h' else 'appointment_2h' end reminder_type
    from appointments a left join services s on s.id=a.service_id
    where a.customer_id is not null and lower(coalesce(a.status,'')) in('requested','booked','confirmed')
      and (a.appointment_at between now()+interval '23 hours 45 minutes' and now()+interval '24 hours 15 minutes' or a.appointment_at between now()+interval '1 hour 45 minutes' and now()+interval '2 hours 15 minutes')
  ), inserted as (
    insert into patient_notifications(customer_id,title,message,notification_type)
    select d.customer_id,case when d.reminder_type='appointment_24h' then 'Appointment tomorrow' else 'Appointment in 2 hours' end,
      coalesce(d.service_name,'Your Panthera appointment')||' is scheduled for '||to_char(d.appointment_at at time zone 'Asia/Riyadh','DD Mon YYYY, HH12:MI AM')||'.',d.reminder_type
    from due d where not exists(select 1 from patient_notifications n where n.customer_id=d.customer_id and n.notification_type=d.reminder_type and n.message like '%'||to_char(d.appointment_at at time zone 'Asia/Riyadh','DD Mon YYYY, HH12:MI AM')||'%' and n.created_at>now()-interval '2 days')
    returning 1
  ) select count(*) into v_count from inserted;
  return v_count;
end;$$;
revoke all on function public.generate_patient_appointment_reminders() from public;

commit;
