begin;

create table if not exists public.patient_experience_feedback (
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.clinics(id) on delete restrict,
  customer_id bigint not null references public.customers(id) on delete cascade,
  appointment_id bigint not null references public.appointments(id) on delete cascade,
  rating smallint not null check(rating between 1 and 5),
  tags text[] not null default '{}',
  comment text,
  is_private boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(customer_id,appointment_id)
);

alter table public.patient_experience_feedback enable row level security;
drop policy if exists patient_feedback_self_read on public.patient_experience_feedback;
create policy patient_feedback_self_read on public.patient_experience_feedback for select to authenticated using(customer_id=public.current_patient_customer_id());

create or replace function public.patient_experience_hub()
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_customer_id bigint:=public.current_patient_customer_id();
begin
 if v_customer_id is null then raise exception 'Patient account is not linked'; end if;
 return jsonb_build_object(
  'moments',coalesce((select jsonb_agg(moment order by (moment->>'date')::timestamptz desc) from(
    select jsonb_build_object('id','joined','type','welcome','title','Your Panthera journey began','message','Welcome to a more personal care experience.','date',c.created_at,'icon','heart') moment from customers c where c.id=v_customer_id
    union all
    select jsonb_build_object('id','first-visit','type','visit','title','Your first Panthera visit','message',coalesce(fv.service_name,'A beautiful beginning'),'date',fv.appointment_at,'icon','sparkles') from(select a.appointment_at,s.name service_name from appointments a left join services s on s.id=a.service_id where a.customer_id=v_customer_id and lower(coalesce(a.status,''))='completed' order by a.appointment_at limit 1)fv
    union all
    select jsonb_build_object('id','latest-care','type','care','title','A step forward in your care','message',coalesce(lc.service_name,'Your latest care session'),'date',lc.session_date,'icon','leaf') from(select ts.session_date,s.name service_name from treatment_sessions ts left join appointments a on a.id=ts.appointment_id left join services s on s.id=a.service_id where ts.customer_id=v_customer_id order by ts.session_date desc limit 1)lc
    union all
    select jsonb_build_object('id','membership','type','membership','title',initcap(la.tier)||' member','message',la.points_balance||' Panthera points earned','date',la.joined_at,'icon','diamond') from patient_loyalty_accounts la where la.customer_id=v_customer_id
  )m),'[]'::jsonb),
  'eligibleVisits',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'service',coalesce(s.name,'Panthera visit'),'provider',st.staff_name,'date',a.appointment_at) order by a.appointment_at desc)
    from appointments a left join services s on s.id=a.service_id left join staff st on st.id=a.doctor_id
    where a.customer_id=v_customer_id and lower(coalesce(a.status,''))='completed'
    and not exists(select 1 from patient_experience_feedback f where f.customer_id=v_customer_id and f.appointment_id=a.id)
  ),'[]'::jsonb),
  'feedback',coalesce((select jsonb_agg(jsonb_build_object('id',f.id,'appointmentId',f.appointment_id,'rating',f.rating,'tags',f.tags,'comment',f.comment,'createdAt',f.created_at) order by f.created_at desc) from patient_experience_feedback f where f.customer_id=v_customer_id),'[]'::jsonb)
 );
end;$$;

create or replace function public.patient_submit_feedback(p_appointment_id bigint,p_rating integer,p_tags text[] default '{}',p_comment text default null)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_customer_id bigint:=public.current_patient_customer_id();v_clinic_id bigint;v_id bigint;
begin
 if v_customer_id is null then raise exception 'Patient account is not linked'; end if;
 if p_rating not between 1 and 5 then raise exception 'Rating must be between 1 and 5'; end if;
 select clinic_id into v_clinic_id from appointments where id=p_appointment_id and customer_id=v_customer_id and lower(coalesce(status,''))='completed';
 if v_clinic_id is null then raise exception 'Only your completed visits can be rated'; end if;
 insert into patient_experience_feedback(clinic_id,customer_id,appointment_id,rating,tags,comment)
 values(v_clinic_id,v_customer_id,p_appointment_id,p_rating,coalesce(p_tags,'{}'),nullif(trim(coalesce(p_comment,'')),''))
 on conflict(customer_id,appointment_id) do update set rating=excluded.rating,tags=excluded.tags,comment=excluded.comment,updated_at=now()
 returning id into v_id;
 return v_id;
end;$$;

revoke all on function public.patient_experience_hub() from public;
revoke all on function public.patient_submit_feedback(bigint,integer,text[],text) from public;
grant execute on function public.patient_experience_hub() to authenticated;
grant execute on function public.patient_submit_feedback(bigint,integer,text[],text) to authenticated;
commit;

with checks as(
 select 'experience_feedback_table' check_name,count(*)::bigint value,1::bigint expected from information_schema.tables where table_schema='public' and table_name='patient_experience_feedback'
 union all select 'experience_feedback_rls',count(*)::bigint,1::bigint from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='patient_experience_feedback' and c.relrowsecurity
 union all select 'experience_functions',count(*)::bigint,2::bigint from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('patient_experience_hub','patient_submit_feedback')
 union all select 'patient_phase_tables',count(*)::bigint,5::bigint from information_schema.tables where table_schema='public' and table_name in('patient_loyalty_accounts','patient_progress_media','patient_beauty_reminders','patient_medical_update_requests','patient_experience_feedback')
 union all select 'patient_phase_functions',count(*)::bigint,9::bigint from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('patient_care_hub','patient_membership_card','patient_results_hub','patient_beauty_calendar','patient_add_beauty_reminder','patient_finance_health_hub','patient_request_medical_update','patient_experience_hub','patient_submit_feedback')
 union all select 'private_progress_bucket',count(*)::bigint,1::bigint from storage.buckets where id='patient-progress' and public=false
 union all select 'patient_phase_rls',count(*)::bigint,5::bigint from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in('patient_loyalty_accounts','patient_progress_media','patient_beauty_reminders','patient_medical_update_requests','patient_experience_feedback') and c.relrowsecurity
)
select case when value=expected then 'OK' else 'CHECK' end status,check_name,value,expected from checks order by check_name;
