begin;

create table if not exists public.payment_invoice_items(
  id bigint generated by default as identity primary key,
  payment_id bigint not null references public.payments(id) on delete cascade,
  clinic_id bigint not null references public.clinics(id) on delete restrict,
  branch_id bigint not null references public.branches(id) on delete restrict,
  service_id bigint not null references public.services(id) on delete restrict,
  service_variant_id bigint references public.service_variants(id) on delete restrict,
  description text not null,
  quantity numeric(12,3) not null default 1 check(quantity>0),
  unit text not null default 'service',
  unit_price numeric(12,2) not null check(unit_price>=0),
  line_total numeric(12,2) not null check(line_total>=0),
  created_at timestamptz not null default now()
);
create index if not exists payment_invoice_items_payment_idx on public.payment_invoice_items(payment_id);
alter table public.payment_invoice_items enable row level security;
drop policy if exists "Authenticated users manage invoice items" on public.payment_invoice_items;
create policy "Authenticated users manage invoice items" on public.payment_invoice_items for all to authenticated using(true) with check(true);

create or replace function public.price_payment_material()
returns trigger language plpgsql security definer set search_path=public as $$
declare v_service_id bigint;v_doctor_id bigint;v_variant_service_id bigint;v_variant_name text;v_list_price numeric;v_package_ml numeric:=1;v_match text[];
begin
  if new.appointment_id is null then return new;end if;
  select a.service_id,a.doctor_id into v_service_id,v_doctor_id from appointments a where a.id=new.appointment_id and a.customer_id=new.customer_id and a.clinic_id=new.clinic_id and a.branch_id=new.branch_id;
  if v_service_id is null then raise exception 'Appointment does not belong to this customer and clinic';end if;
  if new.source_system='web_multi_invoice' then return new;end if;
  if new.service_variant_id is null then
    select coalesce(sp_doctor.price,sp_general.price,s.default_price) into v_list_price from services s left join service_prices sp_doctor on sp_doctor.service_id=s.id and sp_doctor.staff_id=v_doctor_id left join service_prices sp_general on sp_general.service_id=s.id and sp_general.staff_id is null where s.id=v_service_id and s.is_active;
    if v_list_price is null or v_list_price<=0 then raise exception 'Appointment service has no active price';end if;
    new.service_id:=v_service_id;new.material_quantity:=null;new.material_unit:=null;new.material_unit_price:=null;new.material_line_total:=round(v_list_price,2);new.amount:=round(v_list_price,2);return new;
  end if;
  select sv.service_id,sv.name,coalesce(svp.price,sv.price) into v_variant_service_id,v_variant_name,v_list_price from service_variants sv left join service_variant_prices svp on svp.service_variant_id=sv.id and svp.staff_id=v_doctor_id and svp.is_active where sv.id=new.service_variant_id and sv.is_active;
  if v_variant_service_id is null or v_variant_service_id<>v_service_id then raise exception 'Selected material is not linked to the appointment service';end if;
  if v_list_price is null or v_list_price<=0 then raise exception 'Selected material has no active price';end if;
  if coalesce(new.material_quantity,0)<=0 then raise exception 'Material quantity must be greater than zero';end if;
  v_match:=regexp_match(v_variant_name,'^\s*([0-9]+(?:\.[0-9]+)?)\s*ML(\s|$)','i');if v_match is not null then v_package_ml:=v_match[1]::numeric;end if;
  new.service_id:=v_service_id;new.material_unit:='ml';new.material_unit_price:=round(v_list_price/v_package_ml,2);new.material_line_total:=round(new.material_quantity*new.material_unit_price,2);new.amount:=new.material_line_total;return new;
end;$$;

create or replace function public.create_multi_service_invoice(p_customer_id bigint,p_appointment_id bigint,p_items jsonb,p_tax numeric default 0,p_method text default 'cash',p_status text default 'paid',p_payment_date timestamptz default now(),p_invoice_number text default null,p_reference_number text default null,p_notes text default null)
returns bigint language plpgsql security invoker set search_path=public as $$
declare v_a appointments%rowtype;v_item jsonb;v_service services%rowtype;v_variant service_variants%rowtype;v_price numeric;v_package numeric:=1;v_qty numeric;v_line numeric;v_subtotal numeric:=0;v_payment bigint;v_match text[];v_description text;v_booking_category text;
begin
  select * into v_a from appointments where id=p_appointment_id and customer_id=p_customer_id;
  if not found then raise exception 'Appointment does not belong to customer';end if;
  select category into v_booking_category from services where id=v_a.service_id;
  if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception 'Invoice requires at least one item';end if;
  insert into payments(clinic_id,branch_id,customer_id,appointment_id,amount,tax_amount,payment_method,payment_status,payment_date,invoice_number,reference_number,currency,notes,source_system)
  values(v_a.clinic_id,v_a.branch_id,p_customer_id,p_appointment_id,0,greatest(coalesce(p_tax,0),0),p_method,p_status,p_payment_date,nullif(trim(p_invoice_number),''),nullif(trim(p_reference_number),''),'SAR',nullif(trim(p_notes),''),'web_multi_invoice') returning id into v_payment;
  for v_item in select value from jsonb_array_elements(p_items) loop
    select * into v_service from services where id=(v_item->>'service_id')::bigint and clinic_id=v_a.clinic_id and is_active;
    if not found then raise exception 'Invalid invoice service';end if;
    if v_a.doctor_id is not null and not exists(select 1 from staff_services where staff_id=v_a.doctor_id and service_id=v_service.id) then raise exception 'Service is not linked to appointment doctor';end if;
    if v_a.doctor_id is null and (v_service.provider_type is distinct from 'department' or v_service.category is distinct from v_booking_category) then raise exception 'Department invoice item is outside the booked department';end if;
    v_qty:=coalesce((v_item->>'quantity')::numeric,1);if v_qty<=0 then raise exception 'Quantity must be positive';end if;
    if nullif(v_item->>'service_variant_id','') is not null then
      select * into v_variant from service_variants where id=(v_item->>'service_variant_id')::bigint and service_id=v_service.id and is_active;
      if not found then raise exception 'Material is not linked to selected service';end if;
      select coalesce((select price from service_variant_prices where service_variant_id=v_variant.id and staff_id=v_a.doctor_id and is_active limit 1),v_variant.price) into v_price;
      v_match:=regexp_match(v_variant.name,'^\s*([0-9]+(?:\.[0-9]+)?)\s*ML(\s|$)','i');v_package:=case when v_match is null then 1 else v_match[1]::numeric end;v_price:=round(v_price/v_package,2);v_description:=v_service.name||' — '||v_variant.name;
    else
      select coalesce((select price from service_prices where service_id=v_service.id and staff_id=v_a.doctor_id limit 1),(select price from service_prices where service_id=v_service.id and staff_id is null limit 1),v_service.default_price) into v_price;
      v_description:=v_service.name;
    end if;
    if coalesce(v_price,0)<=0 then raise exception 'Selected service or material has no price';end if;
    v_line:=round(v_qty*v_price,2);v_subtotal:=v_subtotal+v_line;
    insert into payment_invoice_items(payment_id,clinic_id,branch_id,service_id,service_variant_id,description,quantity,unit,unit_price,line_total) values(v_payment,v_a.clinic_id,v_a.branch_id,v_service.id,v_variant.id,v_description,v_qty,case when v_variant.id is null then 'service' else 'ml' end,v_price,v_line);
    v_variant:=null;
  end loop;
  update payments set amount=round(v_subtotal+greatest(coalesce(p_tax,0),0),2),invoice_number=coalesce(nullif(trim(p_invoice_number),''),'ZRN-'||lpad(v_payment::text,6,'0')) where id=v_payment;
  return v_payment;
end;$$;
grant execute on function public.create_multi_service_invoice(bigint,bigint,jsonb,numeric,text,text,timestamptz,text,text,text) to authenticated;
commit;

select case when count(*)=1 then 'OK' else 'CHECK' end status,'payment_invoice_items_table' check_name,count(*) value,1 expected from information_schema.tables where table_schema='public' and table_name='payment_invoice_items'
union all select case when count(*)=1 then 'OK' else 'CHECK' end,'multi_service_invoice_function',count(*),1 from pg_proc where proname='create_multi_service_invoice';
