begin;

create table if not exists public.patient_medical_update_requests (
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.clinics(id) on delete restrict,
  customer_id bigint not null references public.customers(id) on delete cascade,
  requested_fields text[] not null default '{}',
  patient_note text,
  status text not null default 'pending' check(status in('pending','reviewing','completed','declined')),
  resolved_by bigint references public.staff(id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists patient_medical_updates_customer_idx on public.patient_medical_update_requests(customer_id,created_at desc);
alter table public.patient_medical_update_requests enable row level security;
drop policy if exists patient_medical_updates_self_read on public.patient_medical_update_requests;
create policy patient_medical_updates_self_read on public.patient_medical_update_requests for select to authenticated using(customer_id=public.current_patient_customer_id());

create or replace function public.patient_finance_health_hub()
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_customer_id bigint:=public.current_patient_customer_id();v_record jsonb;v_filled integer:=0;
begin
 if v_customer_id is null then raise exception 'Patient account is not linked'; end if;
 select to_jsonb(mr),
   (case when nullif(mr.blood_type,'') is not null then 1 else 0 end+
    case when nullif(mr.allergies,'') is not null then 1 else 0 end+
    case when nullif(mr.chronic_diseases,'') is not null then 1 else 0 end+
    case when nullif(mr.medications,'') is not null then 1 else 0 end+
    case when nullif(mr.medical_notes,'') is not null then 1 else 0 end)
 into v_record,v_filled from medical_records mr where mr.customer_id=v_customer_id;

 return jsonb_build_object(
  'wallet',jsonb_build_object(
   'totalPaid',coalesce((select sum(coalesce(amount,0)) from payments where customer_id=v_customer_id and lower(coalesce(payment_status,''))='paid'),0),
   'outstanding',coalesce((select sum(coalesce(amount,0)) from payments where customer_id=v_customer_id and lower(coalesce(payment_status,'')) in('pending','unpaid','due')),0),
   'currency',coalesce((select currency from payments where customer_id=v_customer_id and currency is not null order by created_at desc limit 1),'SAR'),
   'transactions',coalesce((select jsonb_agg(jsonb_build_object(
    'id',p.id,'invoiceNumber',p.invoice_number,'amount',p.amount,'taxAmount',p.tax_amount,'status',p.payment_status,
    'method',p.payment_method,'date',coalesce(p.payment_date,p.created_at),'reference',p.reference_number,'notes',p.notes
   ) order by coalesce(p.payment_date,p.created_at) desc) from payments p where p.customer_id=v_customer_id),'[]'::jsonb)
  ),
  'health',jsonb_build_object(
   'record',v_record,'completeness',round((v_filled::numeric/5)*100),
   'updateRequests',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'fields',r.requested_fields,'note',r.patient_note,'status',r.status,'createdAt',r.created_at) order by r.created_at desc) from patient_medical_update_requests r where r.customer_id=v_customer_id),'[]'::jsonb)
  )
 );
end;$$;

create or replace function public.patient_request_medical_update(p_note text default null,p_fields text[] default '{}')
returns bigint language plpgsql security definer set search_path=public as $$
declare v_customer_id bigint:=public.current_patient_customer_id();v_clinic_id bigint;v_id bigint;
begin
 if v_customer_id is null then raise exception 'Patient account is not linked'; end if;
 if exists(select 1 from patient_medical_update_requests where customer_id=v_customer_id and status in('pending','reviewing')) then raise exception 'An update request is already in progress'; end if;
 select clinic_id into v_clinic_id from customers where id=v_customer_id;
 insert into patient_medical_update_requests(clinic_id,customer_id,requested_fields,patient_note) values(v_clinic_id,v_customer_id,coalesce(p_fields,'{}'),nullif(trim(coalesce(p_note,'')),'')) returning id into v_id;
 return v_id;
end;$$;

revoke all on function public.patient_finance_health_hub() from public;
revoke all on function public.patient_request_medical_update(text,text[]) from public;
grant execute on function public.patient_finance_health_hub() to authenticated;
grant execute on function public.patient_request_medical_update(text,text[]) to authenticated;
commit;

with checks as(
 select 'medical_update_requests_table' check_name,count(*)::bigint value,1::bigint expected from information_schema.tables where table_schema='public' and table_name='patient_medical_update_requests'
 union all select 'medical_update_requests_rls',count(*)::bigint,1::bigint from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='patient_medical_update_requests' and c.relrowsecurity
 union all select 'patient_wallet_health_functions',count(*)::bigint,2::bigint from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('patient_finance_health_hub','patient_request_medical_update')
)
select case when value=expected then 'OK' else 'CHECK' end status,check_name,value,expected from checks order by check_name;
