-- Secure Buraq -> Zernio webhook inbox. Safe to run more than once.
begin;

create table if not exists public.integration_webhook_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  event_hash text not null,
  event_type text not null,
  provider_event_id text,
  payload jsonb not null,
  processing_status text not null default 'received'
    check (processing_status in ('received','processed','ignored','failed')),
  processing_error text,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  unique (provider,event_hash)
);

alter table public.integration_webhook_events enable row level security;

-- Intentionally no client-facing policy. Only server-side service-role code may
-- read or write webhook payloads because they can contain personal messages.
drop policy if exists "Authenticated users manage integration webhook events"
  on public.integration_webhook_events;

create index if not exists integration_webhook_events_status_idx
  on public.integration_webhook_events(provider,processing_status,received_at);
create index if not exists integration_webhook_events_type_idx
  on public.integration_webhook_events(provider,event_type,received_at desc);

commit;

select 'buraq_webhook_storage_ready' as status;
