-- Zernio Phase 6 Staff & HR. Safe to run more than once.
begin;
set local lock_timeout = '20s';

alter table public.staff add column if not exists employee_code text;
alter table public.staff add column if not exists job_title text;
alter table public.staff add column if not exists hire_date date;
alter table public.staff add column if not exists employment_status text not null default 'active';
alter table public.staff add column if not exists salary numeric not null default 0;
alter table public.staff add column if not exists notes text;

create unique index if not exists staff_employee_code_unique
  on public.staff(clinic_id, employee_code) where employee_code is not null;

create table if not exists public.hr_roles (
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.clinics(id) on delete cascade,
  name text not null,
  description text,
  is_system boolean not null default false,
  created_at timestamptz not null default now(),
  unique(clinic_id, name)
);

create table if not exists public.hr_permissions (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  module text not null
);

create table if not exists public.hr_role_permissions (
  role_id bigint not null references public.hr_roles(id) on delete cascade,
  permission_id bigint not null references public.hr_permissions(id) on delete cascade,
  primary key(role_id, permission_id)
);

create table if not exists public.hr_staff_roles (
  staff_id bigint not null references public.staff(id) on delete cascade,
  role_id bigint not null references public.hr_roles(id) on delete cascade,
  assigned_at timestamptz not null default now(),
  primary key(staff_id, role_id)
);

create table if not exists public.hr_attendance (
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.clinics(id) on delete cascade,
  branch_id bigint not null references public.branches(id) on delete restrict,
  staff_id bigint not null references public.staff(id) on delete cascade,
  work_date date not null default current_date,
  check_in timestamptz,
  check_out timestamptz,
  status text not null default 'present' check(status in ('present','absent','late','leave','sick')),
  notes text,
  created_at timestamptz not null default now(),
  unique(staff_id, work_date),
  check(check_out is null or check_in is null or check_out >= check_in)
);

create table if not exists public.hr_shifts (
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.clinics(id) on delete cascade,
  branch_id bigint not null references public.branches(id) on delete restrict,
  staff_id bigint not null references public.staff(id) on delete cascade,
  weekday smallint not null check(weekday between 0 and 6),
  start_time time not null,
  end_time time not null,
  is_working boolean not null default true,
  created_at timestamptz not null default now(),
  unique(staff_id, weekday),
  check(end_time > start_time)
);

insert into public.hr_permissions(code,name,module) values
('customers.manage','Manage customers','Customers'),
('appointments.manage','Manage appointments','Appointments'),
('treatments.manage','Manage treatments','Treatments'),
('payments.manage','Manage payments','Finance'),
('inventory.manage','Manage inventory','Inventory'),
('reports.view','View analytics','Reports'),
('staff.manage','Manage staff and HR','Staff'),
('settings.manage','Manage clinic settings','Settings')
on conflict(code) do update set name=excluded.name,module=excluded.module;

insert into public.hr_roles(clinic_id,name,description,is_system)
select c.id,r.name,r.description,true from public.clinics c cross join (values
('Admin','Full clinic operating access'),
('Doctor','Clinical and treatment access'),
('Nurse','Clinical support and inventory consumption'),
('Reception','Customers, appointments and follow-ups'),
('Coordinator','Customer care and booking coordination'),
('Finance','Payments, invoices and reports')
) r(name,description)
on conflict(clinic_id,name) do nothing;

-- Admin gets every permission; other roles can be customized from the UI later.
insert into public.hr_role_permissions(role_id,permission_id)
select r.id,p.id from public.hr_roles r cross join public.hr_permissions p where r.name='Admin'
on conflict do nothing;

alter table public.hr_roles enable row level security;
alter table public.hr_permissions enable row level security;
alter table public.hr_role_permissions enable row level security;
alter table public.hr_staff_roles enable row level security;
alter table public.hr_attendance enable row level security;
alter table public.hr_shifts enable row level security;

do $$ declare t text; begin
  foreach t in array array['hr_roles','hr_permissions','hr_role_permissions','hr_staff_roles','hr_attendance','hr_shifts'] loop
    execute format('drop policy if exists "Authenticated users manage %1$s" on public.%1$I', t);
    execute format('create policy "Authenticated users manage %1$s" on public.%1$I for all to authenticated using (true) with check (true)', t);
  end loop;
end $$;

create index if not exists hr_attendance_scope_date_idx on public.hr_attendance(clinic_id,branch_id,work_date desc);
create index if not exists hr_shifts_staff_idx on public.hr_shifts(staff_id,weekday);
commit;

select 'staff_hr_phase6_ready' as status;
