begin;

create table if not exists public.patient_accounts (
  auth_user_id uuid primary key references auth.users(id) on delete cascade,
  customer_id bigint not null unique references public.customers(id) on delete cascade,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz
);

create table if not exists public.patient_notifications (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  title text not null,
  message text not null,
  notification_type text not null default 'info',
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists patient_notifications_customer_idx
  on public.patient_notifications(customer_id, is_read, created_at desc);

alter table public.patient_accounts enable row level security;
alter table public.patient_notifications enable row level security;

-- Patient users and clinic employees both use Supabase's authenticated role.
-- Tighten legacy authenticated policies that granted unconditional access so
-- a patient token cannot use the REST API to browse or modify clinic tables.
do $$
declare p record;
begin
  for p in
    select schemaname,tablename,policyname,cmd
    from pg_policies
    where schemaname='public'
      and 'authenticated'=any(roles)
      and (coalesce(qual,'') in ('true','(true)') or coalesce(with_check,'') in ('true','(true)'))
      and tablename not in ('patient_accounts','patient_notifications')
  loop
    if p.cmd='SELECT' or p.cmd='DELETE' then
      execute format('alter policy %I on %I.%I using (public.current_staff_id() is not null)',p.policyname,p.schemaname,p.tablename);
    elsif p.cmd='INSERT' then
      execute format('alter policy %I on %I.%I with check (public.current_staff_id() is not null)',p.policyname,p.schemaname,p.tablename);
    else
      execute format('alter policy %I on %I.%I using (public.current_staff_id() is not null) with check (public.current_staff_id() is not null)',p.policyname,p.schemaname,p.tablename);
    end if;
  end loop;
end $$;

create or replace function public.current_patient_customer_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select customer_id from public.patient_accounts where auth_user_id = auth.uid()
$$;

revoke all on function public.current_patient_customer_id() from public;
grant execute on function public.current_patient_customer_id() to authenticated;

drop policy if exists patient_account_self on public.patient_accounts;
create policy patient_account_self on public.patient_accounts for select to authenticated
using (auth_user_id = auth.uid());

drop policy if exists patient_notification_self on public.patient_notifications;
create policy patient_notification_self on public.patient_notifications for select to authenticated
using (customer_id = public.current_patient_customer_id());

drop policy if exists patient_notification_update_self on public.patient_notifications;
create policy patient_notification_update_self on public.patient_notifications for update to authenticated
using (customer_id = public.current_patient_customer_id())
with check (customer_id = public.current_patient_customer_id());

create or replace function public.link_my_patient_account()
returns bigint
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_phone text;
  v_customer_id bigint;
  v_matches integer;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  select regexp_replace(coalesce(phone, raw_user_meta_data->>'phone', ''), '\D', '', 'g')
    into v_phone from auth.users where id = auth.uid();
  if length(v_phone) < 9 then raise exception 'Verified mobile number is missing'; end if;

  select count(*), min(id) into v_matches, v_customer_id
  from public.customers
  where right(regexp_replace(coalesce(phone_normalized, phone, ''), '\D', '', 'g'), 9) = right(v_phone, 9)
    and coalesce(status, 'active') <> 'inactive';

  if v_matches = 0 then raise exception 'No patient record matches this mobile number'; end if;
  if v_matches > 1 then raise exception 'More than one patient record matches this mobile number'; end if;

  insert into public.patient_accounts(auth_user_id, customer_id, last_seen_at)
  values(auth.uid(), v_customer_id, now())
  on conflict(auth_user_id) do update set customer_id=excluded.customer_id,last_seen_at=now();
  return v_customer_id;
end
$$;

create or replace function public.patient_mobile_dashboard()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_customer_id bigint := public.current_patient_customer_id();
  result jsonb;
begin
  if v_customer_id is null then raise exception 'Patient account is not linked'; end if;
  update public.patient_accounts set last_seen_at=now() where auth_user_id=auth.uid();

  select jsonb_build_object(
    'profile', jsonb_build_object(
      'id', c.id, 'firstName', c.first_name, 'lastName', c.last_name,
      'phone', c.phone, 'email', c.email, 'customerCode', c.customer_code,
      'clinicId', c.clinic_id, 'branchId', c.branch_id
    ),
    'appointments', coalesce((select jsonb_agg(jsonb_build_object(
      'id',a.id,'service',s.name,'provider',coalesce(st.staff_name,d.name,r.name),
      'appointmentAt',a.appointment_at,'status',a.status,'room',r.name
    ) order by a.appointment_at desc)
      from public.appointments a
      left join public.services s on s.id=a.service_id
      left join public.staff st on st.id=a.doctor_id
      left join public.devices d on d.id=a.device_id
      left join public.rooms r on r.id=a.room_id
      where a.customer_id=v_customer_id), '[]'::jsonb),
    'invoices', coalesce((select jsonb_agg(jsonb_build_object(
      'id',p.id,'invoiceNumber',p.invoice_number,'amount',p.amount,
      'status',p.payment_status,'date',coalesce(p.payment_date,p.created_at)
    ) order by p.created_at desc) from public.payments p where p.customer_id=v_customer_id), '[]'::jsonb),
    'medicalRecord', (select to_jsonb(m)-'customer_id'-'clinic_id'-'branch_id' from public.medical_records m where m.customer_id=v_customer_id),
    'notifications', coalesce((select jsonb_agg(to_jsonb(n) order by n.created_at desc) from public.patient_notifications n where n.customer_id=v_customer_id), '[]'::jsonb)
  ) into result
  from public.customers c where c.id=v_customer_id;
  return result;
end
$$;

create or replace function public.patient_booking_catalog()
returns table(id bigint, name text, category text, duration_minutes integer, provider_type text)
language sql
stable
security definer
set search_path = public
as $$
  select distinct s.id,s.name,s.category,s.duration_minutes,s.provider_type
  from public.services s
  where s.is_active and (
    exists(select 1 from public.staff_services ss where ss.service_id=s.id and ss.is_active)
    or exists(select 1 from public.service_devices sd where sd.service_id=s.id)
    or s.provider_type='department'
  ) order by s.category,s.name
$$;

create or replace function public.patient_book_appointment(p_service_id bigint, p_appointment_at timestamptz, p_notes text default null)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  c public.customers%rowtype;
  v_provider_type text;
  v_doctor_id bigint;
  v_device_id bigint;
  v_room_id bigint;
  v_id bigint;
begin
  select * into c from public.customers where id=public.current_patient_customer_id();
  if c.id is null then raise exception 'Patient account is not linked'; end if;
  if p_appointment_at <= now() then raise exception 'Appointment must be in the future'; end if;
  select provider_type into v_provider_type from public.services where id=p_service_id and is_active;
  if v_provider_type is null then raise exception 'Service is not available'; end if;

  select sd.device_id,d.room_id into v_device_id,v_room_id
  from public.service_devices sd join public.devices d on d.id=sd.device_id and d.is_active
  where sd.service_id=p_service_id
    and not exists(select 1 from public.appointments a where a.device_id=d.id and a.appointment_at=p_appointment_at and coalesce(a.status,'') not in('cancelled','no_show'))
  order by d.id limit 1;

  if v_device_id is null and v_provider_type='doctor' then
    select ss.staff_id,sr.room_id into v_doctor_id,v_room_id
    from public.staff_services ss
    join public.staff st on st.id=ss.staff_id and st.is_active
    join public.staff_rooms sr on sr.staff_id=st.id
    where ss.service_id=p_service_id and ss.is_active
      and not exists(select 1 from public.appointments a where a.doctor_id=st.id and a.appointment_at=p_appointment_at and coalesce(a.status,'') not in('cancelled','no_show'))
      and not exists(select 1 from public.appointments a where a.room_id=sr.room_id and a.appointment_at=p_appointment_at and coalesce(a.status,'') not in('cancelled','no_show'))
    order by st.id,sr.room_id limit 1;
  elsif v_device_id is null then
    select r.id into v_room_id from public.rooms r
    where r.branch_id=c.branch_id and r.is_active and lower(r.name) like 'profacial%'
      and not exists(select 1 from public.appointments a where a.room_id=r.id and a.appointment_at=p_appointment_at and coalesce(a.status,'') not in('cancelled','no_show'))
    order by r.id limit 1;
  end if;

  if v_room_id is null then raise exception 'No provider or room is available at this time'; end if;
  insert into public.appointments(customer_id,clinic_id,branch_id,service_id,doctor_id,device_id,room_id,appointment_at,status,notes,source,created_from_channel)
  values(c.id,c.clinic_id,c.branch_id,p_service_id,v_doctor_id,v_device_id,v_room_id,p_appointment_at,'requested',p_notes,'patient_app','mobile')
  returning id into v_id;
  insert into public.patient_notifications(customer_id,title,message,notification_type)
  values(c.id,'Appointment requested','Your appointment request was sent to Panthera Clinics.','appointment');
  return v_id;
end
$$;

create or replace function public.patient_cancel_appointment(p_appointment_id bigint)
returns void language plpgsql security definer set search_path=public as $$
begin
  update public.appointments set status='cancelled'
  where id=p_appointment_id and customer_id=public.current_patient_customer_id()
    and appointment_at>now() and coalesce(status,'') not in('completed','cancelled');
  if not found then raise exception 'Appointment cannot be cancelled'; end if;
end $$;

revoke all on function public.link_my_patient_account() from public;
revoke all on function public.patient_mobile_dashboard() from public;
revoke all on function public.patient_booking_catalog() from public;
revoke all on function public.patient_book_appointment(bigint,timestamptz,text) from public;
revoke all on function public.patient_cancel_appointment(bigint) from public;
grant execute on function public.link_my_patient_account() to authenticated;
grant execute on function public.patient_mobile_dashboard() to authenticated;
grant execute on function public.patient_booking_catalog() to authenticated;
grant execute on function public.patient_book_appointment(bigint,timestamptz,text) to authenticated;
grant execute on function public.patient_cancel_appointment(bigint) to authenticated;

commit;
