-- Secure new-patient registration, legal acceptance and privacy-right requests.
begin;

create table if not exists public.patient_legal_acceptances(
 id bigint generated by default as identity primary key,
 auth_user_id uuid not null references auth.users(id) on delete cascade,
 customer_id bigint not null references public.customers(id) on delete cascade,
 document_type text not null check(document_type in('privacy','terms')),
 document_version text not null,
 accepted_at timestamptz not null default now(),
 unique(auth_user_id,document_type,document_version)
);
create table if not exists public.patient_privacy_requests(
 id bigint generated by default as identity primary key,
 auth_user_id uuid not null references auth.users(id) on delete cascade,
 customer_id bigint not null references public.customers(id) on delete cascade,
 request_type text not null check(request_type in('access','export','correction','deletion','withdraw_consent')),
 details text,
 status text not null default 'submitted' check(status in('submitted','in_review','completed','rejected')),
 submitted_at timestamptz not null default now(),
 completed_at timestamptz
);
create index if not exists patient_privacy_requests_customer_idx on public.patient_privacy_requests(customer_id,status,submitted_at desc);
alter table public.patient_accounts add column if not exists account_status text not null default 'active';
alter table public.patient_accounts drop constraint if exists patient_accounts_account_status_check;
alter table public.patient_accounts add constraint patient_accounts_account_status_check check(account_status in('active','deletion_requested','disabled'));
alter table public.patient_legal_acceptances enable row level security;
alter table public.patient_privacy_requests enable row level security;
drop policy if exists patient_legal_acceptances_self on public.patient_legal_acceptances;
create policy patient_legal_acceptances_self on public.patient_legal_acceptances for select to authenticated using(auth_user_id=auth.uid() or public.current_staff_id() is not null);
drop policy if exists patient_privacy_requests_self on public.patient_privacy_requests;
create policy patient_privacy_requests_self on public.patient_privacy_requests for select to authenticated using(auth_user_id=auth.uid() or public.current_staff_id() is not null);

create or replace function public.current_patient_customer_id() returns bigint
language sql stable security definer set search_path=public as $$
 select customer_id from public.patient_accounts where auth_user_id=auth.uid() and account_status='active'
$$;

create or replace function public.link_my_patient_account() returns bigint
language plpgsql security definer set search_path=public,auth as $$
declare v_phone text;v_customer_id bigint;v_matches integer;v_status text;
begin
 if auth.uid() is null then raise exception 'Authentication required';end if;
 select account_status into v_status from public.patient_accounts where auth_user_id=auth.uid();
 if v_status='deletion_requested' then raise exception 'This account has a deletion request in review. Contact Panthera support to restore access.';end if;
 if v_status='disabled' then raise exception 'This account is disabled. Contact Panthera support.';end if;
 select regexp_replace(coalesce(phone,raw_user_meta_data->>'phone',''),'\D','','g') into v_phone from auth.users where id=auth.uid();
 if length(v_phone)<9 then raise exception 'Verified mobile number is missing';end if;
 select count(*),min(id) into v_matches,v_customer_id from public.customers
 where right(regexp_replace(coalesce(phone_normalized,phone,''),'\D','','g'),9)=right(v_phone,9) and coalesce(status,'active')<>'inactive';
 if v_matches=0 then raise exception 'No patient record matches this mobile number. Choose New patient to create a profile.';end if;
 if v_matches>1 then raise exception 'More than one patient record matches this mobile number';end if;
 if exists(select 1 from patient_accounts where customer_id=v_customer_id and auth_user_id<>auth.uid()) then raise exception 'This patient profile is already secured by another account. Contact Panthera support.';end if;
 insert into patient_accounts(auth_user_id,customer_id,last_seen_at,account_status) values(auth.uid(),v_customer_id,now(),'active')
 on conflict(auth_user_id) do update set customer_id=excluded.customer_id,last_seen_at=now();
 return v_customer_id;
end$$;

create or replace function public.patient_register_new_account(p_first_name text,p_last_name text,p_email text,p_language text,p_document_version text)
returns bigint language plpgsql security definer set search_path=public,auth as $$
declare v_phone text;v_customer_id bigint;v_clinic_id bigint;v_branch_id bigint;v_code text;
begin
 if auth.uid() is null then raise exception 'Authentication required';end if;
 if length(trim(coalesce(p_first_name,'')))<2 then raise exception 'First name is required';end if;
 if nullif(trim(coalesce(p_email,'')),'') is not null and trim(p_email) !~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$' then raise exception 'Enter a valid email address';end if;
 if p_language not in('ar','en') then raise exception 'Unsupported language';end if;
 select regexp_replace(coalesce(phone,raw_user_meta_data->>'phone',''),'\D','','g') into v_phone from auth.users where id=auth.uid();
 if length(v_phone)<9 then raise exception 'Verified mobile number is missing';end if;
 if exists(select 1 from patient_accounts where auth_user_id=auth.uid()) then return public.current_patient_customer_id();end if;
 if exists(select 1 from customers where right(regexp_replace(coalesce(phone_normalized,phone,''),'\D','','g'),9)=right(v_phone,9)) then raise exception 'A patient file already exists for this mobile number. Use existing patient sign in.';end if;
 select c.id,b.id into v_clinic_id,v_branch_id from clinics c join branches b on b.clinic_id=c.id where c.is_active and b.is_active order by (c.code='PANTHERA') desc,(b.code='MAIN') desc,c.id,b.id limit 1;
 if v_clinic_id is null or v_branch_id is null then raise exception 'Clinic registration is not available';end if;
 v_code:='APP-'||upper(substr(replace(auth.uid()::text,'-',''),1,12));
 insert into customers(customer_code,first_name,last_name,phone,phone_normalized,email,status,clinic_id,branch_id)
 values(v_code,trim(p_first_name),nullif(trim(coalesce(p_last_name,'')),''),'+'||v_phone,'+'||v_phone,nullif(trim(coalesce(p_email,'')),''),'active',v_clinic_id,v_branch_id)
 returning id into v_customer_id;
 insert into patient_accounts(auth_user_id,customer_id,last_seen_at,preferred_language) values(auth.uid(),v_customer_id,now(),p_language);
 insert into patient_legal_acceptances(auth_user_id,customer_id,document_type,document_version) values
 (auth.uid(),v_customer_id,'privacy',p_document_version),(auth.uid(),v_customer_id,'terms',p_document_version);
 return v_customer_id;
end$$;

create or replace function public.patient_submit_privacy_request(p_request_type text,p_details text default null)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_customer_id bigint:=public.current_patient_customer_id();v_id bigint;
begin
 if v_customer_id is null then raise exception 'Patient account is not linked';end if;
 if p_request_type not in('access','export','correction','deletion','withdraw_consent') then raise exception 'Unsupported privacy request';end if;
 if exists(select 1 from patient_privacy_requests where customer_id=v_customer_id and request_type=p_request_type and status in('submitted','in_review')) then raise exception 'A matching request is already being reviewed';end if;
 insert into patient_privacy_requests(auth_user_id,customer_id,request_type,details) values(auth.uid(),v_customer_id,p_request_type,nullif(trim(coalesce(p_details,'')),'')) returning id into v_id;
 if p_request_type='deletion' then update patient_accounts set account_status='deletion_requested',last_seen_at=now() where auth_user_id=auth.uid();end if;
 insert into enterprise_notifications(clinic_id,branch_id,title,message,type,href)
 select c.clinic_id,c.branch_id,'Patient privacy request','A patient submitted a '||p_request_type||' request.','privacy','/customers/'||c.id from customers c where c.id=v_customer_id;
 return v_id;
end$$;

revoke all on function public.patient_register_new_account(text,text,text,text,text) from public,anon;
revoke all on function public.patient_submit_privacy_request(text,text) from public,anon;
revoke all on function public.current_patient_customer_id() from public;
grant execute on function public.patient_register_new_account(text,text,text,text,text) to authenticated;
grant execute on function public.patient_submit_privacy_request(text,text) to authenticated;
grant execute on function public.current_patient_customer_id() to authenticated;

commit;
