begin;

create table if not exists public.patient_beauty_reminders (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  title text not null,
  reminder_at timestamptz not null,
  reminder_type text not null default 'personal' check(reminder_type in('personal','routine','product')),
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists patient_beauty_reminders_customer_idx on public.patient_beauty_reminders(customer_id,reminder_at);
alter table public.patient_beauty_reminders enable row level security;
drop policy if exists patient_beauty_reminders_self on public.patient_beauty_reminders;
create policy patient_beauty_reminders_self on public.patient_beauty_reminders for all to authenticated
using(customer_id=public.current_patient_customer_id())
with check(customer_id=public.current_patient_customer_id());

create or replace function public.patient_beauty_calendar()
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_customer_id bigint:=public.current_patient_customer_id();
  v_clinic_id bigint;
  v_branch_id bigint;
begin
  if v_customer_id is null then raise exception 'Patient account is not linked'; end if;
  select clinic_id,branch_id into v_clinic_id,v_branch_id from customers where id=v_customer_id;
  return jsonb_build_object(
    'events',coalesce((
      select jsonb_agg(event order by (event->>'date')::timestamptz) from(
        select jsonb_build_object('id','appointment-'||a.id,'type','appointment','title',coalesce(s.name,'Panthera visit'),'date',a.appointment_at,'status',a.status,'subtitle',coalesce(st.staff_name,r.name)) event
        from appointments a left join services s on s.id=a.service_id left join staff st on st.id=a.doctor_id left join rooms r on r.id=a.room_id where a.customer_id=v_customer_id
        union all
        select jsonb_build_object('id','followup-'||ts.id,'type','followup','title','Recommended follow-up','date',ts.followup_date,'status','recommended','subtitle',coalesce(st.staff_name,'Panthera care team'))
        from treatment_sessions ts left join staff st on st.id=ts.doctor_id where ts.customer_id=v_customer_id and ts.followup_required and ts.followup_date is not null
        union all
        select jsonb_build_object('id','reminder-'||br.id,'type',br.reminder_type,'title',br.title,'date',br.reminder_at,'status','reminder','subtitle',br.notes)
        from patient_beauty_reminders br where br.customer_id=v_customer_id
      )q
    ),'[]'::jsonb),
    'contact',(select jsonb_build_object(
      'clinicName',c.name,'branchName',b.name,
      'phone',coalesce(nullif(b.phone,''),nullif(c.phone,'')),
      'email',c.email,'address',b.address
    ) from clinics c left join branches b on b.id=v_branch_id where c.id=v_clinic_id)
  );
end;
$$;

create or replace function public.patient_add_beauty_reminder(p_title text,p_reminder_at timestamptz,p_type text default 'personal',p_notes text default null)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_customer_id bigint:=public.current_patient_customer_id();v_id bigint;
begin
 if v_customer_id is null then raise exception 'Patient account is not linked'; end if;
 if trim(coalesce(p_title,''))='' then raise exception 'Reminder title is required'; end if;
 if p_type not in('personal','routine','product') then raise exception 'Invalid reminder type'; end if;
 insert into patient_beauty_reminders(customer_id,title,reminder_at,reminder_type,notes) values(v_customer_id,trim(p_title),p_reminder_at,p_type,p_notes) returning id into v_id;
 return v_id;
end;$$;

revoke all on function public.patient_beauty_calendar() from public;
revoke all on function public.patient_add_beauty_reminder(text,timestamptz,text,text) from public;
grant execute on function public.patient_beauty_calendar() to authenticated;
grant execute on function public.patient_add_beauty_reminder(text,timestamptz,text,text) to authenticated;
commit;

with checks as(
 select 'beauty_reminders_table' check_name,count(*)::bigint value,1::bigint expected from information_schema.tables where table_schema='public' and table_name='patient_beauty_reminders'
 union all select 'beauty_reminders_rls',count(*)::bigint,1::bigint from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='patient_beauty_reminders' and c.relrowsecurity
 union all select 'beauty_calendar_functions',count(*)::bigint,2::bigint from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('patient_beauty_calendar','patient_add_beauty_reminder')
)
select case when value=expected then 'OK' else 'CHECK' end status,check_name,value,expected from checks order by check_name;
