-- Zernio Phase 5 Inventory. Safe to run more than once.
create table if not exists public.inventory_suppliers (
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.clinics(id) on delete cascade,
  name text not null,
  phone text,
  email text,
  tax_number text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (clinic_id, name)
);

create table if not exists public.inventory_products (
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.clinics(id) on delete cascade,
  branch_id bigint not null references public.branches(id) on delete restrict,
  name text not null,
  sku text,
  barcode text,
  category text,
  unit text not null default 'unit',
  current_stock numeric not null default 0 check (current_stock >= 0),
  minimum_stock numeric not null default 0 check (minimum_stock >= 0),
  unit_cost numeric not null default 0 check (unit_cost >= 0),
  batch_number text,
  expiry_date date,
  supplier_id bigint references public.inventory_suppliers(id) on delete set null,
  service_variant_id bigint references public.service_variants(id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (clinic_id, branch_id, sku),
  unique (clinic_id, branch_id, barcode)
);

alter table public.inventory_products add column if not exists service_variant_id bigint references public.service_variants(id) on delete set null;
create unique index if not exists inventory_product_variant_unique on public.inventory_products(clinic_id, branch_id, service_variant_id) where service_variant_id is not null;

create table if not exists public.inventory_purchase_orders (
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.clinics(id) on delete cascade,
  branch_id bigint not null references public.branches(id) on delete restrict,
  supplier_id bigint not null references public.inventory_suppliers(id) on delete restrict,
  order_number text not null,
  status text not null default 'draft' check (status in ('draft','ordered','partially_received','received','cancelled')),
  ordered_at timestamptz,
  expected_at date,
  received_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  unique (clinic_id, order_number)
);

create table if not exists public.inventory_purchase_order_items (
  id bigint generated by default as identity primary key,
  purchase_order_id bigint not null references public.inventory_purchase_orders(id) on delete cascade,
  product_id bigint not null references public.inventory_products(id) on delete restrict,
  quantity numeric not null check (quantity > 0),
  received_quantity numeric not null default 0 check (received_quantity >= 0),
  unit_cost numeric not null default 0 check (unit_cost >= 0),
  unique (purchase_order_id, product_id)
);

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.clinics(id) on delete cascade,
  branch_id bigint not null references public.branches(id) on delete restrict,
  product_id bigint not null references public.inventory_products(id) on delete restrict,
  movement_type text not null check (movement_type in ('opening','purchase','consumption','adjustment_in','adjustment_out','expired','return')),
  quantity numeric not null check (quantity > 0),
  unit_cost numeric not null default 0 check (unit_cost >= 0),
  doctor_id bigint references public.staff(id) on delete set null,
  service_id bigint references public.services(id) on delete set null,
  treatment_session_id bigint references public.treatment_sessions(id) on delete set null,
  purchase_order_id bigint references public.inventory_purchase_orders(id) on delete set null,
  notes text,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create or replace function public.apply_inventory_movement() returns trigger language plpgsql security definer set search_path = public as $$
declare v_delta numeric;
begin
  v_delta := case when new.movement_type in ('opening','purchase','adjustment_in','return') then new.quantity else -new.quantity end;
  update public.inventory_products
  set current_stock = current_stock + v_delta, updated_at = now()
  where id = new.product_id and clinic_id = new.clinic_id and branch_id = new.branch_id
    and current_stock + v_delta >= 0;
  if not found then raise exception 'Insufficient stock or invalid product scope'; end if;
  return new;
end $$;

drop trigger if exists inventory_movement_stock_trigger on public.inventory_movements;
create trigger inventory_movement_stock_trigger after insert on public.inventory_movements for each row execute function public.apply_inventory_movement();

create or replace function public.consume_inventory_from_treatment_item() returns trigger language plpgsql security definer set search_path = public as $$
declare v_session public.treatment_sessions%rowtype; v_product_id bigint;
begin
  select * into v_session from public.treatment_sessions where id = new.session_id;
  if new.product_id is not null then
    select id into v_product_id from public.inventory_products
    where id = new.product_id and clinic_id = v_session.clinic_id and branch_id = v_session.branch_id and is_active;
  end if;
  if v_product_id is null and new.service_variant_id is not null then
    select id into v_product_id from public.inventory_products
    where clinic_id = v_session.clinic_id and branch_id = v_session.branch_id
      and service_variant_id = new.service_variant_id and is_active limit 1;
  end if;
  if v_product_id is not null then
    insert into public.inventory_movements(clinic_id,branch_id,product_id,movement_type,quantity,doctor_id,service_id,treatment_session_id,notes)
    values(v_session.clinic_id,v_session.branch_id,v_product_id,'consumption',coalesce(nullif(new.quantity,0),1),v_session.doctor_id,new.service_id,new.session_id,'Automatic treatment consumption');
  end if;
  return new;
end $$;

drop trigger if exists treatment_item_inventory_trigger on public.treatment_items;
create trigger treatment_item_inventory_trigger after insert on public.treatment_items for each row execute function public.consume_inventory_from_treatment_item();

alter table public.inventory_suppliers enable row level security;
alter table public.inventory_products enable row level security;
alter table public.inventory_purchase_orders enable row level security;
alter table public.inventory_purchase_order_items enable row level security;
alter table public.inventory_movements enable row level security;

do $$ declare t text; begin
  foreach t in array array['inventory_suppliers','inventory_products','inventory_purchase_orders','inventory_purchase_order_items','inventory_movements'] loop
    execute format('drop policy if exists "Authenticated users manage %1$s" on public.%1$I', t);
    execute format('create policy "Authenticated users manage %1$s" on public.%1$I for all to authenticated using (true) with check (true)', t);
  end loop;
end $$;

create index if not exists inventory_products_scope_idx on public.inventory_products(clinic_id, branch_id, is_active);
create index if not exists inventory_products_expiry_idx on public.inventory_products(expiry_date) where is_active;
create index if not exists inventory_movements_product_date_idx on public.inventory_movements(product_id, occurred_at desc);
create index if not exists inventory_movements_doctor_idx on public.inventory_movements(doctor_id) where doctor_id is not null;
create index if not exists inventory_movements_service_idx on public.inventory_movements(service_id) where service_id is not null;

select 'inventory_phase5_ready' as status;
