begin;
alter table public.clinic_public_profiles add column if not exists google_place_id text;
alter table public.clinic_public_profiles add column if not exists google_review_url text;
alter table public.patient_messages add column if not exists metadata jsonb not null default '{}'::jsonb;
create table if not exists public.patient_google_review_referrals(id bigint generated by default as identity primary key,clinic_id bigint not null references public.clinics(id) on delete restrict,customer_id bigint not null references public.customers(id) on delete cascade,appointment_id bigint references public.appointments(id) on delete set null,opened_at timestamptz not null default now());
alter table public.patient_google_review_referrals enable row level security;
drop policy if exists patient_google_review_referrals_self on public.patient_google_review_referrals;
create policy patient_google_review_referrals_self on public.patient_google_review_referrals for select to authenticated using(customer_id=public.current_patient_customer_id());
create or replace function public.patient_google_review_destination(p_appointment_id bigint default null) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_customer_id bigint:=public.current_patient_customer_id();v_clinic_id bigint;v_url text;
begin
 if v_customer_id is null then raise exception 'Patient account is not linked';end if;
 select clinic_id into v_clinic_id from customers where id=v_customer_id;
 if p_appointment_id is not null and not exists(select 1 from appointments where id=p_appointment_id and customer_id=v_customer_id and status='completed') then raise exception 'Only completed visits can be reviewed';end if;
 select coalesce(nullif(google_review_url,''),case when nullif(google_place_id,'') is not null then 'https://search.google.com/local/writereview?placeid='||google_place_id end) into v_url from clinic_public_profiles where clinic_id=v_clinic_id;
 if v_url is null then raise exception 'Google review link is not configured';end if;
 insert into patient_google_review_referrals(clinic_id,customer_id,appointment_id) values(v_clinic_id,v_customer_id,p_appointment_id);
 return jsonb_build_object('url',v_url);
end;$$;
revoke all on function public.patient_google_review_destination(bigint) from public;
grant execute on function public.patient_google_review_destination(bigint) to authenticated;
commit;
