begin;

alter table public.services add column if not exists code text;
alter table public.services add column if not exists provider_type text not null default 'department';
alter table public.services add column if not exists price_starting_from boolean not null default false;
alter table public.staff add column if not exists contract_type text;

create unique index if not exists services_clinic_code_unique
  on public.services (clinic_id, code);

create table if not exists public.devices (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  clinic_id bigint not null references public.clinics(id) on delete restrict,
  branch_id bigint not null references public.branches(id) on delete restrict,
  name text not null,
  code text not null,
  is_active boolean not null default true,
  capacity integer not null default 1 check (capacity > 0),
  unique (clinic_id, branch_id, code)
);

create table if not exists public.staff_services (
  staff_id bigint not null references public.staff(id) on delete cascade,
  service_id bigint not null references public.services(id) on delete cascade,
  is_active boolean not null default true,
  duration_minutes integer not null default 30 check (duration_minutes > 0),
  primary key (staff_id, service_id)
);

create table if not exists public.service_devices (
  service_id bigint not null references public.services(id) on delete cascade,
  device_id bigint not null references public.devices(id) on delete cascade,
  is_required boolean not null default true,
  primary key (service_id, device_id)
);

create table if not exists public.service_prices (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  clinic_id bigint not null references public.clinics(id) on delete restrict,
  branch_id bigint not null references public.branches(id) on delete restrict,
  service_id bigint not null references public.services(id) on delete cascade,
  staff_id bigint references public.staff(id) on delete cascade,
  price numeric(12,2) not null check (price >= 0),
  is_starting_from boolean not null default false,
  price_type text not null check (price_type in ('department', 'percentage_doctor', 'salary_doctor')),
  is_active boolean not null default true
);

create unique index if not exists service_prices_scope_unique
  on public.service_prices (clinic_id, branch_id, service_id, coalesce(staff_id, 0));

alter table public.appointments add column if not exists device_id bigint;
alter table public.treatment_sessions add column if not exists device_id bigint;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'appointments_device_id_fkey') then
    alter table public.appointments
      add constraint appointments_device_id_fkey foreign key (device_id)
      references public.devices(id) on delete set null;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'treatment_sessions_device_id_fkey') then
    alter table public.treatment_sessions
      add constraint treatment_sessions_device_id_fkey foreign key (device_id)
      references public.devices(id) on delete set null;
  end if;
end $$;

do $$
declare
  v_clinic_id bigint;
  v_branch_id bigint;
begin
  select id into v_clinic_id from public.clinics where code = 'PANTHERA' limit 1;
  select id into v_branch_id from public.branches where clinic_id = v_clinic_id and code = 'MAIN' limit 1;
  if v_clinic_id is null or v_branch_id is null then
    raise exception 'Panthera clinic or MAIN branch was not found';
  end if;

  insert into public.staff (staff_name, role, clinic_id, branch_id, is_active, contract_type)
  select item.name, 'doctor', v_clinic_id, v_branch_id, true, item.contract_type
  from (values
    ('Dr Fatima Alsatouf', 'percentage'),
    ('Dr Maram', 'percentage'),
    ('Dr Fatima Khaled', 'salary')
  ) as item(name, contract_type)
  where not exists (
    select 1 from public.staff s
    where s.clinic_id = v_clinic_id and lower(trim(s.staff_name)) = lower(item.name)
  );

  update public.staff s
  set role = 'doctor', branch_id = v_branch_id, is_active = true,
      contract_type = item.contract_type
  from (values
    ('Dr Fatima Alsatouf', 'percentage'),
    ('Dr Maram', 'percentage'),
    ('Dr Fatima Khaled', 'salary')
  ) as item(name, contract_type)
  where s.clinic_id = v_clinic_id and lower(trim(s.staff_name)) = lower(item.name);

  insert into public.devices (clinic_id, branch_id, name, code, is_active)
  values
    (v_clinic_id, v_branch_id, 'PicoWay', 'PICOWAY', true),
    (v_clinic_id, v_branch_id, 'Clarity II', 'CLARITY-II', true),
    (v_clinic_id, v_branch_id, 'Fraxis', 'FRAXIS', true)
  on conflict (clinic_id, branch_id, code) do update
    set name = excluded.name, is_active = true;

  insert into public.services
    (clinic_id, code, name, category, default_price, duration_minutes, is_active, provider_type, price_starting_from)
  select v_clinic_id, x.code, x.name, x.category, x.price, 30, true, x.provider_type, x.starting_from
  from (values
    ('P0015','Shaving Services','Laser Hair Removal',100::numeric,'department',false),
    ('P0014','Laser Head Cover','Laser Hair Removal',60::numeric,'department',false),
    ('P009','Male Full Body Hair Removal','Laser Hair Removal',700::numeric,'department',false),
    ('P007','Small Area Hair Removal','Laser Hair Removal',150::numeric,'department',false),
    ('P008','Female Full Body Hair Removal','Laser Hair Removal',600::numeric,'department',false),
    ('P0010','Female Full Body Hair Removal - Morning','Laser Hair Removal',500::numeric,'department',false),
    ('P0011','Male One Area Hair Removal','Laser Hair Removal',400::numeric,'department',false),
    ('P0012','Female Full Body Hair Removal - Evening','Laser Hair Removal',600::numeric,'department',false),
    ('P006','Female One Area Hair Removal','Laser Hair Removal',300::numeric,'department',false),
    ('P00107','Eyebrows Hair Bleaching','Bleaching',150::numeric,'department',false),
    ('P00106','Face Hair Bleaching','Bleaching',250::numeric,'department',false),
    ('P00304','ProFacial Royal with Zain Obagi','ProFacial',699::numeric,'department',false),
    ('P00303','ProFacial Hair','ProFacial',499::numeric,'department',false),
    ('P00302','ProFacial Underarms','ProFacial',499::numeric,'department',false),
    ('P00301','ProFacial Face with Classic Mask','ProFacial',250::numeric,'department',false),
    ('P00102','Tattoo Removal - Large Area','Tattoo Removal',1000::numeric,'doctor',true),
    ('P00101','Tattoo Removal - Small Area','Tattoo Removal',699::numeric,'doctor',true)
  ) as x(code, name, category, price, provider_type, starting_from)
  on conflict (clinic_id, code) do update set
    name = excluded.name,
    category = excluded.category,
    default_price = excluded.default_price,
    duration_minutes = excluded.duration_minutes,
    is_active = true,
    provider_type = excluded.provider_type,
    price_starting_from = excluded.price_starting_from;

  insert into public.staff_services (staff_id, service_id, is_active, duration_minutes)
  select st.id, sv.id, true, 30
  from public.staff st
  cross join public.services sv
  where st.clinic_id = v_clinic_id
    and lower(trim(st.staff_name)) in ('dr fatima alsatouf', 'dr maram', 'dr fatima khaled')
    and sv.clinic_id = v_clinic_id and sv.code in ('P00102', 'P00101')
  on conflict (staff_id, service_id) do update set is_active = true;

  insert into public.service_devices (service_id, device_id, is_required)
  select sv.id, d.id, true
  from public.services sv
  join public.devices d on d.clinic_id = v_clinic_id and d.branch_id = v_branch_id
  where sv.clinic_id = v_clinic_id and (
    (sv.category = 'Laser Hair Removal' and d.code = 'CLARITY-II') or
    (sv.category in ('Bleaching', 'Tattoo Removal') and d.code = 'PICOWAY')
  )
  on conflict (service_id, device_id) do update set is_required = true;

  merge into public.service_prices target
  using (
    select v_clinic_id clinic_id, v_branch_id branch_id, sv.id service_id,
      null::bigint staff_id, x.price, x.starting_from, 'department'::text price_type
    from (values
      ('P0015',100::numeric,false),('P0014',60::numeric,false),('P009',700::numeric,false),
      ('P007',150::numeric,false),('P008',600::numeric,false),('P0010',500::numeric,false),
      ('P0011',400::numeric,false),('P0012',600::numeric,false),('P006',300::numeric,false),
      ('P00107',150::numeric,false),('P00106',250::numeric,false),
      ('P00304',699::numeric,false),('P00303',499::numeric,false),
      ('P00302',499::numeric,false),('P00301',250::numeric,false)
    ) x(code, price, starting_from)
    join public.services sv on sv.clinic_id = v_clinic_id and sv.code = x.code
    union all
    select v_clinic_id, v_branch_id, sv.id, st.id, x.price, true,
      case when st.contract_type = 'salary' then 'salary_doctor' else 'percentage_doctor' end
    from (values
      ('Dr Fatima Alsatouf','P00102',1500::numeric),('Dr Maram','P00102',1500::numeric),
      ('Dr Fatima Khaled','P00102',1000::numeric),('Dr Fatima Alsatouf','P00101',799::numeric),
      ('Dr Maram','P00101',799::numeric),('Dr Fatima Khaled','P00101',699::numeric)
    ) x(staff_name, code, price)
    join public.staff st on st.clinic_id = v_clinic_id and lower(trim(st.staff_name)) = lower(x.staff_name)
    join public.services sv on sv.clinic_id = v_clinic_id and sv.code = x.code
  ) source
  on target.clinic_id = source.clinic_id and target.branch_id = source.branch_id
    and target.service_id = source.service_id and target.staff_id is not distinct from source.staff_id
  when matched then update set price = source.price, is_starting_from = source.starting_from,
    price_type = source.price_type, is_active = true
  when not matched then insert (clinic_id, branch_id, service_id, staff_id, price, is_starting_from, price_type, is_active)
    values (source.clinic_id, source.branch_id, source.service_id, source.staff_id,
      source.price, source.starting_from, source.price_type, true);
end $$;

alter table public.devices enable row level security;
alter table public.staff_services enable row level security;
alter table public.service_devices enable row level security;
alter table public.service_prices enable row level security;

drop policy if exists "Clinic users manage devices" on public.devices;
create policy "Clinic users manage devices" on public.devices for all to authenticated
using (exists (select 1 from public.user_clinic_access a where a.user_id = auth.uid() and a.clinic_id = devices.clinic_id and (a.branch_id is null or a.branch_id = devices.branch_id)))
with check (exists (select 1 from public.user_clinic_access a where a.user_id = auth.uid() and a.clinic_id = devices.clinic_id and (a.branch_id is null or a.branch_id = devices.branch_id)));

drop policy if exists "Clinic users manage staff services" on public.staff_services;
create policy "Clinic users manage staff services" on public.staff_services for all to authenticated
using (exists (select 1 from public.staff s join public.user_clinic_access a on a.clinic_id = s.clinic_id where s.id = staff_services.staff_id and a.user_id = auth.uid() and (a.branch_id is null or a.branch_id = s.branch_id)))
with check (exists (select 1 from public.staff s join public.user_clinic_access a on a.clinic_id = s.clinic_id where s.id = staff_services.staff_id and a.user_id = auth.uid() and (a.branch_id is null or a.branch_id = s.branch_id)));

drop policy if exists "Clinic users manage service devices" on public.service_devices;
create policy "Clinic users manage service devices" on public.service_devices for all to authenticated
using (exists (select 1 from public.devices d join public.user_clinic_access a on a.clinic_id = d.clinic_id where d.id = service_devices.device_id and a.user_id = auth.uid() and (a.branch_id is null or a.branch_id = d.branch_id)))
with check (exists (select 1 from public.devices d join public.user_clinic_access a on a.clinic_id = d.clinic_id where d.id = service_devices.device_id and a.user_id = auth.uid() and (a.branch_id is null or a.branch_id = d.branch_id)));

drop policy if exists "Clinic users manage service prices" on public.service_prices;
create policy "Clinic users manage service prices" on public.service_prices for all to authenticated
using (exists (select 1 from public.user_clinic_access a where a.user_id = auth.uid() and a.clinic_id = service_prices.clinic_id and (a.branch_id is null or a.branch_id = service_prices.branch_id)))
with check (exists (select 1 from public.user_clinic_access a where a.user_id = auth.uid() and a.clinic_id = service_prices.clinic_id and (a.branch_id is null or a.branch_id = service_prices.branch_id)));

commit;

select 'doctors' check_name, count(*) row_count from public.staff
where clinic_id = (select id from public.clinics where code = 'PANTHERA' limit 1)
  and lower(trim(staff_name)) in ('dr fatima alsatouf','dr maram','dr fatima khaled')
union all
select 'services', count(*) from public.services
where clinic_id = (select id from public.clinics where code = 'PANTHERA' limit 1)
  and code in ('P0015','P0014','P009','P007','P008','P0010','P0011','P0012','P006','P00107','P00106','P00304','P00303','P00302','P00301','P00102','P00101')
union all
select 'devices', count(*) from public.devices
where clinic_id = (select id from public.clinics where code = 'PANTHERA' limit 1)
union all
select 'prices', count(*) from public.service_prices
where clinic_id = (select id from public.clinics where code = 'PANTHERA' limit 1);
