"use client";
import Link from"next/link";import{useState}from"react";import{Bot,BrainCircuit,Building2,CalendarCheck,Loader2,Megaphone,Send,Stethoscope,WalletCards}from"lucide-react";
import{Button}from"@/components/ui/button";import{useClinic}from"@/features/clinic/hooks/useClinic";import{askAgent}from"../api/agents.api";import{useAgentWorkspace}from"../hooks/useAgentWorkspace";import type{AgentAnswer,AgentKind}from"../types/agents";
const agents:Array<{id:AgentKind;name:string;description:string;icon:typeof Bot;color:string;questions:string[]}>= [
{id:"reception",name:"Reception Agent",description:"Booking, confirmations and follow-ups",icon:CalendarCheck,color:"bg-blue-600",questions:["مين محتاج تأكيد حجز النهاردة؟","إيه أولويات الاستقبال اليوم؟","كيف نقلل الـ no-show؟"]},
{id:"doctor",name:"Doctor Agent",description:"Clinical workflow and treatment readiness",icon:Stethoscope,color:"bg-emerald-600",questions:["ما حالة جلسات العلاج هذا الشهر؟","هل توجد مخاطر تشغيلية قبل الجلسات؟","ما المواد التي تحتاج متابعة مخزون؟"]},
{id:"marketing",name:"Marketing Agent",description:"Campaigns, ROI and segmentation",icon:Megaphone,color:"bg-fuchsia-600",questions:["ما أفضل حملة نركز عليها؟","كيف نحسن تحويل العملاء المحتملين؟","لخص أداء التسويق الحالي."]},
{id:"finance",name:"Finance Agent",description:"Collections and revenue forecast",icon:WalletCards,color:"bg-amber-600",questions:["كيف وضع التحصيل هذا الشهر؟","ما أولويات المتابعة المالية؟","ما المخاطر المالية الحالية؟"]},
{id:"ceo",name:"CEO Agent",description:"Whole-clinic executive intelligence",icon:Building2,color:"bg-slate-950",questions:["كيف حال العيادة اليوم؟","ما أهم 3 قرارات اليوم؟","أين أكبر فرصة نمو الآن؟"]}];
export default function AIAgentsWorkspace(){const{clinic,selectedBranch,isLoading:cl}=useClinic(),c=clinic?.id??0,b=selectedBranch?.id??0;const{data,isLoading,error,refetch}=useAgentWorkspace(c,b);const[selected,setSelected]=useState<AgentKind>("ceo"),[question,setQuestion]=useState("كيف حال العيادة اليوم؟"),[answer,setAnswer]=useState<AgentAnswer|null>(null),[busy,setBusy]=useState(false),[askError,setAskError]=useState("");const current=agents.find(x=>x.id===selected)!;const CurrentIcon=current.icon;
async function ask(){if(!data||!question.trim())return;setBusy(true);setAskError("");setAnswer(null);try{setAnswer(await askAgent(selected,question,data.context));}catch(e){setAskError(e instanceof Error?e.message:"AI agent failed");}finally{setBusy(false);}}
if(cl||isLoading)return <div className="rounded-2xl bg-white p-12 text-center">Loading AI Agents...</div>;if(error||!data)return <div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-red-700"><strong>AI Agent workspace could not load.</strong><p>{error instanceof Error?error.message:"Unexpected error"}</p><Button className="mt-4" onClick={()=>void refetch()}>Retry</Button></div>;
return <div className="space-y-7"><header className="rounded-3xl bg-gradient-to-br from-slate-950 via-indigo-950 to-violet-950 p-8 text-white"><div className="flex items-center gap-4"><span className="rounded-2xl bg-white/10 p-4"><BrainCircuit className="h-9 w-9 text-violet-300"/></span><div><p className="text-sm font-semibold uppercase tracking-widest text-violet-300">Phase 8</p><h1 className="mt-1 text-3xl font-black">Zernio AI Agents</h1><p className="mt-2 text-slate-300">Five specialized agents working from one anonymous clinic intelligence layer.</p></div></div><div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Today",`${data.context.appointmentsToday} bookings`],["Revenue",`${data.context.revenueMonth.toLocaleString()} SAR`],["Follow-ups",data.context.pendingFollowUps],["Leads",data.context.marketingLeads],["Low stock",data.context.lowStockProducts]].map(([l,v])=><div key={String(l)} className="rounded-xl bg-white/10 p-4"><p className="text-xs text-slate-400">{String(l)}</p><strong className="mt-1 block text-lg">{String(v)}</strong></div>)}</div></header>
<section className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{agents.map(a=>{const Icon=a.icon,active=a.id===selected;return <button key={a.id} onClick={()=>{setSelected(a.id);setQuestion(a.questions[0]);setAnswer(null);}} className={`rounded-2xl border p-5 text-left transition ${active?"border-violet-500 bg-violet-50 shadow-md":"bg-white hover:border-violet-200"}`}><span className={`inline-flex rounded-xl p-2.5 text-white ${a.color}`}><Icon/></span><h2 className="mt-4 font-bold">{a.name}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{a.description}</p></button>})}</section>
<section className="grid gap-6 xl:grid-cols-[1.45fr_0.8fr]"><div className="rounded-3xl border bg-white p-7 shadow-sm"><div className="flex items-center gap-3"><span className={`rounded-xl p-2 text-white ${current.color}`}><CurrentIcon/></span><div><h2 className="text-xl font-bold">Ask {current.name}</h2><p className="text-xs text-slate-500">Only anonymous operational metrics are sent to OpenAI.</p></div></div><div className="mt-5 flex flex-wrap gap-2">{current.questions.map(q=><button key={q} onClick={()=>setQuestion(q)} className="rounded-full bg-slate-100 px-3 py-2 text-xs hover:bg-slate-200">{q}</button>)}</div><div className="mt-4 flex gap-3"><textarea value={question} onChange={e=>setQuestion(e.target.value)} rows={3} maxLength={500} className="flex-1 rounded-xl border p-4"/><Button onClick={()=>void ask()} disabled={busy||!question.trim()} className="self-end">{busy?<Loader2 className="animate-spin"/>:<Send/>}Ask</Button></div>{askError&&<p className="mt-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{askError}</p>}{answer&&<div className="mt-6 space-y-5 rounded-2xl bg-slate-50 p-6"><p className="leading-7 text-slate-800">{answer.answer}</p><div className="grid gap-4 md:grid-cols-2"><div><h3 className="font-semibold text-emerald-700">Recommended actions</h3><ul className="mt-2 space-y-2 text-sm">{answer.actions.map(x=><li key={x}>• {x}</li>)}</ul></div><div><h3 className="font-semibold text-amber-700">Risks to watch</h3><ul className="mt-2 space-y-2 text-sm">{answer.risks.map(x=><li key={x}>• {x}</li>)}</ul></div></div><div className="flex flex-wrap gap-2">{answer.metricHighlights.map(x=><span key={x} className="rounded-full bg-white px-3 py-1 text-xs font-medium">{x}</span>)}</div></div>}</div>
<aside className="rounded-3xl bg-slate-950 p-6 text-white"><div className="flex items-center gap-2"><Bot className="text-violet-300"/><h2 className="font-bold">Live action queue</h2></div><p className="mt-1 text-xs text-slate-400">Private names stay in Zernio and are never sent to the model.</p><div className="mt-5 space-y-3">{data.tasks[selected].map(t=><Link key={t.id} href={t.href} className="block rounded-xl bg-white/10 p-4 hover:bg-white/15"><div className="flex justify-between gap-2"><strong className="text-sm">{t.title}</strong><span className={`text-[10px] font-bold uppercase ${t.priority==="high"?"text-red-300":t.priority==="medium"?"text-amber-300":"text-emerald-300"}`}>{t.priority}</span></div><p className="mt-2 text-xs leading-5 text-slate-300">{t.detail}</p></Link>)}</div></aside></section>
<p className="text-center text-xs text-slate-500">AI agents provide operational decision support. They do not diagnose, prescribe, send messages, create bookings, or move money without a user action.</p></div>;
}
