/* eslint-disable @typescript-eslint/no-explicit-any */
import{createClient}from"@/lib/supabase/client";const s=createClient();export type BrainCandidate={id:number;name:string;phone:string;reason:string;score:number;href:string};export type BrainData={customers:any[];appointments:any[];payments:any[];treatments:any[];leads:any[];campaigns:any[]};
export async function getBrainData(c:number,b:number):Promise<BrainData>{const[x,a,p,t,l,m]=await Promise.all([s.from("customers").select("id,first_name,last_name,phone,status,created_at").eq("clinic_id",c).eq("branch_id",b),s.from("appointments").select("id,customer_id,status,appointment_at,services(name)").eq("clinic_id",c).eq("branch_id",b),s.from("payments").select("customer_id,amount,payment_status,payment_date").eq("clinic_id",c).eq("branch_id",b),s.from("treatments").select("customer_id,service_name,status,treatment_date,final_price,price").eq("clinic_id",c).eq("branch_id",b),s.from("marketing_leads").select("source,status,created_at").eq("clinic_id",c).eq("branch_id",b),s.from("marketing_campaigns").select("name,channel,status,spend").eq("clinic_id",c).eq("branch_id",b)]);const e=x.error||a.error||p.error||t.error||l.error||m.error;if(e)throw new Error(e.message);return{customers:x.data??[],appointments:a.data??[],payments:p.data??[],treatments:t.data??[],leads:l.data??[],campaigns:m.data??[]};}
export function askClinicBrain(question:string,d:BrainData){const q=question.toLowerCase(),now=Date.now(),day=86400000;const stats=d.customers.map(c=>{const apps=d.appointments.filter(a=>a.customer_id===c.id),paid=d.payments.filter(p=>p.customer_id===c.id&&!['cancelled','refunded'].includes(p.payment_status??'')).reduce((z,p)=>z+Number(p.amount??0),0),tx=d.treatments.filter(t=>t.customer_id===c.id),dates=[...apps.map(a=>a.appointment_at),...tx.map(t=>t.treatment_date)].filter(Boolean).map(x=>new Date(x).getTime()),last=dates.length?Math.max(...dates):0,noShow=apps.filter(a=>['no_show','cancelled'].includes(a.status)).length;return{...c,apps,tx,paid,last,days:last?Math.floor((now-last)/day):999,noShow};});let title="Clinic overview",summary="",candidates:BrainCandidate[]=[];
if(q.includes("sculptra")||q.includes("سكالبترا")){title="Customers potentially relevant for Sculptra review";candidates=stats.filter(x=>x.status!=="inactive"&&(x.tx.some((t:any)=>String(t.service_name).toLowerCase().includes("filler"))||x.paid>=3000)).map(x=>({id:x.id,name:`${x.first_name??''} ${x.last_name??''}`.trim(),phone:x.phone??'',reason:"Previous aesthetic treatment/value pattern; clinical assessment is still required.",score:Math.min(95,50+x.tx.length*8+Math.floor(x.paid/1000)),href:`/customers/${x.id}`})).sort((a,b)=>b.score-a.score).slice(0,20);summary=`وجدنا ${candidates.length} عميلًا للمراجعة التسويقية فقط. النتيجة ليست توصية طبية ويجب تقييم الطبيب.`;}
else if(q.includes("not return")||q.includes("may not return")||q.includes("مش هيرجع")||q.includes("عدم العودة")){title="Customers at risk of not returning";candidates=stats.filter(x=>x.status!=="inactive"&&(x.days>90||x.noShow>0)).map(x=>({id:x.id,name:`${x.first_name??''} ${x.last_name??''}`.trim(),phone:x.phone??'',reason:x.days>90?`No recorded visit for ${x.days} days.`:`${x.noShow} missed/cancelled appointment(s).`,score:Math.min(99,40+Math.min(x.days,365)/6+x.noShow*15),href:`/customers/${x.id}`})).sort((a,b)=>b.score-a.score).slice(0,30);summary=`يوجد ${candidates.length} عميلًا يحتاجون متابعة احتفاظ.`;}
else if(q.includes("campaign")||q.includes("حملة")){title="Recommended campaign";const lost=stats.filter(x=>x.days>120&&x.status!=="inactive").length,top=[...new Map(d.leads.map((x:any)=>[x.source,d.leads.filter((y:any)=>y.source===x.source).length])).entries()].sort((a,b)=>Number(b[1])-Number(a[1]))[0];summary=lost?`ابدأ حملة Win-back للعملاء غير النشطين لأكثر من 120 يومًا (${lost} عميل). استخدم عرض مراجعة أو استشارة، وقِس الحجز والتحصيل.`:`أفضل خطوة هي حملة متابعة للعملاء المحتملين الحاليين. المصدر الأعلى حاليًا: ${top?.[0]??'لا توجد بيانات كافية'}.`;}
else if(q.includes("revenue")||q.includes("ايراد")||q.includes("إيراد")){title="Revenue prediction";const month=new Date(new Date().getFullYear(),new Date().getMonth(),1).getTime(),revenue=d.payments.filter(p=>new Date(p.payment_date).getTime()>=month&&!['cancelled','refunded'].includes(p.payment_status??'')).reduce((z,p)=>z+Number(p.amount??0),0),days=new Date().getDate(),totalDays=new Date(new Date().getFullYear(),new Date().getMonth()+1,0).getDate(),forecast=days?revenue/days*totalDays:0;summary=`إيراد الشهر المسجل ${Math.round(revenue).toLocaleString()} ريال، والتوقع التشغيلي بنهاية الشهر ${Math.round(forecast).toLocaleString()} ريال حسب معدل الأيام الحالي.`;}
else{title="How is the clinic today?";const today=new Date();today.setHours(0,0,0,0);const todayApps=d.appointments.filter(a=>new Date(a.appointment_at)>=today),revenue=d.payments.filter(p=>!['cancelled','refunded'].includes(p.payment_status??'')).reduce((z,p)=>z+Number(p.amount??0),0);summary=`لديك ${todayApps.length} موعدًا من اليوم فصاعدًا، ${d.customers.length} عميلًا، وإجمالي مدفوعات مسجلة ${Math.round(revenue).toLocaleString()} ريال. راجع التأكيدات والمتابعات والمخزون قبل بداية التشغيل.`;}
return{title,summary,candidates};}
