import { createClient } from "@/lib/supabase/client";
export type BrainCandidate={id:number;name:string;phone:string;reason:string;score:number;href:string};
type Customer={id:number;first_name:string|null;last_name:string|null;phone:string|null;status:string|null;created_at:string};
type Appointment={id:number;customer_id:number;status:string;appointment_at:string;services:{name:string}|null};
type Payment={customer_id:number;amount:number;payment_status:string|null;payment_date:string|null};
type Treatment={customer_id:number;service_name:string|null;status:string;treatment_date:string|null;final_price:number|null;price:number|null};
type Lead={source:string|null;status:string;created_at:string};type Campaign={name:string;channel:string|null;status:string;spend:number|null};
export type BrainData={customers:Customer[];appointments:Appointment[];payments:Payment[];treatments:Treatment[];leads:Lead[];campaigns:Campaign[];financeIncluded:boolean};
export async function getBrainData(clinicId:number,branchId:number,includeFinance=false):Promise<BrainData>{const db=createClient();const[customers,appointments,payments,treatments,leads,campaigns]=await Promise.all([db.from("customers").select("id,first_name,last_name,phone,status,created_at").eq("clinic_id",clinicId).eq("branch_id",branchId),db.from("appointments").select("id,customer_id,status,appointment_at,services(name)").eq("clinic_id",clinicId).eq("branch_id",branchId),includeFinance?db.from("payments").select("customer_id,amount,payment_status,payment_date").eq("clinic_id",clinicId).eq("branch_id",branchId):Promise.resolve({data:[],error:null}),db.from("treatments").select("customer_id,service_name,status,treatment_date,final_price,price").eq("clinic_id",clinicId).eq("branch_id",branchId),db.from("marketing_leads").select("source,status,created_at").eq("clinic_id",clinicId).eq("branch_id",branchId),db.from("marketing_campaigns").select("name,channel,status,spend").eq("clinic_id",clinicId).eq("branch_id",branchId)]);const error=customers.error||appointments.error||payments.error||treatments.error||leads.error||campaigns.error;if(error)throw new Error(error.message);return{customers:(customers.data??[])as Customer[],appointments:(appointments.data??[])as unknown as Appointment[],payments:(payments.data??[])as Payment[],treatments:(treatments.data??[])as Treatment[],leads:(leads.data??[])as Lead[],campaigns:(campaigns.data??[])as Campaign[],financeIncluded:includeFinance};}
export function askClinicBrain(question:string,data:BrainData){const query=question.toLowerCase(),now=Date.now(),day=86400000;const stats=data.customers.map(customer=>{const appointments=data.appointments.filter(item=>item.customer_id===customer.id),paid=data.payments.filter(item=>item.customer_id===customer.id&&!['cancelled','refunded'].includes(item.payment_status??'')).reduce((sum,item)=>sum+Number(item.amount??0),0),treatments=data.treatments.filter(item=>item.customer_id===customer.id),dates=[...appointments.map(item=>item.appointment_at),...treatments.map(item=>item.treatment_date)].filter((value):value is string=>Boolean(value)).map(value=>new Date(value).getTime()),last=dates.length?Math.max(...dates):0,noShow=appointments.filter(item=>['no_show','cancelled'].includes(item.status)).length;return{...customer,appointments,treatments,paid,days:last?Math.floor((now-last)/day):999,noShow};});let title="نظرة عامة على العيادة",summary="",candidates:BrainCandidate[]=[];
if(query.includes("sculptra")||query.includes("سكلبترا")){title="مرضى محتملون لمراجعة خدمة سكلبترا";candidates=stats.filter(item=>item.status!=="inactive"&&(item.treatments.some(treatment=>String(treatment.service_name).toLowerCase().includes("filler"))||(data.financeIncluded&&item.paid>=3000))).map(item=>({id:item.id,name:`${item.first_name??''} ${item.last_name??''}`.trim(),phone:item.phone??'',reason:"نمط علاجات تجميلية سابقة؛ ويظل التقييم السريري إلزاميًا.",score:Math.min(95,50+item.treatments.length*8+(data.financeIncluded?Math.floor(item.paid/1000):0)),href:`/customers/${item.id}`})).sort((a,b)=>b.score-a.score).slice(0,20);summary=`تم العثور على ${candidates.length} مريضًا للمراجعة التسويقية فقط، وليست النتيجة توصية طبية.`;}
else if(query.includes("not return")||query.includes("عدم العودة")||query.includes("مش هيرجع")){title="مرضى معرضون لعدم العودة";candidates=stats.filter(item=>item.status!=="inactive"&&(item.days>90||item.noShow>0)).map(item=>({id:item.id,name:`${item.first_name??''} ${item.last_name??''}`.trim(),phone:item.phone??'',reason:item.days>90?`لا توجد زيارة مسجلة منذ ${item.days} يومًا.`:`لديه ${item.noShow} موعد ملغي أو لم يحضره.`,score:Math.min(99,40+Math.min(item.days,365)/6+item.noShow*15),href:`/customers/${item.id}`})).sort((a,b)=>b.score-a.score).slice(0,30);summary=`يوجد ${candidates.length} مريضًا يحتاجون متابعة احتفاظ.`;}
else if(query.includes("campaign")||query.includes("حملة")){title="الحملة المقترحة";const inactive=stats.filter(item=>item.days>120&&item.status!=="inactive").length;const sources=new Map<string,number>();for(const lead of data.leads){const source=lead.source||"غير محدد";sources.set(source,(sources.get(source)??0)+1)}const top=[...sources].sort((a,b)=>b[1]-a[1])[0];summary=inactive?`ابدأ حملة استعادة للمرضى غير النشطين لأكثر من 120 يومًا (${inactive} مريضًا)، وقِس الحجز والتحويل.`:`ابدأ متابعة للعملاء المحتملين الحاليين. المصدر الأعلى حاليًا: ${top?.[0]??'لا توجد بيانات كافية'}.`;}
else if(query.includes("revenue")||query.includes("ايراد")||query.includes("إيراد")){title="توقع الإيرادات";if(!data.financeIncluded)summary="التحليل المالي غير متاح حسب صلاحيات حسابك.";else{const month=new Date(new Date().getFullYear(),new Date().getMonth(),1).getTime(),revenue=data.payments.filter(item=>item.payment_date&&new Date(item.payment_date).getTime()>=month&&!['cancelled','refunded'].includes(item.payment_status??'')).reduce((sum,item)=>sum+Number(item.amount??0),0),days=new Date().getDate(),monthDays=new Date(new Date().getFullYear(),new Date().getMonth()+1,0).getDate(),forecast=days?revenue/days*monthDays:0;summary=`إيراد الشهر المسجل ${Math.round(revenue).toLocaleString("en-US")} ريال، والتوقع التشغيلي ${Math.round(forecast).toLocaleString("en-US")} ريال.`;}}
else{title="كيف حال العيادة اليوم؟";const today=new Date();today.setHours(0,0,0,0);const upcoming=data.appointments.filter(item=>new Date(item.appointment_at)>=today);const finance=data.financeIncluded?`، وإجمالي مدفوعات ${data.payments.filter(item=>!['cancelled','refunded'].includes(item.payment_status??'')).reduce((sum,item)=>sum+Number(item.amount??0),0).toLocaleString("en-US")} ريال`:"";summary=`لديك ${upcoming.length} موعدًا من اليوم فصاعدًا و${data.customers.length} مريضًا${finance}. راجع التأكيدات والمتابعات والمخزون.`;}return{title,summary,candidates};}
