begin;
create table if not exists public.patient_documents(
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.clinics(id) on delete cascade,
  branch_id bigint not null references public.branches(id) on delete restrict,
  customer_id bigint not null references public.customers(id) on delete cascade,
  appointment_id bigint references public.appointments(id) on delete set null,
  treatment_id bigint references public.treatments(id) on delete set null,
  document_type text not null check(document_type in('prescription','quotation','patient_form','clinical_note','patient_link','attachment')),
  title text not null,
  content text,
  amount numeric(14,2),
  external_url text,
  status text not null default 'active',
  created_by_staff_id bigint references public.staff(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists patient_documents_customer_idx on public.patient_documents(customer_id,created_at desc);
alter table public.patient_documents enable row level security;
insert into public.hr_permissions(code,name,module) values
('patient_documents.view','View patient documents','Patients'),
('patient_documents.create','Create patient documents','Patients'),
('patient_documents.manage','Manage patient documents','Patients')
on conflict(code) do update set name=excluded.name,module=excluded.module;
insert into public.hr_role_permissions(role_id,permission_id)
select r.id,p.id from public.hr_roles r cross join public.hr_permissions p where r.name='Admin' and p.code like 'patient_documents.%' on conflict do nothing;
create policy patient_documents_read on public.patient_documents for select to authenticated using(clinic_id=public.current_clinic_id() and public.has_any_hr_permission(array['patient_documents.view','patient_documents.create','patient_documents.manage','customers.manage','medical.view']));
create policy patient_documents_create on public.patient_documents for insert to authenticated with check(clinic_id=public.current_clinic_id() and created_by_staff_id=public.current_staff_id() and public.has_any_hr_permission(array['patient_documents.create','patient_documents.manage','customers.manage','medical.edit']));
create policy patient_documents_update on public.patient_documents for update to authenticated using(clinic_id=public.current_clinic_id() and public.has_any_hr_permission(array['patient_documents.manage','customers.manage','medical.edit'])) with check(clinic_id=public.current_clinic_id() and public.has_any_hr_permission(array['patient_documents.manage','customers.manage','medical.edit']));
drop trigger if exists enterprise_audit_patient_documents on public.patient_documents;
create trigger enterprise_audit_patient_documents after insert or update or delete on public.patient_documents for each row execute function public.enterprise_audit_trigger();
do $$begin if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='patient_documents') then alter publication supabase_realtime add table public.patient_documents;end if;end$$;
commit;
