begin;

alter table public.payments add column if not exists insurance_amount numeric(14,2) not null default 0;
alter table public.payments add column if not exists diagnostic_fee numeric(14,2) not null default 0;
alter table public.payments add column if not exists preauthorization_status text;
alter table public.payments add column if not exists is_signed boolean not null default false;
alter table public.payments add column if not exists is_released boolean not null default false;
alter table public.payments add column if not exists einvoice_reported_at timestamptz;
alter table public.payments add column if not exists assigned_to_staff_id bigint references public.staff(id) on delete set null;
alter table public.payments add column if not exists details text;

insert into public.hr_permissions(code,name,module) values
('expenses.view','View expenses','Finance'),
('expenses.create','Create expenses','Finance'),
('expenses.pay','Record expense payments','Finance'),
('expenses.manage','Manage expenses','Finance'),
('accounting.view','View accounting','Finance'),
('accounting.manage','Manage accounting','Finance'),
('incomes.view','View income register','Finance'),
('incomes.create','Create manual income','Finance'),
('incomes.manage','Manage income register','Finance')
on conflict(code) do update set name=excluded.name,module=excluded.module;

insert into public.hr_role_permissions(role_id,permission_id)
select r.id,p.id from public.hr_roles r cross join public.hr_permissions p
where lower(r.name)='admin' and p.code in('expenses.view','expenses.create','expenses.pay','expenses.manage','accounting.view','accounting.manage','incomes.view','incomes.create','incomes.manage')
on conflict do nothing;

create table if not exists public.clinic_expenses(
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.clinics(id) on delete cascade,
  branch_id bigint not null references public.branches(id) on delete cascade,
  expense_number text not null,
  expense_date date not null default current_date,
  name text not null,
  details text,
  category text not null default 'other',
  account_key text not null default 'other_expense',
  supplier_name text,
  laboratory_name text,
  assigned_to_staff_id bigint references public.staff(id) on delete set null,
  quantity numeric(14,3) not null default 1 check(quantity>0),
  total_amount numeric(14,2) not null default 0 check(total_amount>=0),
  paid_amount numeric(14,2) not null default 0 check(paid_amount>=0),
  receipt_confirmed boolean not null default false,
  received_at timestamptz,
  delivered_at timestamptz,
  status text not null default 'open' check(status in('open','partial','paid','cancelled')),
  created_by_staff_id bigint references public.staff(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(clinic_id,expense_number)
);

create table if not exists public.clinic_expense_payments(
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.clinics(id) on delete cascade,
  branch_id bigint not null references public.branches(id) on delete cascade,
  expense_id bigint not null references public.clinic_expenses(id) on delete cascade,
  payment_date timestamptz not null default now(),
  amount numeric(14,2) not null check(amount>0),
  payment_method text not null default 'cash',
  treasury_key text not null default 'cash',
  reference_number text,
  details text,
  created_by_staff_id bigint references public.staff(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.clinic_incomes(
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.clinics(id) on delete cascade,
  branch_id bigint not null references public.branches(id) on delete cascade,
  income_number text not null,
  income_date timestamptz not null default now(),
  name text not null,
  income_type text not null default 'other',
  account_key text not null default 'other_revenue',
  payment_method text not null default 'cash',
  treasury_key text not null default 'cash',
  amount numeric(14,2) not null check(amount>0),
  reference_number text,
  details text,
  assigned_to_staff_id bigint references public.staff(id) on delete set null,
  created_by_staff_id bigint references public.staff(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(clinic_id,income_number)
);

create index if not exists clinic_expenses_scope_date_idx on public.clinic_expenses(clinic_id,branch_id,expense_date desc);
create index if not exists clinic_expense_payments_expense_idx on public.clinic_expense_payments(expense_id,payment_date desc);
create index if not exists clinic_incomes_scope_date_idx on public.clinic_incomes(clinic_id,branch_id,income_date desc);

alter table public.clinic_expenses enable row level security;
alter table public.clinic_expense_payments enable row level security;
alter table public.clinic_incomes enable row level security;
drop policy if exists clinic_expenses_read on public.clinic_expenses;
drop policy if exists clinic_expenses_write on public.clinic_expenses;
drop policy if exists clinic_expense_payments_read on public.clinic_expense_payments;
drop policy if exists clinic_expense_payments_write on public.clinic_expense_payments;
create policy clinic_expenses_read on public.clinic_expenses for select to authenticated using(clinic_id=public.current_clinic_id() and public.has_any_hr_permission(array['expenses.view','expenses.manage','accounting.view','accounting.manage','payments.manage']));
create policy clinic_expenses_write on public.clinic_expenses for all to authenticated using(clinic_id=public.current_clinic_id() and public.has_any_hr_permission(array['expenses.create','expenses.manage','accounting.manage','payments.manage'])) with check(clinic_id=public.current_clinic_id() and public.has_any_hr_permission(array['expenses.create','expenses.manage','accounting.manage','payments.manage']));
create policy clinic_expense_payments_read on public.clinic_expense_payments for select to authenticated using(clinic_id=public.current_clinic_id() and public.has_any_hr_permission(array['expenses.view','expenses.manage','accounting.view','accounting.manage','payments.manage']));
create policy clinic_expense_payments_write on public.clinic_expense_payments for all to authenticated using(clinic_id=public.current_clinic_id() and public.has_any_hr_permission(array['expenses.pay','expenses.manage','accounting.manage','payments.manage'])) with check(clinic_id=public.current_clinic_id() and public.has_any_hr_permission(array['expenses.pay','expenses.manage','accounting.manage','payments.manage']));
drop policy if exists clinic_incomes_read on public.clinic_incomes;
drop policy if exists clinic_incomes_write on public.clinic_incomes;
create policy clinic_incomes_read on public.clinic_incomes for select to authenticated using(clinic_id=public.current_clinic_id() and public.has_any_hr_permission(array['incomes.view','incomes.manage','accounting.view','accounting.manage','payments.manage']));
create policy clinic_incomes_write on public.clinic_incomes for all to authenticated using(clinic_id=public.current_clinic_id() and public.has_any_hr_permission(array['incomes.create','incomes.manage','accounting.manage','payments.manage'])) with check(clinic_id=public.current_clinic_id() and public.has_any_hr_permission(array['incomes.create','incomes.manage','accounting.manage','payments.manage']));

create or replace function public.validate_clinic_expense_payment() returns trigger language plpgsql security definer set search_path=public as $$
declare expense_total numeric; already_paid numeric;
begin
  select total_amount into expense_total from public.clinic_expenses where id=new.expense_id for update;
  if expense_total is null then raise exception 'Expense not found'; end if;
  select coalesce(sum(amount),0) into already_paid from public.clinic_expense_payments where expense_id=new.expense_id and id<>coalesce(new.id,0);
  if already_paid+new.amount>expense_total then raise exception 'Expense payment exceeds the outstanding amount'; end if;
  return new;
end$$;
drop trigger if exists validate_clinic_expense_payment_trigger on public.clinic_expense_payments;
create trigger validate_clinic_expense_payment_trigger before insert or update of expense_id,amount on public.clinic_expense_payments for each row execute function public.validate_clinic_expense_payment();

create or replace function public.refresh_clinic_expense_totals() returns trigger language plpgsql security definer set search_path=public as $$
declare target_id bigint; paid numeric;
begin
  target_id:=case when tg_op='DELETE' then old.expense_id else new.expense_id end;
  select coalesce(sum(amount),0) into paid from public.clinic_expense_payments where expense_id=target_id;
  update public.clinic_expenses set paid_amount=paid,status=case when status='cancelled' then status when paid<=0 then 'open' when paid>=total_amount then 'paid' else 'partial' end,updated_at=now() where id=target_id;
  return null;
end$$;
drop trigger if exists refresh_clinic_expense_totals_trigger on public.clinic_expense_payments;
create trigger refresh_clinic_expense_totals_trigger after insert or update or delete on public.clinic_expense_payments for each row execute function public.refresh_clinic_expense_totals();

create or replace function public.accounting_expense_payment_post() returns trigger language plpgsql security definer set search_path=public as $$
declare expense_row public.clinic_expenses%rowtype; entry_id bigint; debit_id bigint; credit_id bigint;
begin
  select * into expense_row from public.clinic_expenses where id=new.expense_id;
  delete from public.accounting_journal_entries where clinic_id=new.clinic_id and source_type='expense_payment' and source_id=new.id;
  debit_id:=public.accounting_account_id(new.clinic_id,expense_row.account_key);
  credit_id:=public.accounting_account_id(new.clinic_id,case when new.treasury_key in('bank','gateway_clearing','cash') then new.treasury_key else 'cash' end);
  insert into public.accounting_journal_entries(clinic_id,branch_id,entry_number,entry_date,description_en,description_ar,status,source_type,source_id,posted_at)
  values(new.clinic_id,new.branch_id,'EXP-'||new.id,new.payment_date::date,'Expense payment: '||expense_row.name,'دفعة مصروف: '||expense_row.name,'posted','expense_payment',new.id,now()) returning id into entry_id;
  insert into public.accounting_journal_lines(entry_id,clinic_id,account_id,staff_id,debit,credit,memo_en,memo_ar) values
  (entry_id,new.clinic_id,debit_id,expense_row.assigned_to_staff_id,new.amount,0,expense_row.name,expense_row.name),
  (entry_id,new.clinic_id,credit_id,expense_row.assigned_to_staff_id,0,new.amount,coalesce(new.reference_number,new.payment_method),coalesce(new.reference_number,new.payment_method));
  return new;
end$$;
drop trigger if exists accounting_expense_payment_trigger on public.clinic_expense_payments;
create trigger accounting_expense_payment_trigger after insert or update of amount,payment_method,treasury_key,payment_date,reference_number on public.clinic_expense_payments for each row execute function public.accounting_expense_payment_post();

create or replace function public.accounting_finance_source_cleanup() returns trigger language plpgsql security definer set search_path=public as $$
begin
  delete from public.accounting_journal_entries
  where clinic_id=old.clinic_id
    and source_type=case when tg_table_name='clinic_incomes' then 'manual_income' else 'expense_payment' end
    and source_id=old.id;
  return old;
end$$;
drop trigger if exists accounting_expense_payment_cleanup_trigger on public.clinic_expense_payments;
create trigger accounting_expense_payment_cleanup_trigger after delete on public.clinic_expense_payments for each row execute function public.accounting_finance_source_cleanup();

create or replace function public.accounting_manual_income_post() returns trigger language plpgsql security definer set search_path=public as $$
declare entry_id bigint; debit_id bigint; credit_id bigint;
begin
  delete from public.accounting_journal_entries where clinic_id=new.clinic_id and source_type='manual_income' and source_id=new.id;
  debit_id:=public.accounting_account_id(new.clinic_id,case when new.treasury_key in('bank','gateway_clearing','cash') then new.treasury_key else 'cash' end);
  credit_id:=public.accounting_account_id(new.clinic_id,new.account_key);
  insert into public.accounting_journal_entries(clinic_id,branch_id,entry_number,entry_date,description_en,description_ar,status,source_type,source_id,posted_at)
  values(new.clinic_id,new.branch_id,'INC-'||new.id,new.income_date::date,'Manual income: '||new.name,'دخل مباشر: '||new.name,'posted','manual_income',new.id,now()) returning id into entry_id;
  insert into public.accounting_journal_lines(entry_id,clinic_id,account_id,staff_id,debit,credit,memo_en,memo_ar) values
  (entry_id,new.clinic_id,debit_id,new.assigned_to_staff_id,new.amount,0,coalesce(new.reference_number,new.payment_method),coalesce(new.reference_number,new.payment_method)),
  (entry_id,new.clinic_id,credit_id,new.assigned_to_staff_id,0,new.amount,new.name,new.name);
  return new;
end$$;
drop trigger if exists accounting_manual_income_trigger on public.clinic_incomes;
create trigger accounting_manual_income_trigger after insert or update of amount,payment_method,treasury_key,income_date,reference_number,account_key on public.clinic_incomes for each row execute function public.accounting_manual_income_post();
drop trigger if exists accounting_manual_income_cleanup_trigger on public.clinic_incomes;
create trigger accounting_manual_income_cleanup_trigger after delete on public.clinic_incomes for each row execute function public.accounting_finance_source_cleanup();

do $$declare table_name text;begin foreach table_name in array array['clinic_expenses','clinic_expense_payments','clinic_incomes'] loop if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename=table_name) then execute format('alter publication supabase_realtime add table public.%I',table_name); end if; end loop;end$$;

commit;
