begin;

create table if not exists public.security_events(
  id bigint generated by default as identity primary key,
  event_type text not null check(char_length(event_type) between 3 and 80),
  severity text not null default 'warning' check(severity in('info','warning','critical')),
  actor_key_hash text,
  ip_hash text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists security_events_created_idx on public.security_events(created_at desc);
create index if not exists security_events_type_idx on public.security_events(event_type,created_at desc);
alter table public.security_events enable row level security;
revoke all on public.security_events from public,anon,authenticated;
grant select,insert on public.security_events to service_role;
grant usage,select on sequence public.security_events_id_seq to service_role;

create or replace function public.mark_staff_record_access_changed()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if old.is_active is distinct from new.is_active
    or old.employment_status is distinct from new.employment_status
    or old.email is distinct from new.email
    or old.role is distinct from new.role then
    new.access_changed_at=clock_timestamp();
  end if;
  return new;
end;
$$;

drop trigger if exists staff_record_access_changed on public.staff;
create trigger staff_record_access_changed
before update of is_active,employment_status,email,role on public.staff
for each row execute function public.mark_staff_record_access_changed();

create or replace function public.finalize_moyasar_payment(
  p_gateway_invoice_id text,
  p_status text,
  p_gateway_payload jsonb,
  p_reference_number text
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_intent public.patient_payment_intents%rowtype;
  v_payment_id bigint;
  v_now timestamptz:=clock_timestamp();
begin
  if p_status not in('paid','failed','expired','cancelled','pending') then
    raise exception 'Unsupported payment status';
  end if;

  select * into v_intent
  from public.patient_payment_intents
  where gateway_invoice_id=p_gateway_invoice_id
  for update;

  if not found then raise exception 'Unknown payment intent'; end if;
  if v_intent.status='paid' then
    return jsonb_build_object('status','paid','alreadyFinalized',true);
  end if;

  if p_status<>'paid' then
    update public.patient_payment_intents
    set status=p_status,gateway_payload=p_gateway_payload,updated_at=v_now
    where id=v_intent.id;
    return jsonb_build_object('status',p_status,'alreadyFinalized',false);
  end if;

  update public.patient_appointment_payments
  set payment_status='paid',updated_at=v_now
  where id=v_intent.appointment_payment_id;

  select id into v_payment_id
  from public.payments
  where appointment_id=v_intent.appointment_id
    and lower(coalesce(payment_status,'')) not in('cancelled','refunded')
  order by id
  limit 1
  for update;

  if v_payment_id is null then
    insert into public.payments(
      customer_id,appointment_id,amount,paid_amount,balance_due,currency,
      payment_method,payment_status,payment_date,reference_number,source_system,
      clinic_id,branch_id
    ) values(
      v_intent.customer_id,v_intent.appointment_id,v_intent.amount,v_intent.amount,0,
      v_intent.currency,'online','paid',v_now,p_reference_number,'moyasar',
      v_intent.clinic_id,v_intent.branch_id
    ) returning id into v_payment_id;
  else
    update public.payments set
      amount=v_intent.amount,paid_amount=v_intent.amount,balance_due=0,
      currency=v_intent.currency,payment_method='online',payment_status='paid',
      payment_date=v_now,reference_number=p_reference_number,source_system='moyasar',
      clinic_id=v_intent.clinic_id,branch_id=v_intent.branch_id
    where id=v_payment_id;
  end if;

  insert into public.patient_notifications(customer_id,title,message,notification_type)
  values(
    v_intent.customer_id,
    'Payment successful · تم الدفع بنجاح',
    'Your online payment was received successfully. · تم استلام دفعتك الإلكترونية بنجاح.',
    'payment'
  );

  update public.patient_payment_intents
  set status='paid',gateway_payload=p_gateway_payload,updated_at=v_now
  where id=v_intent.id;

  return jsonb_build_object('status','paid','paymentId',v_payment_id,'alreadyFinalized',false);
end;
$$;

revoke all on function public.finalize_moyasar_payment(text,text,jsonb,text) from public,anon,authenticated;
grant execute on function public.finalize_moyasar_payment(text,text,jsonb,text) to service_role;

commit;
