begin;
create table if not exists public.patient_receipts(
 id bigint generated by default as identity primary key,
 clinic_id bigint not null references public.clinics(id) on delete cascade,
 branch_id bigint not null references public.branches(id) on delete restrict,
 customer_id bigint not null references public.customers(id) on delete cascade,
 payment_id bigint references public.payments(id) on delete set null,
 title text not null,
 storage_path text not null unique,
 mime_type text not null,
 file_size bigint not null check(file_size>0 and file_size<=10485760),
 notes text,
 created_by_staff_id bigint references public.staff(id) on delete set null,
 created_at timestamptz not null default now()
);
create index if not exists patient_receipts_customer_idx on public.patient_receipts(customer_id,created_at desc);
alter table public.patient_receipts enable row level security;
insert into public.hr_permissions(code,name,module) values ('patient_receipts.view','View patient receipt gallery','Patients'),('patient_receipts.create','Upload patient receipts','Patients'),('patient_receipts.manage','Manage patient receipts','Patients') on conflict(code) do update set name=excluded.name,module=excluded.module;
insert into public.hr_role_permissions(role_id,permission_id) select r.id,p.id from public.hr_roles r cross join public.hr_permissions p where r.name='Admin' and p.code like 'patient_receipts.%' on conflict do nothing;
create policy patient_receipts_read on public.patient_receipts for select to authenticated using(clinic_id=public.current_clinic_id() and public.has_any_hr_permission(array['patient_receipts.view','patient_receipts.create','patient_receipts.manage','payments.view','customers.manage']));
create policy patient_receipts_create on public.patient_receipts for insert to authenticated with check(clinic_id=public.current_clinic_id() and created_by_staff_id=public.current_staff_id() and public.has_any_hr_permission(array['patient_receipts.create','patient_receipts.manage','payments.manage','customers.manage']));
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('patient-receipts','patient-receipts',false,10485760,array['image/jpeg','image/png','image/webp','application/pdf']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy patient_receipts_storage_read on storage.objects for select to authenticated using(bucket_id='patient-receipts' and exists(select 1 from public.patient_receipts r where r.storage_path=name and r.clinic_id=public.current_clinic_id() and public.has_any_hr_permission(array['patient_receipts.view','patient_receipts.create','patient_receipts.manage','payments.view','customers.manage'])));
create policy patient_receipts_storage_insert on storage.objects for insert to authenticated with check(bucket_id='patient-receipts' and (storage.foldername(name))[1]=public.current_clinic_id()::text and public.has_any_hr_permission(array['patient_receipts.create','patient_receipts.manage','payments.manage','customers.manage']));
create policy patient_receipts_storage_delete on storage.objects for delete to authenticated using(bucket_id='patient-receipts' and (storage.foldername(name))[1]=public.current_clinic_id()::text and public.has_any_hr_permission(array['patient_receipts.manage','payments.manage','customers.manage']));
drop trigger if exists enterprise_audit_patient_receipts on public.patient_receipts;
create trigger enterprise_audit_patient_receipts after insert or delete on public.patient_receipts for each row execute function public.enterprise_audit_trigger();
commit;
