begin;

alter table public.customers add column if not exists assigned_doctor_id bigint references public.staff(id) on delete set null;
alter table public.customers add column if not exists referral_source text;
alter table public.customers add column if not exists referral_detail text;
alter table public.customers add column if not exists selected_at timestamptz;

create table if not exists public.patient_tags(
 id bigint generated by default as identity primary key,
 clinic_id bigint not null references public.clinics(id) on delete cascade,
 name text not null,
 color text not null default '#0ea5e9',
 is_active boolean not null default true,
 created_at timestamptz not null default now(),
 unique(clinic_id,name)
);
create table if not exists public.customer_patient_tags(
 customer_id bigint not null references public.customers(id) on delete cascade,
 tag_id bigint not null references public.patient_tags(id) on delete cascade,
 created_at timestamptz not null default now(),
 primary key(customer_id,tag_id)
);
create table if not exists public.patient_wallet_transactions(
 id bigint generated by default as identity primary key,
 clinic_id bigint not null references public.clinics(id) on delete restrict,
 branch_id bigint references public.branches(id) on delete set null,
 customer_id bigint not null references public.customers(id) on delete cascade,
 transaction_type text not null check(transaction_type in('credit','debit','refund','adjustment')),
 amount numeric(14,2) not null check(amount>0),
 description text,
 reference_number text,
 created_by uuid default auth.uid(),
 created_at timestamptz not null default now()
);
create index if not exists patient_wallet_customer_idx on public.patient_wallet_transactions(customer_id,created_at desc);

alter table public.patient_tags enable row level security;
alter table public.customer_patient_tags enable row level security;
alter table public.patient_wallet_transactions enable row level security;
drop policy if exists patient_tags_clinic_scope on public.patient_tags;
create policy patient_tags_clinic_scope on public.patient_tags for all to authenticated using(clinic_id=public.current_clinic_id()) with check(clinic_id=public.current_clinic_id());
drop policy if exists customer_patient_tags_clinic_scope on public.customer_patient_tags;
create policy customer_patient_tags_clinic_scope on public.customer_patient_tags for all to authenticated using(exists(select 1 from public.customers c where c.id=customer_id and c.clinic_id=public.current_clinic_id())) with check(exists(select 1 from public.customers c where c.id=customer_id and c.clinic_id=public.current_clinic_id()));
drop policy if exists patient_wallet_staff_scope on public.patient_wallet_transactions;
create policy patient_wallet_staff_scope on public.patient_wallet_transactions for all to authenticated using(clinic_id=public.current_clinic_id()) with check(clinic_id=public.current_clinic_id());
drop policy if exists patient_wallet_self_read on public.patient_wallet_transactions;
create policy patient_wallet_self_read on public.patient_wallet_transactions for select to authenticated using(customer_id=public.current_patient_customer_id());
grant select,insert,update,delete on public.patient_tags,public.customer_patient_tags to authenticated;
grant select on public.patient_wallet_transactions to authenticated;
grant usage,select on all sequences in schema public to authenticated;

create or replace function public.staff_adjust_patient_wallet(p_customer_id bigint,p_amount numeric,p_type text default 'credit',p_description text default null)
returns bigint language plpgsql security definer set search_path=public as $$
declare c public.customers%rowtype;transaction_id bigint;
begin
 if not public.has_any_hr_permission(array['customers.edit','customers.manage','payments.create','payments.manage']) then raise exception 'Forbidden';end if;
 if p_amount<=0 or p_type not in('credit','debit','refund','adjustment') then raise exception 'Invalid wallet transaction';end if;
 select * into c from public.customers where id=p_customer_id and clinic_id=public.current_clinic_id();
 if c.id is null then raise exception 'Patient not found';end if;
 insert into public.patient_wallet_transactions(clinic_id,branch_id,customer_id,transaction_type,amount,description)
 values(c.clinic_id,c.branch_id,c.id,p_type,p_amount,nullif(trim(p_description),'')) returning id into transaction_id;
 return transaction_id;
end$$;
grant execute on function public.staff_adjust_patient_wallet(bigint,numeric,text,text) to authenticated;

create or replace function public.patient_wallet_summary()
returns jsonb language sql security definer set search_path=public as $$
 select jsonb_build_object(
  'balance',coalesce(sum(case when transaction_type in('credit','refund') then amount else -amount end),0),
  'transactions',coalesce(jsonb_agg(jsonb_build_object('id',id,'type',transaction_type,'amount',amount,'description',description,'date',created_at) order by created_at desc),'[]'::jsonb)
 ) from public.patient_wallet_transactions where customer_id=public.current_patient_customer_id()
$$;
grant execute on function public.patient_wallet_summary() to authenticated;

create or replace view public.customer_directory with (security_invoker=true) as
select c.id,c.clinic_id,c.branch_id,c.customer_code,c.first_name,c.last_name,c.phone,c.phone_normalized,c.email,c.gender,c.status,c.date_of_birth,c.national_id,c.nationality,c.created_at,c.assigned_doctor_id,c.referral_source,c.referral_detail,c.selected_at,
 b.name branch_name,d.staff_name assigned_doctor_name,
 coalesce(fin.total_paid,0) total_paid,coalesce(fin.remaining,0) remaining,
 coalesce(wallet.balance,0) wallet_balance,coalesce(loyalty.points_balance,0) points_available,
 previous_appointment.appointment_at previous_appointment_at,previous_appointment.doctor_name previous_appointment_doctor,
 active_appointment.appointment_at active_appointment_at,active_appointment.doctor_name active_appointment_doctor,
 coalesce(tags.tags,'[]'::jsonb) tags
from public.customers c
left join public.branches b on b.id=c.branch_id
left join public.staff d on d.id=c.assigned_doctor_id
left join lateral(select sum(coalesce(p.paid_amount,case when p.payment_status='paid' then p.amount else 0 end)) total_paid,sum(coalesce(p.balance_due,0)) remaining from public.payments p where p.customer_id=c.id and p.payment_status not in('cancelled','refunded')) fin on true
left join lateral(select sum(case when w.transaction_type in('credit','refund') then w.amount else -w.amount end) balance from public.patient_wallet_transactions w where w.customer_id=c.id) wallet on true
left join public.patient_loyalty_accounts loyalty on loyalty.customer_id=c.id
left join lateral(select a.appointment_at,coalesce(s.staff_name,a.doctor_name) doctor_name from public.appointments a left join public.staff s on s.id=a.doctor_id where a.customer_id=c.id and a.appointment_at<now() order by a.appointment_at desc limit 1) previous_appointment on true
left join lateral(select a.appointment_at,coalesce(s.staff_name,a.doctor_name) doctor_name from public.appointments a left join public.staff s on s.id=a.doctor_id where a.customer_id=c.id and a.appointment_at>=now() and a.status not in('cancelled','no_show','completed') order by a.appointment_at limit 1) active_appointment on true
left join lateral(select jsonb_agg(jsonb_build_object('id',t.id,'name',t.name,'color',t.color) order by t.name) tags from public.customer_patient_tags ct join public.patient_tags t on t.id=ct.tag_id where ct.customer_id=c.id and t.is_active) tags on true;
grant select on public.customer_directory to authenticated;

commit;
