"use client";

import { useMemo, useState } from "react";
import { Plus, Search, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { useClinic } from "@/features/clinic/hooks/useClinic";
import { useMasterData } from "@/features/master-data/hooks/useMasterData";
import { usePermissionAccess } from "@/features/users/hooks/usePermissionAccess";
import { useExpenseActions, useExpenses } from "../hooks/useExpenses";
import type { ClinicExpense } from "../types/expense";

const field="h-11 rounded-xl border px-3 text-sm outline-none focus:border-cyan-500";
const money=(value:number)=>new Intl.NumberFormat("ar-SA-u-nu-latn",{style:"currency",currency:"SAR",maximumFractionDigits:2}).format(Number(value??0));
const date=(value:string|null)=>value?new Intl.DateTimeFormat("ar-SA-u-nu-latn",{dateStyle:"medium",timeZone:"Asia/Riyadh"}).format(new Date(value)):"—";
const accountOptions=[['medical_materials','المواد الطبية'],['salaries','الرواتب'],['rent','الإيجار'],['marketing','التسويق'],['utilities','المرافق'],['depreciation','الإهلاك'],['administrative','المصروفات الإدارية'],['other_expense','مصروفات أخرى']];

export default function ExpenseCenter(){
  const{clinic,selectedBranch}=useClinic();const access=usePermissionAccess();const clinicId=clinic?.id??0,branchId=selectedBranch?.id??0;
  const query=useExpenses(clinicId,branchId);const actions=useExpenseActions();const{data:master}=useMasterData();
  const[search,setSearch]=useState("");const[showAdd,setShowAdd]=useState(false);const[paying,setPaying]=useState<ClinicExpense|null>(null);
  const[expense,setExpense]=useState({name:"",expense_date:new Date().toISOString().slice(0,10),category:"other",account_key:"other_expense",supplier_name:"",laboratory_name:"",assigned_to_staff_id:"",quantity:"1",total_amount:"",details:""});
  const[payment,setPayment]=useState({amount:"",payment_method:"cash",treasury_key:"cash",reference_number:"",details:""});
  const canView=access.can("expenses.view","expenses.manage","accounting.view","accounting.manage","payments.manage");const canCreate=access.can("expenses.create","expenses.manage","accounting.manage","payments.manage");const canPay=access.can("expenses.pay","expenses.manage","accounting.manage","payments.manage");const canManage=access.can("expenses.manage","accounting.manage","payments.manage");
  async function markOperational(item:ClinicExpense,kind:"confirm"|"receive"|"deliver"){
    const now=new Date().toISOString();
    const values=kind==="confirm"?{receipt_confirmed:true}:kind==="receive"?{receipt_confirmed:true,received_at:now}:{receipt_confirmed:true,received_at:item.received_at??now,delivered_at:now};
    try{await actions.update.mutateAsync({id:item.id,values});toast.success(kind==="confirm"?"تم تأكيد الاستلام":kind==="receive"?"تم تسجيل استلام المصروف":"تم تسجيل التسليم");}catch(error){toast.error(error instanceof Error?error.message:"تعذر تحديث حالة المصروف");}
  }
  const rows=useMemo(()=>{const q=search.trim().toLowerCase();return(query.data??[]).filter(x=>!q||[x.name,x.expense_number,x.supplier_name,x.laboratory_name,x.assignee?.staff_name,x.category].filter(Boolean).join(" ").toLowerCase().includes(q));},[query.data,search]);
  const total=rows.reduce((s,x)=>s+Number(x.total_amount),0),paid=rows.reduce((s,x)=>s+Number(x.paid_amount),0);
  if(!canView&&!access.isLoading)return <div className="rounded-2xl bg-amber-50 p-6 text-amber-800">نتائج المصروفات غير متوفرة لك حسب صلاحيات حسابك.</div>;
  const operationalPanel=canManage&&rows.some(x=>!x.receipt_confirmed||!x.received_at||!x.delivered_at)?<div className="space-y-2 rounded-2xl border bg-white p-4"><h3 className="font-black">متابعة الاستلام والتسليم</h3>{rows.filter(x=>!x.receipt_confirmed||!x.received_at||!x.delivered_at).map(x=><div key={x.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-slate-50 p-3"><div><b>{x.name}</b><small className="block text-slate-500" dir="ltr">{x.expense_number}</small></div><div className="flex flex-wrap gap-2">{!x.receipt_confirmed&&<button onClick={()=>void markOperational(x,"confirm")} className="rounded-lg border bg-white px-3 py-2 text-sm font-bold">تأكيد الاستلام</button>}{!x.received_at&&<button onClick={()=>void markOperational(x,"receive")} className="rounded-lg border bg-white px-3 py-2 text-sm font-bold">تم الاستلام</button>}{!x.delivered_at&&<button onClick={()=>void markOperational(x,"deliver")} className="rounded-lg border bg-white px-3 py-2 text-sm font-bold">تم التسليم</button>}</div></div>)}</div>:null;
  return <section className="space-y-4" dir="rtl">
    {operationalPanel}
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-bold text-cyan-700">PANTHERA FINANCE</p><h2 className="text-2xl font-black">مركز المصروفات ومدفوعاتها</h2><p className="text-sm text-slate-500">الموردون والمعامل والموظفون والخزائن والقيود المحاسبية في سجل واحد</p></div>{canCreate&&<button onClick={()=>setShowAdd(v=>!v)} className="rounded-xl bg-slate-950 px-4 py-3 font-bold text-white"><Plus className="me-2 inline size-4"/>مصروف جديد</button>}</div>
    {showAdd&&<form className="grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-3" onSubmit={async e=>{e.preventDefault();try{await actions.create.mutateAsync({clinic_id:clinicId,branch_id:branchId,expense_number:`EXP-${Date.now()}`,expense_date:expense.expense_date,name:expense.name,details:expense.details||null,category:expense.category,account_key:expense.account_key,supplier_name:expense.supplier_name||null,laboratory_name:expense.laboratory_name||null,assigned_to_staff_id:Number(expense.assigned_to_staff_id)||null,quantity:Number(expense.quantity),total_amount:Number(expense.total_amount)});toast.success("تم إنشاء المصروف");setShowAdd(false);setExpense({...expense,name:"",total_amount:"",details:""});}catch(error){toast.error(error instanceof Error?error.message:"تعذر إنشاء المصروف")}}}><input required className={field} placeholder="اسم المصروف" value={expense.name} onChange={e=>setExpense({...expense,name:e.target.value})}/><input required type="date" className={field} value={expense.expense_date} onChange={e=>setExpense({...expense,expense_date:e.target.value})}/><select className={field} value={expense.account_key} onChange={e=>setExpense({...expense,account_key:e.target.value})}>{accountOptions.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><input className={field} placeholder="المورد" value={expense.supplier_name} onChange={e=>setExpense({...expense,supplier_name:e.target.value})}/><input className={field} placeholder="المعمل" value={expense.laboratory_name} onChange={e=>setExpense({...expense,laboratory_name:e.target.value})}/><select className={field} value={expense.assigned_to_staff_id} onChange={e=>setExpense({...expense,assigned_to_staff_id:e.target.value})}><option value="">مخصصة لموظف</option>{master?.staff.filter(x=>x.is_active).map(x=><option key={x.id} value={x.id}>{x.staff_name}</option>)}</select><input required min="0.001" step="0.001" type="number" className={field} placeholder="الكمية" value={expense.quantity} onChange={e=>setExpense({...expense,quantity:e.target.value})}/><input required min="0" step="0.01" type="number" className={field} placeholder="السعر الإجمالي" value={expense.total_amount} onChange={e=>setExpense({...expense,total_amount:e.target.value})}/><input className={field} placeholder="التفاصيل" value={expense.details} onChange={e=>setExpense({...expense,details:e.target.value})}/><button className="rounded-xl bg-cyan-600 py-3 font-bold text-white md:col-span-3">حفظ المصروف</button></form>}
    <div className="grid gap-3 sm:grid-cols-3"><Card label="إجمالي المصروفات" value={money(total)}/><Card label="المدفوع" value={money(paid)}/><Card label="المتبقي" value={money(total-paid)}/></div>
    <label className="flex items-center gap-2 rounded-xl border bg-white px-4"><Search className="size-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث في الاسم أو المورد أو المعمل أو الموظف" className="h-11 w-full outline-none"/></label>
    <div className="max-h-[62vh] overflow-auto rounded-2xl border bg-white"><table className="w-full min-w-[1750px] text-sm"><thead className="sticky top-0 bg-slate-100"><tr>{["الرقم","الاسم","التاريخ","السعر","المدفوع","المتبقي","الكمية","النوع","المورد","المعمل","مخصصة لموظف","تأكيد الاستلام","تم الاستلام","تم التسليم","الحالة","تم الإنشاء","آخر تحديث","إجراء"].map(x=><th key={x} className="p-3 text-start">{x}</th>)}</tr></thead><tbody>{rows.map(x=><tr key={x.id} className="border-t"><td className="p-3 font-bold" dir="ltr">{x.expense_number}</td><td className="p-3 font-bold">{x.name}<small className="block text-slate-500">{x.details}</small></td><td className="p-3">{date(x.expense_date)}</td><td className="p-3">{money(x.total_amount)}</td><td className="p-3 text-emerald-700">{money(x.paid_amount)}</td><td className="p-3 text-rose-700">{money(Number(x.total_amount)-Number(x.paid_amount))}</td><td className="p-3">{x.quantity}</td><td className="p-3">{accountOptions.find(a=>a[0]===x.account_key)?.[1]??x.category}</td><td className="p-3">{x.supplier_name||"—"}</td><td className="p-3">{x.laboratory_name||"—"}</td><td className="p-3">{x.assignee?.staff_name||"—"}</td><td className="p-3">{x.receipt_confirmed?"✓":"✕"}</td><td className="p-3">{date(x.received_at)}</td><td className="p-3">{date(x.delivered_at)}</td><td className="p-3">{x.status==='paid'?"مدفوع":x.status==='partial'?"جزئي":x.status==='cancelled'?"ملغي":"مفتوح"}</td><td className="p-3">{date(x.created_at)}</td><td className="p-3">{date(x.updated_at)}</td><td className="p-3">{canPay&&x.status!=="paid"&&x.status!=="cancelled"?<button onClick={()=>{setPaying(x);setPayment({...payment,amount:String(Math.max(Number(x.total_amount)-Number(x.paid_amount),0))})}} className="rounded-lg bg-emerald-600 px-3 py-2 font-bold text-white"><WalletCards className="me-1 inline size-4"/>تسجيل دفعة</button>:"—"}</td></tr>)}</tbody></table></div>
    {paying&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><form className="w-full max-w-xl space-y-3 rounded-2xl bg-white p-6" onSubmit={async e=>{e.preventDefault();try{await actions.pay.mutateAsync({clinic_id:clinicId,branch_id:branchId,expense_id:paying.id,payment_date:new Date().toISOString(),amount:Number(payment.amount),payment_method:payment.payment_method,treasury_key:payment.treasury_key,reference_number:payment.reference_number||null,details:payment.details||null});toast.success("تم تسجيل دفعة المصروف وترحيلها محاسبيًا");setPaying(null);}catch(error){toast.error(error instanceof Error?error.message:"تعذر تسجيل الدفعة")}}}><h3 className="text-xl font-black">دفع المصروف: {paying.name}</h3><input required min="0.01" max={Math.max(Number(paying.total_amount)-Number(paying.paid_amount),0)} step="0.01" type="number" className={`${field} w-full`} value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/><div className="grid grid-cols-2 gap-3"><select className={field} value={payment.payment_method} onChange={e=>{const method=e.target.value;setPayment({...payment,payment_method:method,treasury_key:method==='cash'?'cash':method==='bank_transfer'?'bank':'gateway_clearing'})}}><option value="cash">نقدي</option><option value="bank_transfer">تحويل بنكي</option><option value="card">بطاقة بنكية</option><option value="other">أخرى</option></select><input className={field} placeholder="المرجع" value={payment.reference_number} onChange={e=>setPayment({...payment,reference_number:e.target.value})}/></div><input className={`${field} w-full`} placeholder="تفاصيل الدفعة" value={payment.details} onChange={e=>setPayment({...payment,details:e.target.value})}/><div className="flex gap-2"><button className="flex-1 rounded-xl bg-emerald-600 py-3 font-bold text-white">حفظ وترحيل</button><button type="button" onClick={()=>setPaying(null)} className="rounded-xl border px-5">إلغاء</button></div></form></div>}
  </section>;
}
function Card({label,value}:{label:string;value:string}){return <div className="rounded-2xl border bg-white p-4"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>}
