"use client";
import { useState } from "react";
import { Landmark, ReceiptText, TrendingDown, TrendingUp } from "lucide-react";
import AccountingDashboard from "./AccountingDashboard";
import ExpenseCenter from "./ExpenseCenter";
import IncomeCenter from "./IncomeCenter";
import { usePermissionAccess } from "@/features/users/hooks/usePermissionAccess";

const tabs=[{id:"accounting",label:"المحاسبة",icon:Landmark},{id:"income",label:"الدخل",icon:TrendingUp},{id:"expenses",label:"المصروفات ومدفوعاتها",icon:TrendingDown}] as const;
export default function FinanceWorkspace(){const access=usePermissionAccess();const allowedTabs=tabs.filter(item=>item.id==="accounting"?access.can("accounting.view","accounting.manage","payments.manage"):item.id==="income"?access.can("incomes.view","incomes.manage","payments.view","payments.manage"):access.can("expenses.view","expenses.manage","payments.manage"));const[tab,setTab]=useState<(typeof tabs)[number]["id"]>("accounting");const active=allowedTabs.some(item=>item.id===tab)?tab:allowedTabs[0]?.id;if(!access.isLoading&&!active)return <div className="rounded-2xl bg-amber-50 p-6 text-amber-800">قسم المالية والمحاسبة غير متوفر لك حسب صلاحيات حسابك.</div>;return <div className="space-y-5" dir="rtl"><section className="overflow-hidden rounded-[28px] bg-[#071826] p-6 text-white shadow-xl"><div className="flex items-center gap-3"><ReceiptText className="size-8 text-cyan-300"/><div><p className="text-xs font-black tracking-[.2em] text-cyan-300">PANTHERA FINANCE</p><h1 className="text-3xl font-black">المالية والمحاسبة</h1><p className="mt-1 text-sm text-slate-300">الفواتير والدخل والمصروفات والبنك والقيود والقوائم مترابطة لحظيًا</p></div></div></section><nav className="flex gap-2 overflow-x-auto rounded-2xl border bg-white p-2 shadow-sm">{allowedTabs.map(item=>{const Icon=item.icon;return <button key={item.id} onClick={()=>setTab(item.id)} className={`flex shrink-0 items-center gap-2 rounded-xl px-5 py-3 font-bold ${active===item.id?"bg-slate-950 text-white":"hover:bg-slate-100"}`}><Icon className="size-4"/>{item.label}</button>})}</nav>{active==="accounting"&&<AccountingDashboard/>}{active==="income"&&<IncomeCenter/>}{active==="expenses"&&<ExpenseCenter/>}</div>}
