"use client";
import{useMemo,useState}from"react";import{useMutation,useQueryClient}from"@tanstack/react-query";import{Calculator,PackageOpen,Plus,Trash2}from"lucide-react";import{toast}from"sonner";
import{Dialog,DialogContent,DialogHeader,DialogTitle,DialogTrigger}from"@/components/ui/dialog";import{Button}from"@/components/ui/button";import{Input}from"@/components/ui/input";import{useCustomers}from"@/features/customers/hooks/useCustomers";import{useAppointments}from"@/features/appointments/hooks/useAppointments";import{useMasterData}from"@/features/appointments/hooks/useMasterData";import{invalidateCustomerWorkspace}from"@/lib/query/invalidateCustomer";import{createMultiServiceInvoice}from"../api/payment.api";
import{useLocale}from"@/components/LocaleProvider";import{usePayments}from"../hooks/usePayments";
import type{Customer}from"@/features/customers/types/customer";
type Line={key:number;serviceId:number;variantId:number|null;quantity:number};const nowLocal=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};let nextKey=1;
const matchingCustomers=(customers:Customer[],raw:string)=>{const q=raw.trim().toLowerCase(),digits=q.replace(/\D/g,"");return customers.filter(c=>!q||`${c.first_name??""} ${c.last_name??""}`.toLowerCase().includes(q)||(digits&&(c.phone??"").replace(/\D/g,"").includes(digits))||(c.national_id??"").toLowerCase().includes(q)||(c.customer_code??"").toLowerCase().includes(q))};
export default function AddPaymentDialog({clinicId,branchId,initialCustomerId,initialAppointmentId,triggerLabelEn="Add payment",triggerLabelAr="إضافة دفعة"}:{clinicId:number;branchId:number;initialCustomerId?:number;initialAppointmentId?:number;triggerLabelEn?:string;triggerLabelAr?:string}){
 const{isArabic,text:localeText}=useLocale();
 const text=(english:string,arabic:string)=>localeText(
  english==="VAT (fixed 15%)"?(isSaudi?"VAT exempt (Saudi)":"VAT (15%)"):english==="VAT is calculated automatically at 15% after discount."?(isSaudi?"Saudi customers are VAT exempt.":english):english,
  arabic==="الضريبة (ثابتة 15٪)"?(isSaudi?"معفى من الضريبة (سعودي)":"الضريبة (15٪)"):arabic==="تُحسب الضريبة تلقائيًا بنسبة 15٪ بعد الخصم."?(isSaudi?"العملاء السعوديون معفيون من الضريبة.":arabic):arabic
 );
 const[open,setOpen]=useState(false),[search,setSearch]=useState(""),[customerId,setCustomerId]=useState(initialCustomerId??0),[appointmentId,setAppointmentId]=useState(initialAppointmentId??0),[lines,setLines]=useState<Line[]>([]),[discount,setDiscount]=useState(0),[paid,setPaid]=useState(0),[method,setMethod]=useState("cash"),[status,setStatus]=useState("paid"),[paymentDate,setPaymentDate]=useState(nowLocal()),[invoice,setInvoice]=useState(""),[reference,setReference]=useState(""),[notes,setNotes]=useState("");
 const{data:customers=[]}=useCustomers(),{data:appointments=[]}=useAppointments(),{data:payments=[]}=usePayments(clinicId,branchId),{data:master}=useMasterData(),qc=useQueryClient();const appointment=appointments.find(a=>a.id===appointmentId);
 const mutation=useMutation({mutationFn:createMultiServiceInvoice,onSuccess:async()=>{await invalidateCustomerWorkspace(qc,customerId);await qc.invalidateQueries({queryKey:["payments"]});await qc.invalidateQueries({queryKey:["billing-due"]})}});
 const customerName=(customer:Customer)=>`${customer.first_name??""} ${customer.last_name??""}`.trim()||text("Customer","عميل");
 const customerOptionLabel=(customer:Customer)=>`${customer.customer_code||"—"} — ${customerName(customer)}`;
 const filteredCustomers=useMemo(()=>matchingCustomers(customers,search).slice(0,50),[customers,search]);const invoicedAppointmentIds=useMemo(()=>new Set(payments.filter(p=>p.appointment_id!==null&&!['cancelled','refunded'].includes(String(p.payment_status).toLowerCase())).map(p=>p.appointment_id)),[payments]);const hasExistingInvoice=initialAppointmentId!=null&&invoicedAppointmentIds.has(initialAppointmentId);const customerAppointments=appointments.filter(a=>a.customer_id===customerId&&(!invoicedAppointmentIds.has(a.id)||a.id===initialAppointmentId));const selectedCustomer=customers.find(c=>c.id===customerId),isSaudi=selectedCustomer?.nationality!=="non_saudi";
 const selectedCustomerDetails=selectedCustomer?[
  {label:text("File number","رقم الملف"),value:selectedCustomer.customer_code||"—"},
  {label:text("Phone","رقم الهاتف"),value:selectedCustomer.phone||"—"},
  {label:text("National ID","رقم الهوية"),value:selectedCustomer.national_id||"—"},
  {label:text("Nationality","الجنسية"),value:selectedCustomer.nationality==="saudi"?text("Saudi","سعودي"):selectedCustomer.nationality==="non_saudi"?text("Non-Saudi","غير سعودي"):text("Not specified","غير محددة")},
  {label:text("Gender","الجنس"),value:selectedCustomer.gender==="male"?text("Male","ذكر"):selectedCustomer.gender==="female"?text("Female","أنثى"):text("Not specified","غير محدد")}
 ]:[];
 const updateCustomerSearch=(value:string)=>{setSearch(value);const matches=matchingCustomers(customers,value);if(value.trim()&&matches.length===1&&matches[0].id!==customerId){setCustomerId(matches[0].id);setAppointmentId(0)}};
 const availableServices=useMemo(()=>{if(!master||!appointment)return[];if(appointment.doctor_id){const ids=new Set(master.staffServices.filter(x=>x.staff_id===appointment.doctor_id).map(x=>x.service_id));return master.services.filter(s=>s.is_active&&ids.has(s.id))}const base=master.services.find(s=>s.id===appointment.service_id);return master.services.filter(s=>s.is_active&&s.provider_type==="department"&&s.category===base?.category)},[master,appointment]);
 const priced=useMemo(()=>lines.map(line=>{const service=master?.services.find(s=>s.id===line.serviceId),variants=(master?.serviceVariants??[]).filter(v=>v.service_id===line.serviceId&&v.is_active),variant=variants.find(v=>v.id===line.variantId);let unit=0;if(variant){const doctorPrice=master?.serviceVariantPrices.find(p=>p.service_variant_id===variant.id&&p.staff_id===appointment?.doctor_id&&p.is_active);const list=Number(doctorPrice?.price??variant.price),match=variant.name.match(/^\s*([0-9]+(?:\.[0-9]+)?)\s*ML\b/i),pack=match?Number(match[1]):1;unit=list/pack}else if(!variants.length&&service){const doctorPrice=master?.servicePrices.find(p=>p.service_id===service.id&&p.staff_id===appointment?.doctor_id),general=master?.servicePrices.find(p=>p.service_id===service.id&&p.staff_id===null);unit=Number(doctorPrice?.price??general?.price??service.default_price)}return{...line,service,variants,variant,unit,total:unit*Math.max(Number(line.quantity)||0,0)}}),[lines,master,appointment?.doctor_id]);const subtotal=priced.reduce((sum,x)=>sum+x.total,0),discountAmount=subtotal*Math.min(Math.max(discount||0,0),100)/100,taxRate=isSaudi?0:.15,tax=Math.max(subtotal-discountAmount,0)*taxRate,total=Math.max(subtotal-discountAmount+tax,0),effectivePaid=status==="paid"?total:Math.min(Math.max(paid||0,0),total),balance=Math.max(total-effectivePaid,0),valid=appointment&&priced.length>0&&priced.every(x=>x.service&&x.unit>0&&x.quantity>0&&(!x.variants.length||x.variant));
 const update=(key:number,values:Partial<Line>)=>setLines(old=>old.map(x=>x.key===key?{...x,...values}:x));const add=()=>setLines(old=>[...old,{key:nextKey++,serviceId:0,variantId:null,quantity:1}]);const remove=(key:number)=>setLines(old=>old.filter(x=>x.key!==key));
 async function submit(){if(hasExistingInvoice)return toast.error(text("An invoice has already been issued for this appointment","تم إصدار فاتورة لهذا الموعد بالفعل"));if(!valid||!appointment)return toast.error(text("Complete the procedures, materials and quantities first","أكمل الإجراءات والمواد والكميات أولًا"));try{await mutation.mutateAsync({customer_id:customerId,appointment_id:appointment.id,items:priced.map(x=>({service_id:x.serviceId,service_variant_id:x.variantId,quantity:x.quantity})),tax_amount:tax,discount_amount:discountAmount,paid_amount:effectivePaid,payment_method:method,payment_status:status,payment_date:new Date(paymentDate).toISOString(),invoice_number:invoice,reference_number:reference,notes});toast.success(text("Invoice issued successfully","تم إصدار الفاتورة بنجاح"));setOpen(false);setSearch("");setInvoice("");setReference("");setNotes("")}catch(e){toast.error(e instanceof Error?e.message:text("Could not issue the invoice","تعذر إصدار الفاتورة"))}}
 return <Dialog open={open} onOpenChange={value=>{if(value&&hasExistingInvoice){toast.info(text("An invoice has already been issued for this appointment","تم إصدار فاتورة لهذا الموعد بالفعل"));return}setOpen(value);if(value){const cid=initialCustomerId??customerId,aid=initialAppointmentId??appointmentId;setCustomerId(cid);setAppointmentId(aid);const selected=appointments.find(a=>a.id===aid);setLines(selected?.service_id?[{key:nextKey++,serviceId:selected.service_id,variantId:null,quantity:1}]:[])}}}><DialogTrigger render={<Button type="button" disabled={hasExistingInvoice}/>}>{hasExistingInvoice?text("Invoice issued","تم إصدار الفاتورة"):text(triggerLabelEn,triggerLabelAr)}</DialogTrigger><DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-3xl" dir={isArabic?"rtl":"ltr"}><DialogHeader><DialogTitle>{text("Multi-procedure visit invoice","فاتورة زيارة متعددة الإجراءات")}</DialogTitle></DialogHeader><div className="space-y-4">
  <div><Input placeholder={text("Search by name, phone, national ID or file number","ابحث بالاسم أو الهاتف أو الهوية أو رقم الملف")} value={search} onChange={e=>updateCustomerSearch(e.target.value)}/><select value={customerId||""} onChange={e=>{setCustomerId(Number(e.target.value));setAppointmentId(0)}} className="mt-2 w-full rounded-md border bg-background px-3 py-2"><option value="">{text("Select customer","اختر العميل")}</option>{filteredCustomers.map(c=><option key={c.id} value={c.id}>{customerOptionLabel(c)}</option>)}</select>{selectedCustomer&&<section className="mt-3 rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="mb-3"><p className="text-xs font-semibold text-slate-500">{text("Selected customer","العميل المحدد")}</p><p className="text-lg font-black text-slate-950">{customerName(selectedCustomer)}</p></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{selectedCustomerDetails.map(item=><div key={item.label} className="rounded-xl border border-slate-200 bg-white p-3"><p className="text-xs font-semibold text-slate-500">{item.label}</p><p className="mt-1 font-bold text-slate-950">{item.value}</p></div>)}</div></section>}</div>
  <select value={appointmentId||""} onChange={e=>{const id=Number(e.target.value);setAppointmentId(id);const selected=appointments.find(a=>a.id===id);setLines(selected?.service_id?[{key:nextKey++,serviceId:selected.service_id,variantId:null,quantity:1}]:[])}} disabled={!customerId} className="w-full rounded-md border bg-background px-3 py-2 disabled:opacity-50"><option value="">{text("Select customer visit","اختر زيارة العميل")}</option>{customerAppointments.map(a=><option key={a.id} value={a.id}>{new Date(a.appointment_at).toLocaleString(isArabic?"ar-SA":"en-SA",{hour12:true})} — {(isArabic?master?.services.find(s=>s.id===a.service_id)?.name_ar:master?.services.find(s=>s.id===a.service_id)?.name)||a.services?.name||text("No service","بدون خدمة")}</option>)}</select>
  {appointment&&<section className="space-y-3 rounded-2xl border border-emerald-200 bg-emerald-50/60 p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><PackageOpen className="text-emerald-700"/><div><b>{text("Visit procedures","إجراءات هذه الزيارة")}</b><p className="text-xs text-slate-500">{text("Add every procedure performed, even if it was not in the original booking","أضف أي إجراء تم تنفيذه حتى لو لم يكن في الحجز الأصلي")}</p></div></div><Button type="button" size="sm" onClick={add}><Plus className="h-4 w-4"/>{text("Another procedure","إجراء آخر")}</Button></div>{priced.map((line,index)=><div key={line.key} className="grid gap-2 rounded-xl border bg-white p-3 md:grid-cols-[1fr_1fr_120px_110px_40px]"><select value={line.serviceId||""} onChange={e=>update(line.key,{serviceId:Number(e.target.value),variantId:null,quantity:1})} className="rounded-md border px-2 py-2"><option value="">{text("Select procedure","اختر الإجراء")}</option>{availableServices.map(s=><option key={s.id} value={s.id}>{(isArabic?s.name_ar:s.name)||s.name}</option>)}</select><select value={line.variantId??""} disabled={!line.variants.length} onChange={e=>update(line.key,{variantId:Number(e.target.value)||null})} className="rounded-md border px-2 py-2 disabled:bg-slate-100"><option value="">{line.variants.length?text("Select material","اختر المادة"):text("No separate material","لا توجد مادة منفصلة")}</option>{line.variants.map(v=><option key={v.id} value={v.id}>{(isArabic?v.name_ar:v.name)||v.name}</option>)}</select><Input type="number" min="0.1" step="0.1" value={line.quantity} onChange={e=>update(line.key,{quantity:Number(e.target.value)})}/><div className="rounded-lg bg-slate-100 p-2 text-center text-sm font-black">{line.total.toLocaleString("en-SA",{maximumFractionDigits:2})} SAR</div><button type="button" disabled={index===0&&priced.length===1} onClick={()=>remove(line.key)} className="text-red-500 disabled:opacity-20"><Trash2 className="h-4 w-4"/></button></div>)}</section>}
  <div className="rounded-2xl bg-slate-950 p-4 text-white"><div className="grid gap-2 text-sm sm:grid-cols-3"><div><span className="text-slate-400">{text("Subtotal","قبل الضريبة")}</span><b className="block">{subtotal.toLocaleString("en-SA")} SAR</b></div><div><span className="text-slate-400">{text("VAT (fixed 15%)","الضريبة (ثابتة 15٪)")}</span><b className="block">{tax.toLocaleString("en-SA")} SAR</b></div><div><span className="text-slate-400">{text(`Discount (${discount}%)`,`الخصم (${discount}٪)`)}</span><b className="block text-amber-300">{discountAmount.toLocaleString("en-SA")} SAR</b></div></div><div className="mt-3 flex justify-between text-xl text-emerald-400"><span className="flex items-center gap-2"><Calculator/>{text("Total","الإجمالي")}</span><b>{total.toLocaleString("en-SA")} SAR</b></div><div className="mt-2 flex justify-between"><span>{text("Paid","المدفوع")}</span><b>{effectivePaid.toLocaleString("en-SA")} SAR</b></div><div className="mt-1 flex justify-between text-rose-300"><span>{text("Remaining","المتبقي")}</span><b>{balance.toLocaleString("en-SA")} SAR</b></div></div>
  <div><label className="mb-1 block text-sm font-bold">{text("Discount percentage","نسبة الخصم")}</label><div className="relative"><Input type="number" min="0" max="100" step="0.01" placeholder="0" value={discount||""} onChange={e=>setDiscount(Math.min(Math.max(Number(e.target.value),0),100))}/><span className={`pointer-events-none absolute top-1/2 -translate-y-1/2 text-slate-500 ${isArabic?"left-3":"right-3"}`}>%</span></div><p className="mt-1 text-xs text-slate-500">{text("VAT is calculated automatically at 15% after discount.","تُحسب الضريبة تلقائيًا بنسبة 15٪ بعد الخصم.")}</p></div><div className="grid grid-cols-2 gap-3"><select value={method} onChange={e=>setMethod(e.target.value)} className="rounded-md border px-3"><option value="cash">{text("Cash","نقدًا")}</option><option value="card">{text("Card","بطاقة")}</option><option value="bank_transfer">{text("Bank transfer","تحويل بنكي")}</option><option value="tabby">{text("Tabby","تابي")}</option><option value="tamara">{text("Tamara","تمارا")}</option><option value="other">{text("Other","أخرى")}</option></select><select value={status} onChange={e=>{setStatus(e.target.value);if(e.target.value==="pending")setPaid(0)}} className="rounded-md border px-3 py-2"><option value="paid">{text("Paid in full","مدفوع بالكامل")}</option><option value="partial">{text("Partially paid","مدفوع جزئيًا")}</option><option value="pending">{text("Unpaid","غير مدفوع")}</option><option value="refunded">{text("Refunded","مسترد")}</option><option value="cancelled">{text("Cancelled","ملغي")}</option></select></div>{status==="partial"&&<Input type="number" min="0" max={total} step="0.01" placeholder={text("Amount actually paid","المبلغ المدفوع فعليًا")} value={paid||""} onChange={e=>setPaid(Number(e.target.value))}/>}<Input type="datetime-local" value={paymentDate} onChange={e=>setPaymentDate(e.target.value)}/><div className="grid grid-cols-2 gap-3"><Input placeholder={text("Invoice number (generated automatically)","رقم الفاتورة (يتولد تلقائيًا)")} value={invoice} onChange={e=>setInvoice(e.target.value)}/><Input placeholder={text("Reference number","الرقم المرجعي")} value={reference} onChange={e=>setReference(e.target.value)}/></div><textarea placeholder={text("Invoice notes","ملاحظات الفاتورة")} value={notes} onChange={e=>setNotes(e.target.value)} className="min-h-20 w-full rounded-md border p-3"/><Button type="button" className="w-full" disabled={mutation.isPending||!valid} onClick={()=>void submit()}>{mutation.isPending?text("Issuing invoice...","جارٍ إصدار الفاتورة..."):text("Save independent invoice","حفظ كفاتورة مستقلة")}</Button>
 </div></DialogContent></Dialog>
}
