"use client";

import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Filter, UsersRound } from "lucide-react";
import AddAppointmentDialogV2 from "@/features/appointments/components/AddAppointmentDialogV2";
import AddCustomerDialog from "@/features/customers/components/AddCustomerDialog";
import CustomerTable from "@/features/customers/components/CustomerTable";
import { CatalogColorSelect } from "@/features/customers/components/PatientCatalogBadge";
import { getCustomerIdsByDoctorId, getCustomerIdsByServiceIds, getPatientTags, getReferralSources } from "@/features/customers/api/customer.api";
import { filterCustomers } from "@/features/customers/engine/filter-customers";
import { useCustomers } from "@/features/customers/hooks/useCustomers";
import { useClinic } from "@/features/clinic/hooks/useClinic";
import { usePermissionAccess } from "@/features/users/hooks/usePermissionAccess";
import { useMasterData } from "@/features/master-data/hooks/useMasterData";

const PER_PAGE = 50;
export default function CustomersPage() {
  const { clinic, selectedBranch } = useClinic();
  const access = usePermissionAccess();
  const { data: customers = [], isLoading, error } = useCustomers();
  const { data: master } = useMasterData();
  const tagCatalog = useQuery({ queryKey: ["patient-tags", clinic?.id], queryFn: () => getPatientTags(clinic?.id ?? 0), enabled: !!clinic?.id });
  const refCatalog = useQuery({ queryKey: ["referral-sources", clinic?.id], queryFn: () => getReferralSources(clinic?.id ?? 0), enabled: !!clinic?.id });
  const [search, setSearch] = useState(""); const [doctor, setDoctor] = useState("all"); const [branch, setBranch] = useState("all"); const [tag, setTag] = useState("all"); const [referral, setReferral] = useState("all"); const [insurance, setInsurance] = useState("all"); const [priceGroup, setPriceGroup] = useState("all"); const [page, setPage] = useState(1);
  const canView = access.can("customers.view", "customers.details.view", "customers.manage");
  const doctors = useMemo(() => master?.staff.filter((item) => item.is_active && item.role?.toLowerCase() === "doctor").map((item) => [item.id, item.staff_name] as [number, string]) ?? [], [master]);
  const branches = useMemo(() => master?.branches.filter((item) => item.is_active).map((item) => [item.id, item.name] as [number, string]) ?? [], [master]);
  const tags = useMemo(() => tagCatalog.data?.map((item) => [item.id, item.name, item.color] as [number, string, string]) ?? [], [tagCatalog.data]);
  const referrals = useMemo(() => refCatalog.data?.map((item) => [item.id, item.name, item.color] as [number, string, string]) ?? [], [refCatalog.data]);
  const insuranceCompanies = useMemo(() => [...new Set(customers.map((item) => item.insurance_company).filter((item): item is string => Boolean(item)))].map((name, index) => [index, name] as [number, string]), [customers]);
  const priceGroups = useMemo(() => [...new Set(customers.map((item) => item.price_group).filter((item): item is string => Boolean(item)))].map((name, index) => [index, name] as [number, string]), [customers]);
  const departmentServiceIds = useMemo(() => { if (!doctor.startsWith("department:") || !master) return []; const department = doctor.slice("department:".length); return master.services.filter((service) => { const value = [service.name, service.name_en, service.name_ar, service.category, service.category_en, service.category_ar].filter(Boolean).join(" ").toLowerCase(); if (department === "laser") return value.includes("laser hair removal") || value.includes("إزالة الشعر"); if (department === "bleaching") return value.includes("bleach") || value.includes("تشقير"); return value.includes("profacial") || value.includes("بروفاشيال"); }).map((service) => service.id); }, [doctor, master]);
  const departmentPatients = useQuery({ queryKey: ["customer-department-services", departmentServiceIds], queryFn: () => getCustomerIdsByServiceIds(departmentServiceIds), enabled: doctor.startsWith("department:") && departmentServiceIds.length > 0 });
  const departmentPatientIds = useMemo(() => new Set(departmentPatients.data ?? []), [departmentPatients.data]);
  const selectedDoctorId = !doctor.startsWith("department:") && doctor !== "all" ? Number(doctor) : 0;
  const doctorPatients = useQuery({ queryKey: ["customer-doctor-appointments", selectedDoctorId], queryFn: () => getCustomerIdsByDoctorId(selectedDoctorId), enabled: selectedDoctorId > 0 });
  const doctorPatientIds = useMemo(() => new Set(doctorPatients.data ?? []), [doctorPatients.data]);
  const selectedDoctorName = doctors.find(([id]) => id === selectedDoctorId)?.[1];
  const filtered = useMemo(() => filterCustomers(customers, { search, doctor, doctorName: selectedDoctorName, doctorPatientIds, departmentPatientIds, branch, tag, referral, insurance, priceGroup }), [customers, search, doctor, selectedDoctorName, doctorPatientIds, departmentPatientIds, branch, tag, referral, insurance, priceGroup]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / PER_PAGE)); const current = Math.min(page, totalPages); const visible = filtered.slice((current - 1) * PER_PAGE, current * PER_PAGE);
  const filter = (setter: (value: string) => void) => (event: React.ChangeEvent<HTMLSelectElement>) => { setter(event.target.value); setPage(1); };
  return <div className="space-y-3" dir="rtl"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-black"><UsersRound className="text-sky-600" />المرضى <span className="rounded-full bg-sky-100 px-3 py-1 text-sm text-sky-700">{filtered.length}</span></h1><p className="text-sm text-slate-500">سجل موحد للبيانات والمواعيد والرصيد والإحالات والعلامات</p></div>{clinic && selectedBranch && <div className="flex gap-2">{access.can("customers.create", "customers.manage") && <AddCustomerDialog clinicId={clinic.id} branchId={selectedBranch.id} />}{access.can("appointments.create", "appointments.manage") && <AddAppointmentDialogV2 clinicId={clinic.id} branchId={selectedBranch.id} />}</div>}</header>
    <section className="grid gap-2 rounded-xl border bg-white p-3 shadow-sm md:grid-cols-3 xl:grid-cols-8"><label className="flex items-center gap-2 rounded-lg border px-3"><Filter className="size-4 text-slate-400" /><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="الاسم، الهاتف، الملف، الهوية..." className="h-10 min-w-0 flex-1 outline-none" /></label><Select value={branch} onChange={filter(setBranch)} label="كل الفروع" options={branches} /><Select value={doctor} onChange={filter(setDoctor)} label="طبيب" options={doctors} /><Select value={tag} onChange={filter(setTag)} label="كل العلامات" options={tags} /><Select value={referral} onChange={filter(setReferral)} label="كل الإحالات" options={referrals} /><TextSelect value={insurance} onChange={filter(setInsurance)} label="كل شركات التأمين" options={insuranceCompanies} /><TextSelect value={priceGroup} onChange={filter(setPriceGroup)} label="كل مجموعات الأسعار" options={priceGroups} /><button onClick={() => { setSearch(""); setBranch("all"); setDoctor("all"); setTag("all"); setReferral("all"); setInsurance("all"); setPriceGroup("all"); setPage(1); }} className="h-10 rounded-lg border font-bold">إزالة الفلاتر</button></section>
    {isLoading && <div className="rounded-xl bg-white p-10 text-center">جارٍ تحميل المرضى...</div>}{error && <div className="rounded-xl bg-red-50 p-5 text-red-700">{error.message}</div>}{!access.isLoading && !canView && <div className="rounded-xl bg-amber-50 p-5 text-amber-800">نتائج المرضى غير متوفرة لك حسب صلاحيات حسابك.</div>}{canView && !isLoading && !error && <><CustomerTable customers={visible} /><nav className="flex items-center justify-between rounded-xl border bg-white px-4 py-2 text-sm"><span>{filtered.length ? `${(current - 1) * PER_PAGE + 1}-${Math.min(current * PER_PAGE, filtered.length)} من ${filtered.length}` : "0"}</span><div className="flex items-center gap-2"><button disabled={current === 1} onClick={() => setPage((p) => Math.max(1, p - 1))} className="rounded border px-3 py-1 disabled:opacity-30">السابق</button><span>{current} / {totalPages}</span><button disabled={current === totalPages} onClick={() => setPage((p) => Math.min(totalPages, p + 1))} className="rounded border px-3 py-1 disabled:opacity-30">التالي</button></div></nav></>}
  </div>;
}
function Select({ value, onChange, label, options }: { value: string; onChange: (e: React.ChangeEvent<HTMLSelectElement>) => void; label: string; options: Array<[number, string] | [number, string, string]> }) { const isCatalogFilter = label === "كل العلامات" || label === "All tags" || label === "كل الإحالات" || label === "All referrals"; if (isCatalogFilter) return <CatalogColorSelect value={value} onValueChange={(next) => onChange({ target: { value: next } } as React.ChangeEvent<HTMLSelectElement>)} label={label} options={options.map(([id,name,color])=>[id,name,color||"#516e84"])} />; const isDoctorFilter = label === "طبيب" || label === "Doctor"; return <select value={value} onChange={onChange} className="h-10 rounded-lg border px-3 font-bold"><option value="all">{label}</option>{options.map(([id, name]) => <option key={id} value={id}>{name}</option>)}{isDoctorFilter&&<optgroup label="Departments"><option value="department:laser">Laser Department</option><option value="department:bleaching">Hair Bleaching</option><option value="department:profacial">ProFacial</option></optgroup>}</select>; }
function TextSelect({ value, onChange, label, options }: { value: string; onChange: (e: React.ChangeEvent<HTMLSelectElement>) => void; label: string; options: Array<[number, string]> }) { return <select value={value} onChange={onChange} className="h-10 rounded-lg border px-3"><option value="all">{label}</option>{options.map(([id, name]) => <option key={id} value={name}>{name}</option>)}</select>; }
